/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrganisationalUnit,
  OrganisationalUnit$inboundSchema,
  OrganisationalUnit$Outbound,
  OrganisationalUnit$outboundSchema,
} from "./organisationalunit.js";

export type AwsOrganisationalUnitRequest = {
  /**
   * AWS Control Tower Management Account ID.
   */
  mgmtAccountId: string;
  /**
   * Organisational Structure of the AWS Account.
   */
  structure: Array<OrganisationalUnit>;
};

/** @internal */
export const AwsOrganisationalUnitRequest$inboundSchema: z.ZodType<
  AwsOrganisationalUnitRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mgmtAccountId: z.string(),
  structure: z.array(OrganisationalUnit$inboundSchema),
});

/** @internal */
export type AwsOrganisationalUnitRequest$Outbound = {
  mgmtAccountId: string;
  structure: Array<OrganisationalUnit$Outbound>;
};

/** @internal */
export const AwsOrganisationalUnitRequest$outboundSchema: z.ZodType<
  AwsOrganisationalUnitRequest$Outbound,
  z.ZodTypeDef,
  AwsOrganisationalUnitRequest
> = z.object({
  mgmtAccountId: z.string(),
  structure: z.array(OrganisationalUnit$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AwsOrganisationalUnitRequest$ {
  /** @deprecated use `AwsOrganisationalUnitRequest$inboundSchema` instead. */
  export const inboundSchema = AwsOrganisationalUnitRequest$inboundSchema;
  /** @deprecated use `AwsOrganisationalUnitRequest$outboundSchema` instead. */
  export const outboundSchema = AwsOrganisationalUnitRequest$outboundSchema;
  /** @deprecated use `AwsOrganisationalUnitRequest$Outbound` instead. */
  export type Outbound = AwsOrganisationalUnitRequest$Outbound;
}

export function awsOrganisationalUnitRequestToJSON(
  awsOrganisationalUnitRequest: AwsOrganisationalUnitRequest,
): string {
  return JSON.stringify(
    AwsOrganisationalUnitRequest$outboundSchema.parse(
      awsOrganisationalUnitRequest,
    ),
  );
}

export function awsOrganisationalUnitRequestFromJSON(
  jsonString: string,
): SafeParseResult<AwsOrganisationalUnitRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AwsOrganisationalUnitRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AwsOrganisationalUnitRequest' from JSON`,
  );
}
