/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CloudAccountsAwsMgmtAccountOnboardingResponse = {
  /**
   * True if the Management Account is onboarded, false otherwise.
   */
  isOnboarded: boolean;
};

/** @internal */
export const CloudAccountsAwsMgmtAccountOnboardingResponse$inboundSchema:
  z.ZodType<
    CloudAccountsAwsMgmtAccountOnboardingResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    isOnboarded: z.boolean(),
  });
/** @internal */
export type CloudAccountsAwsMgmtAccountOnboardingResponse$Outbound = {
  isOnboarded: boolean;
};

/** @internal */
export const CloudAccountsAwsMgmtAccountOnboardingResponse$outboundSchema:
  z.ZodType<
    CloudAccountsAwsMgmtAccountOnboardingResponse$Outbound,
    z.ZodTypeDef,
    CloudAccountsAwsMgmtAccountOnboardingResponse
  > = z.object({
    isOnboarded: z.boolean(),
  });

export function cloudAccountsAwsMgmtAccountOnboardingResponseToJSON(
  cloudAccountsAwsMgmtAccountOnboardingResponse:
    CloudAccountsAwsMgmtAccountOnboardingResponse,
): string {
  return JSON.stringify(
    CloudAccountsAwsMgmtAccountOnboardingResponse$outboundSchema.parse(
      cloudAccountsAwsMgmtAccountOnboardingResponse,
    ),
  );
}
export function cloudAccountsAwsMgmtAccountOnboardingResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CloudAccountsAwsMgmtAccountOnboardingResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CloudAccountsAwsMgmtAccountOnboardingResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CloudAccountsAwsMgmtAccountOnboardingResponse' from JSON`,
  );
}
