/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CloudAccountsAwsUpdateIntegrationRequest = {
  /**
   * AWS Control Tower Management Account ID.
   */
  managementAccountId: string;
  /**
   * AWS Accounts ID to be integrated.
   */
  accountId: string;
  /**
   * Name of the AWS Account.
   */
  accountName: string;
  /**
   * Role ARN to be assumed by the AWS Account.
   */
  roleArn: string;
  /**
   * AWS Account ID.
   */
  orgUnitId?: string | undefined;
  /**
   * AWS Organizational Unit Name.
   */
  orgUnitName?: string | undefined;
  /**
   * Immediate Parent Organization Unit ID of the AWS Account to be integrated.
   */
  parentOrgUnitId?: string | undefined;
};

/** @internal */
export const CloudAccountsAwsUpdateIntegrationRequest$inboundSchema: z.ZodType<
  CloudAccountsAwsUpdateIntegrationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  managementAccountId: z.string(),
  accountId: z.string(),
  accountName: z.string(),
  roleArn: z.string(),
  orgUnitId: z.string().optional(),
  orgUnitName: z.string().optional(),
  parentOrgUnitId: z.string().optional(),
});

/** @internal */
export type CloudAccountsAwsUpdateIntegrationRequest$Outbound = {
  managementAccountId: string;
  accountId: string;
  accountName: string;
  roleArn: string;
  orgUnitId?: string | undefined;
  orgUnitName?: string | undefined;
  parentOrgUnitId?: string | undefined;
};

/** @internal */
export const CloudAccountsAwsUpdateIntegrationRequest$outboundSchema: z.ZodType<
  CloudAccountsAwsUpdateIntegrationRequest$Outbound,
  z.ZodTypeDef,
  CloudAccountsAwsUpdateIntegrationRequest
> = z.object({
  managementAccountId: z.string(),
  accountId: z.string(),
  accountName: z.string(),
  roleArn: z.string(),
  orgUnitId: z.string().optional(),
  orgUnitName: z.string().optional(),
  parentOrgUnitId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CloudAccountsAwsUpdateIntegrationRequest$ {
  /** @deprecated use `CloudAccountsAwsUpdateIntegrationRequest$inboundSchema` instead. */
  export const inboundSchema =
    CloudAccountsAwsUpdateIntegrationRequest$inboundSchema;
  /** @deprecated use `CloudAccountsAwsUpdateIntegrationRequest$outboundSchema` instead. */
  export const outboundSchema =
    CloudAccountsAwsUpdateIntegrationRequest$outboundSchema;
  /** @deprecated use `CloudAccountsAwsUpdateIntegrationRequest$Outbound` instead. */
  export type Outbound = CloudAccountsAwsUpdateIntegrationRequest$Outbound;
}

export function cloudAccountsAwsUpdateIntegrationRequestToJSON(
  cloudAccountsAwsUpdateIntegrationRequest:
    CloudAccountsAwsUpdateIntegrationRequest,
): string {
  return JSON.stringify(
    CloudAccountsAwsUpdateIntegrationRequest$outboundSchema.parse(
      cloudAccountsAwsUpdateIntegrationRequest,
    ),
  );
}

export function cloudAccountsAwsUpdateIntegrationRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  CloudAccountsAwsUpdateIntegrationRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CloudAccountsAwsUpdateIntegrationRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CloudAccountsAwsUpdateIntegrationRequest' from JSON`,
  );
}
