/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CloudAccountsAwsMgmtAccountOnboardingResponse = {
  /**
   * True if the Management Account is onboarded, false otherwise.
   */
  isOnboarded: boolean;
};

/** @internal */
export const CloudAccountsAwsMgmtAccountOnboardingResponse$inboundSchema:
  z.ZodType<
    CloudAccountsAwsMgmtAccountOnboardingResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    isOnboarded: z.boolean(),
  });

/** @internal */
export type CloudAccountsAwsMgmtAccountOnboardingResponse$Outbound = {
  isOnboarded: boolean;
};

/** @internal */
export const CloudAccountsAwsMgmtAccountOnboardingResponse$outboundSchema:
  z.ZodType<
    CloudAccountsAwsMgmtAccountOnboardingResponse$Outbound,
    z.ZodTypeDef,
    CloudAccountsAwsMgmtAccountOnboardingResponse
  > = z.object({
    isOnboarded: z.boolean(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CloudAccountsAwsMgmtAccountOnboardingResponse$ {
  /** @deprecated use `CloudAccountsAwsMgmtAccountOnboardingResponse$inboundSchema` instead. */
  export const inboundSchema =
    CloudAccountsAwsMgmtAccountOnboardingResponse$inboundSchema;
  /** @deprecated use `CloudAccountsAwsMgmtAccountOnboardingResponse$outboundSchema` instead. */
  export const outboundSchema =
    CloudAccountsAwsMgmtAccountOnboardingResponse$outboundSchema;
  /** @deprecated use `CloudAccountsAwsMgmtAccountOnboardingResponse$Outbound` instead. */
  export type Outbound = CloudAccountsAwsMgmtAccountOnboardingResponse$Outbound;
}

export function cloudAccountsAwsMgmtAccountOnboardingResponseToJSON(
  cloudAccountsAwsMgmtAccountOnboardingResponse:
    CloudAccountsAwsMgmtAccountOnboardingResponse,
): string {
  return JSON.stringify(
    CloudAccountsAwsMgmtAccountOnboardingResponse$outboundSchema.parse(
      cloudAccountsAwsMgmtAccountOnboardingResponse,
    ),
  );
}

export function cloudAccountsAwsMgmtAccountOnboardingResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CloudAccountsAwsMgmtAccountOnboardingResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CloudAccountsAwsMgmtAccountOnboardingResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CloudAccountsAwsMgmtAccountOnboardingResponse' from JSON`,
  );
}
