/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CommonKeyValuePair = {
  /**
   * Key.
   */
  key: string;
  /**
   * Value.
   */
  value: string;
};

/** @internal */
export const CommonKeyValuePair$inboundSchema: z.ZodType<
  CommonKeyValuePair,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  value: z.string(),
});
/** @internal */
export type CommonKeyValuePair$Outbound = {
  key: string;
  value: string;
};

/** @internal */
export const CommonKeyValuePair$outboundSchema: z.ZodType<
  CommonKeyValuePair$Outbound,
  z.ZodTypeDef,
  CommonKeyValuePair
> = z.object({
  key: z.string(),
  value: z.string(),
});

export function commonKeyValuePairToJSON(
  commonKeyValuePair: CommonKeyValuePair,
): string {
  return JSON.stringify(
    CommonKeyValuePair$outboundSchema.parse(commonKeyValuePair),
  );
}
export function commonKeyValuePairFromJSON(
  jsonString: string,
): SafeParseResult<CommonKeyValuePair, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommonKeyValuePair$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommonKeyValuePair' from JSON`,
  );
}
