/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CommonTag = {
  /**
   * Tag key.
   */
  key: string;
  /**
   * Tag value.
   */
  value: string;
};

/** @internal */
export const CommonTag$inboundSchema: z.ZodType<
  CommonTag,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  value: z.string(),
});
/** @internal */
export type CommonTag$Outbound = {
  key: string;
  value: string;
};

/** @internal */
export const CommonTag$outboundSchema: z.ZodType<
  CommonTag$Outbound,
  z.ZodTypeDef,
  CommonTag
> = z.object({
  key: z.string(),
  value: z.string(),
});

export function commonTagToJSON(commonTag: CommonTag): string {
  return JSON.stringify(CommonTag$outboundSchema.parse(commonTag));
}
export function commonTagFromJSON(
  jsonString: string,
): SafeParseResult<CommonTag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommonTag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommonTag' from JSON`,
  );
}
