/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CompositeMetric = {
  /**
   * Name of the composite metric
   */
  name: string;
  /**
   * Display name of the composite metric. A short description of the metric.
   */
  displayName: string;
  /**
   * Description of the composite metric. A detailed description of the metric.
   */
  description: string;
  /**
   * PromQL query to calculate the composite metric
   */
  formula: string;
  /**
   * Unit of the composite metric
   */
  units: string;
};

/** @internal */
export const CompositeMetric$inboundSchema: z.ZodType<
  CompositeMetric,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  displayName: z.string(),
  description: z.string(),
  formula: z.string(),
  units: z.string(),
});

/** @internal */
export type CompositeMetric$Outbound = {
  name: string;
  displayName: string;
  description: string;
  formula: string;
  units: string;
};

/** @internal */
export const CompositeMetric$outboundSchema: z.ZodType<
  CompositeMetric$Outbound,
  z.ZodTypeDef,
  CompositeMetric
> = z.object({
  name: z.string(),
  displayName: z.string(),
  description: z.string(),
  formula: z.string(),
  units: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompositeMetric$ {
  /** @deprecated use `CompositeMetric$inboundSchema` instead. */
  export const inboundSchema = CompositeMetric$inboundSchema;
  /** @deprecated use `CompositeMetric$outboundSchema` instead. */
  export const outboundSchema = CompositeMetric$outboundSchema;
  /** @deprecated use `CompositeMetric$Outbound` instead. */
  export type Outbound = CompositeMetric$Outbound;
}

export function compositeMetricToJSON(
  compositeMetric: CompositeMetric,
): string {
  return JSON.stringify(CompositeMetric$outboundSchema.parse(compositeMetric));
}

export function compositeMetricFromJSON(
  jsonString: string,
): SafeParseResult<CompositeMetric, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompositeMetric$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompositeMetric' from JSON`,
  );
}
