/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Tags = {
  server: string;
  tagWithoutValue: string;
};

export const CreateTokenRequestType = {
  Ingestion: "ingestion",
} as const;
export type CreateTokenRequestType = ClosedEnum<typeof CreateTokenRequestType>;

export type CreateTokenRequest = {
  name: string;
  tags: Tags;
  type: CreateTokenRequestType;
};

/** @internal */
export const Tags$inboundSchema: z.ZodType<Tags, z.ZodTypeDef, unknown> = z
  .object({
    server: z.string(),
    tag_without_value: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "tag_without_value": "tagWithoutValue",
    });
  });

/** @internal */
export type Tags$Outbound = {
  server: string;
  tag_without_value: string;
};

/** @internal */
export const Tags$outboundSchema: z.ZodType<Tags$Outbound, z.ZodTypeDef, Tags> =
  z.object({
    server: z.string(),
    tagWithoutValue: z.string(),
  }).transform((v) => {
    return remap$(v, {
      tagWithoutValue: "tag_without_value",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Tags$ {
  /** @deprecated use `Tags$inboundSchema` instead. */
  export const inboundSchema = Tags$inboundSchema;
  /** @deprecated use `Tags$outboundSchema` instead. */
  export const outboundSchema = Tags$outboundSchema;
  /** @deprecated use `Tags$Outbound` instead. */
  export type Outbound = Tags$Outbound;
}

export function tagsToJSON(tags: Tags): string {
  return JSON.stringify(Tags$outboundSchema.parse(tags));
}

export function tagsFromJSON(
  jsonString: string,
): SafeParseResult<Tags, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tags$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tags' from JSON`,
  );
}

/** @internal */
export const CreateTokenRequestType$inboundSchema: z.ZodNativeEnum<
  typeof CreateTokenRequestType
> = z.nativeEnum(CreateTokenRequestType);

/** @internal */
export const CreateTokenRequestType$outboundSchema: z.ZodNativeEnum<
  typeof CreateTokenRequestType
> = CreateTokenRequestType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTokenRequestType$ {
  /** @deprecated use `CreateTokenRequestType$inboundSchema` instead. */
  export const inboundSchema = CreateTokenRequestType$inboundSchema;
  /** @deprecated use `CreateTokenRequestType$outboundSchema` instead. */
  export const outboundSchema = CreateTokenRequestType$outboundSchema;
}

/** @internal */
export const CreateTokenRequest$inboundSchema: z.ZodType<
  CreateTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  tags: z.lazy(() => Tags$inboundSchema),
  type: CreateTokenRequestType$inboundSchema,
});

/** @internal */
export type CreateTokenRequest$Outbound = {
  name: string;
  tags: Tags$Outbound;
  type: string;
};

/** @internal */
export const CreateTokenRequest$outboundSchema: z.ZodType<
  CreateTokenRequest$Outbound,
  z.ZodTypeDef,
  CreateTokenRequest
> = z.object({
  name: z.string(),
  tags: z.lazy(() => Tags$outboundSchema),
  type: CreateTokenRequestType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTokenRequest$ {
  /** @deprecated use `CreateTokenRequest$inboundSchema` instead. */
  export const inboundSchema = CreateTokenRequest$inboundSchema;
  /** @deprecated use `CreateTokenRequest$outboundSchema` instead. */
  export const outboundSchema = CreateTokenRequest$outboundSchema;
  /** @deprecated use `CreateTokenRequest$Outbound` instead. */
  export type Outbound = CreateTokenRequest$Outbound;
}

export function createTokenRequestToJSON(
  createTokenRequest: CreateTokenRequest,
): string {
  return JSON.stringify(
    CreateTokenRequest$outboundSchema.parse(createTokenRequest),
  );
}

export function createTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTokenRequest' from JSON`,
  );
}
