/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const DatabaseMetricsCaptureMethod = {
  Sniffer: "sniffer",
  Poll: "poll",
  Profiler: "profiler",
  SlowLog: "slow-log",
} as const;
export type DatabaseMetricsCaptureMethod = ClosedEnum<
  typeof DatabaseMetricsCaptureMethod
>;

/** @internal */
export const DatabaseMetricsCaptureMethod$inboundSchema: z.ZodNativeEnum<
  typeof DatabaseMetricsCaptureMethod
> = z.nativeEnum(DatabaseMetricsCaptureMethod);

/** @internal */
export const DatabaseMetricsCaptureMethod$outboundSchema: z.ZodNativeEnum<
  typeof DatabaseMetricsCaptureMethod
> = DatabaseMetricsCaptureMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatabaseMetricsCaptureMethod$ {
  /** @deprecated use `DatabaseMetricsCaptureMethod$inboundSchema` instead. */
  export const inboundSchema = DatabaseMetricsCaptureMethod$inboundSchema;
  /** @deprecated use `DatabaseMetricsCaptureMethod$outboundSchema` instead. */
  export const outboundSchema = DatabaseMetricsCaptureMethod$outboundSchema;
}
