/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DatabaseCredentialsPublicKeyResponse = {
  /**
   *   Public Key for locally encrypting database credentials before using in database connectivity options
   *
   * @remarks
   *   in observe or update Database call
   */
  publicKey: string;
};

/** @internal */
export const DatabaseCredentialsPublicKeyResponse$inboundSchema: z.ZodType<
  DatabaseCredentialsPublicKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  publicKey: z.string(),
});

/** @internal */
export type DatabaseCredentialsPublicKeyResponse$Outbound = {
  publicKey: string;
};

/** @internal */
export const DatabaseCredentialsPublicKeyResponse$outboundSchema: z.ZodType<
  DatabaseCredentialsPublicKeyResponse$Outbound,
  z.ZodTypeDef,
  DatabaseCredentialsPublicKeyResponse
> = z.object({
  publicKey: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatabaseCredentialsPublicKeyResponse$ {
  /** @deprecated use `DatabaseCredentialsPublicKeyResponse$inboundSchema` instead. */
  export const inboundSchema =
    DatabaseCredentialsPublicKeyResponse$inboundSchema;
  /** @deprecated use `DatabaseCredentialsPublicKeyResponse$outboundSchema` instead. */
  export const outboundSchema =
    DatabaseCredentialsPublicKeyResponse$outboundSchema;
  /** @deprecated use `DatabaseCredentialsPublicKeyResponse$Outbound` instead. */
  export type Outbound = DatabaseCredentialsPublicKeyResponse$Outbound;
}

export function databaseCredentialsPublicKeyResponseToJSON(
  databaseCredentialsPublicKeyResponse: DatabaseCredentialsPublicKeyResponse,
): string {
  return JSON.stringify(
    DatabaseCredentialsPublicKeyResponse$outboundSchema.parse(
      databaseCredentialsPublicKeyResponse,
    ),
  );
}

export function databaseCredentialsPublicKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<DatabaseCredentialsPublicKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DatabaseCredentialsPublicKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatabaseCredentialsPublicKeyResponse' from JSON`,
  );
}
