/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const DatabaseType = {
  Mysql: "mysql",
  Mongo: "mongo",
  Mssql: "mssql",
  Redis: "redis",
  Pgsql: "pgsql",
} as const;
export type DatabaseType = ClosedEnum<typeof DatabaseType>;

/** @internal */
export const DatabaseType$inboundSchema: z.ZodNativeEnum<typeof DatabaseType> =
  z.nativeEnum(DatabaseType);

/** @internal */
export const DatabaseType$outboundSchema: z.ZodNativeEnum<typeof DatabaseType> =
  DatabaseType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatabaseType$ {
  /** @deprecated use `DatabaseType$inboundSchema` instead. */
  export const inboundSchema = DatabaseType$inboundSchema;
  /** @deprecated use `DatabaseType$outboundSchema` instead. */
  export const outboundSchema = DatabaseType$outboundSchema;
}
