/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DatabaseSslOptionsUpdate,
  DatabaseSslOptionsUpdate$inboundSchema,
  DatabaseSslOptionsUpdate$Outbound,
  DatabaseSslOptionsUpdate$outboundSchema,
} from "./databasessloptionsupdate.js";

export type DatabaseConnectionOptionsUpdate = {
  /**
   * Database server host
   */
  host?: string | undefined;
  /**
   * Database server port
   */
  port?: string | undefined;
  /**
   * Database schema name
   */
  dbname?: string | undefined;
  /**
   * Encrypted credentials for connecting to the database server when using basic authentication (username, password)
   *
   * @remarks
   * can be generated using this command:
   * ./dbo-headless-installer -swoparams=<SwoParamasJsonFile> --encrypt-creds --user=<USERNAME> --password=<PASSWORD>
   * Use the dbo-headless-installer binary located at:
   * https://agent-binaries.cloud.solarwinds.com/?prefix=dbo-headless-installer/latest/
   */
  encryptedCredentials?: string | undefined;
  /**
   * Username for connecting to database server needed only for auth methods other than basic auth
   */
  user?: string | undefined;
  /**
   * Enable ssl when agent connects to database server
   */
  sslEnabled?: boolean | undefined;
  /**
   * SSL connection options, when sslEnabled is true
   */
  sslOptions?: DatabaseSslOptionsUpdate | undefined;
  /**
   * Cloud region in case of database managed by cloud provider, required for IAM authentication
   */
  cloudRegion?: string | undefined;
  /**
   * binding for packet sniffing for sniffer captureMethod (on-host), example: 0.0.0.0:6379,[::]:6379
   */
  bindings?: string | undefined;
};

/** @internal */
export const DatabaseConnectionOptionsUpdate$inboundSchema: z.ZodType<
  DatabaseConnectionOptionsUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  host: z.string().optional(),
  port: z.string().default(""),
  dbname: z.string().default(""),
  encryptedCredentials: z.string().default(""),
  user: z.string().default(""),
  sslEnabled: z.boolean().default(false),
  sslOptions: DatabaseSslOptionsUpdate$inboundSchema.optional(),
  cloudRegion: z.string().default(""),
  bindings: z.string().default(""),
});

/** @internal */
export type DatabaseConnectionOptionsUpdate$Outbound = {
  host?: string | undefined;
  port: string;
  dbname: string;
  encryptedCredentials: string;
  user: string;
  sslEnabled: boolean;
  sslOptions?: DatabaseSslOptionsUpdate$Outbound | undefined;
  cloudRegion: string;
  bindings: string;
};

/** @internal */
export const DatabaseConnectionOptionsUpdate$outboundSchema: z.ZodType<
  DatabaseConnectionOptionsUpdate$Outbound,
  z.ZodTypeDef,
  DatabaseConnectionOptionsUpdate
> = z.object({
  host: z.string().optional(),
  port: z.string().default(""),
  dbname: z.string().default(""),
  encryptedCredentials: z.string().default(""),
  user: z.string().default(""),
  sslEnabled: z.boolean().default(false),
  sslOptions: DatabaseSslOptionsUpdate$outboundSchema.optional(),
  cloudRegion: z.string().default(""),
  bindings: z.string().default(""),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatabaseConnectionOptionsUpdate$ {
  /** @deprecated use `DatabaseConnectionOptionsUpdate$inboundSchema` instead. */
  export const inboundSchema = DatabaseConnectionOptionsUpdate$inboundSchema;
  /** @deprecated use `DatabaseConnectionOptionsUpdate$outboundSchema` instead. */
  export const outboundSchema = DatabaseConnectionOptionsUpdate$outboundSchema;
  /** @deprecated use `DatabaseConnectionOptionsUpdate$Outbound` instead. */
  export type Outbound = DatabaseConnectionOptionsUpdate$Outbound;
}

export function databaseConnectionOptionsUpdateToJSON(
  databaseConnectionOptionsUpdate: DatabaseConnectionOptionsUpdate,
): string {
  return JSON.stringify(
    DatabaseConnectionOptionsUpdate$outboundSchema.parse(
      databaseConnectionOptionsUpdate,
    ),
  );
}

export function databaseConnectionOptionsUpdateFromJSON(
  jsonString: string,
): SafeParseResult<DatabaseConnectionOptionsUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatabaseConnectionOptionsUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatabaseConnectionOptionsUpdate' from JSON`,
  );
}
