/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DatabasePluginStatus = {
  /**
   * Name of plugin observing database server
   */
  pluginName: string;
  /**
   * Deployment Status of plugin observing database server
   */
  deploymentStatus: string;
  /**
   * Health Status of plugin observing database server
   */
  healthStatus: string;
};

/** @internal */
export const DatabasePluginStatus$inboundSchema: z.ZodType<
  DatabasePluginStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  pluginName: z.string(),
  deploymentStatus: z.string(),
  healthStatus: z.string(),
});

/** @internal */
export type DatabasePluginStatus$Outbound = {
  pluginName: string;
  deploymentStatus: string;
  healthStatus: string;
};

/** @internal */
export const DatabasePluginStatus$outboundSchema: z.ZodType<
  DatabasePluginStatus$Outbound,
  z.ZodTypeDef,
  DatabasePluginStatus
> = z.object({
  pluginName: z.string(),
  deploymentStatus: z.string(),
  healthStatus: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatabasePluginStatus$ {
  /** @deprecated use `DatabasePluginStatus$inboundSchema` instead. */
  export const inboundSchema = DatabasePluginStatus$inboundSchema;
  /** @deprecated use `DatabasePluginStatus$outboundSchema` instead. */
  export const outboundSchema = DatabasePluginStatus$outboundSchema;
  /** @deprecated use `DatabasePluginStatus$Outbound` instead. */
  export type Outbound = DatabasePluginStatus$Outbound;
}

export function databasePluginStatusToJSON(
  databasePluginStatus: DatabasePluginStatus,
): string {
  return JSON.stringify(
    DatabasePluginStatus$outboundSchema.parse(databasePluginStatus),
  );
}

export function databasePluginStatusFromJSON(
  jsonString: string,
): SafeParseResult<DatabasePluginStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatabasePluginStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatabasePluginStatus' from JSON`,
  );
}
