/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const DatabaseAuthMethod = {
  Basic: "basic",
  Awsiam: "awsiam",
  Windows: "windows",
  Entraclientcert: "entraclientcert",
  Entraclientsecret: "entraclientsecret",
  Cert: "cert",
} as const;
export type DatabaseAuthMethod = ClosedEnum<typeof DatabaseAuthMethod>;

/** @internal */
export const DatabaseAuthMethod$inboundSchema: z.ZodNativeEnum<
  typeof DatabaseAuthMethod
> = z.nativeEnum(DatabaseAuthMethod);

/** @internal */
export const DatabaseAuthMethod$outboundSchema: z.ZodNativeEnum<
  typeof DatabaseAuthMethod
> = DatabaseAuthMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatabaseAuthMethod$ {
  /** @deprecated use `DatabaseAuthMethod$inboundSchema` instead. */
  export const inboundSchema = DatabaseAuthMethod$inboundSchema;
  /** @deprecated use `DatabaseAuthMethod$outboundSchema` instead. */
  export const outboundSchema = DatabaseAuthMethod$outboundSchema;
}
