/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DatabasePluginStatus,
  DatabasePluginStatus$inboundSchema,
  DatabasePluginStatus$Outbound,
  DatabasePluginStatus$outboundSchema,
} from "./databasepluginstatus.js";

export type DatabasePluginStatusResponse = {
  /**
   * Status of plugin(s) observing database server
   */
  plugins: Array<DatabasePluginStatus>;
};

/** @internal */
export const DatabasePluginStatusResponse$inboundSchema: z.ZodType<
  DatabasePluginStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  plugins: z.array(DatabasePluginStatus$inboundSchema),
});

/** @internal */
export type DatabasePluginStatusResponse$Outbound = {
  plugins: Array<DatabasePluginStatus$Outbound>;
};

/** @internal */
export const DatabasePluginStatusResponse$outboundSchema: z.ZodType<
  DatabasePluginStatusResponse$Outbound,
  z.ZodTypeDef,
  DatabasePluginStatusResponse
> = z.object({
  plugins: z.array(DatabasePluginStatus$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatabasePluginStatusResponse$ {
  /** @deprecated use `DatabasePluginStatusResponse$inboundSchema` instead. */
  export const inboundSchema = DatabasePluginStatusResponse$inboundSchema;
  /** @deprecated use `DatabasePluginStatusResponse$outboundSchema` instead. */
  export const outboundSchema = DatabasePluginStatusResponse$outboundSchema;
  /** @deprecated use `DatabasePluginStatusResponse$Outbound` instead. */
  export type Outbound = DatabasePluginStatusResponse$Outbound;
}

export function databasePluginStatusResponseToJSON(
  databasePluginStatusResponse: DatabasePluginStatusResponse,
): string {
  return JSON.stringify(
    DatabasePluginStatusResponse$outboundSchema.parse(
      databasePluginStatusResponse,
    ),
  );
}

export function databasePluginStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<DatabasePluginStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DatabasePluginStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DatabasePluginStatusResponse' from JSON`,
  );
}
