/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DboDatabasePluginStatus,
  DboDatabasePluginStatus$inboundSchema,
  DboDatabasePluginStatus$Outbound,
  DboDatabasePluginStatus$outboundSchema,
} from "./dbodatabasepluginstatus.js";

export type DboDatabasePluginStatusResponse = {
  /**
   * Status of plugin(s) observing database server
   */
  plugins: Array<DboDatabasePluginStatus>;
};

/** @internal */
export const DboDatabasePluginStatusResponse$inboundSchema: z.ZodType<
  DboDatabasePluginStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  plugins: z.array(DboDatabasePluginStatus$inboundSchema),
});

/** @internal */
export type DboDatabasePluginStatusResponse$Outbound = {
  plugins: Array<DboDatabasePluginStatus$Outbound>;
};

/** @internal */
export const DboDatabasePluginStatusResponse$outboundSchema: z.ZodType<
  DboDatabasePluginStatusResponse$Outbound,
  z.ZodTypeDef,
  DboDatabasePluginStatusResponse
> = z.object({
  plugins: z.array(DboDatabasePluginStatus$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DboDatabasePluginStatusResponse$ {
  /** @deprecated use `DboDatabasePluginStatusResponse$inboundSchema` instead. */
  export const inboundSchema = DboDatabasePluginStatusResponse$inboundSchema;
  /** @deprecated use `DboDatabasePluginStatusResponse$outboundSchema` instead. */
  export const outboundSchema = DboDatabasePluginStatusResponse$outboundSchema;
  /** @deprecated use `DboDatabasePluginStatusResponse$Outbound` instead. */
  export type Outbound = DboDatabasePluginStatusResponse$Outbound;
}

export function dboDatabasePluginStatusResponseToJSON(
  dboDatabasePluginStatusResponse: DboDatabasePluginStatusResponse,
): string {
  return JSON.stringify(
    DboDatabasePluginStatusResponse$outboundSchema.parse(
      dboDatabasePluginStatusResponse,
    ),
  );
}

export function dboDatabasePluginStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<DboDatabasePluginStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DboDatabasePluginStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DboDatabasePluginStatusResponse' from JSON`,
  );
}
