/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * SSL mode such as require, verify-ca, verify-full as applicable
 */
export const DboDatabaseSslOptionsSslMode = {
  Require: "require",
  VerifyCa: "verify-ca",
  VerifyFull: "verify-full",
} as const;
/**
 * SSL mode such as require, verify-ca, verify-full as applicable
 */
export type DboDatabaseSslOptionsSslMode = ClosedEnum<
  typeof DboDatabaseSslOptionsSslMode
>;

export type DboDatabaseSslOptions = {
  /**
   * SSL mode such as require, verify-ca, verify-full as applicable
   */
  sslMode?: DboDatabaseSslOptionsSslMode | undefined;
  /**
   * CA file path
   */
  sslCAPath?: string | undefined;
  /**
   * SSL key file path
   */
  sslKeyPath?: string | undefined;
  /**
   * SSL cert file path
   */
  sslCertPath?: string | undefined;
};

/** @internal */
export const DboDatabaseSslOptionsSslMode$inboundSchema: z.ZodNativeEnum<
  typeof DboDatabaseSslOptionsSslMode
> = z.nativeEnum(DboDatabaseSslOptionsSslMode);
/** @internal */
export const DboDatabaseSslOptionsSslMode$outboundSchema: z.ZodNativeEnum<
  typeof DboDatabaseSslOptionsSslMode
> = DboDatabaseSslOptionsSslMode$inboundSchema;

/** @internal */
export const DboDatabaseSslOptions$inboundSchema: z.ZodType<
  DboDatabaseSslOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  sslMode: DboDatabaseSslOptionsSslMode$inboundSchema.default("require"),
  sslCAPath: z.string().default(""),
  sslKeyPath: z.string().default(""),
  sslCertPath: z.string().default(""),
});
/** @internal */
export type DboDatabaseSslOptions$Outbound = {
  sslMode: string;
  sslCAPath: string;
  sslKeyPath: string;
  sslCertPath: string;
};

/** @internal */
export const DboDatabaseSslOptions$outboundSchema: z.ZodType<
  DboDatabaseSslOptions$Outbound,
  z.ZodTypeDef,
  DboDatabaseSslOptions
> = z.object({
  sslMode: DboDatabaseSslOptionsSslMode$outboundSchema.default("require"),
  sslCAPath: z.string().default(""),
  sslKeyPath: z.string().default(""),
  sslCertPath: z.string().default(""),
});

export function dboDatabaseSslOptionsToJSON(
  dboDatabaseSslOptions: DboDatabaseSslOptions,
): string {
  return JSON.stringify(
    DboDatabaseSslOptions$outboundSchema.parse(dboDatabaseSslOptions),
  );
}
export function dboDatabaseSslOptionsFromJSON(
  jsonString: string,
): SafeParseResult<DboDatabaseSslOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DboDatabaseSslOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DboDatabaseSslOptions' from JSON`,
  );
}
