/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DboDatabasePluginStatus = {
  /**
   * Name of plugin observing database server
   */
  pluginName: string;
  /**
   * Deployment Status of plugin observing database server
   */
  deploymentStatus: string;
  /**
   * Health Status of plugin observing database server
   */
  healthStatus: string;
};

/** @internal */
export const DboDatabasePluginStatus$inboundSchema: z.ZodType<
  DboDatabasePluginStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  pluginName: z.string(),
  deploymentStatus: z.string(),
  healthStatus: z.string(),
});
/** @internal */
export type DboDatabasePluginStatus$Outbound = {
  pluginName: string;
  deploymentStatus: string;
  healthStatus: string;
};

/** @internal */
export const DboDatabasePluginStatus$outboundSchema: z.ZodType<
  DboDatabasePluginStatus$Outbound,
  z.ZodTypeDef,
  DboDatabasePluginStatus
> = z.object({
  pluginName: z.string(),
  deploymentStatus: z.string(),
  healthStatus: z.string(),
});

export function dboDatabasePluginStatusToJSON(
  dboDatabasePluginStatus: DboDatabasePluginStatus,
): string {
  return JSON.stringify(
    DboDatabasePluginStatus$outboundSchema.parse(dboDatabasePluginStatus),
  );
}
export function dboDatabasePluginStatusFromJSON(
  jsonString: string,
): SafeParseResult<DboDatabasePluginStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DboDatabasePluginStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DboDatabasePluginStatus' from JSON`,
  );
}
