/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * SSL mode such as require, verify-ca, verify-full as applicable
 */
export const DboDatabaseSslOptionsUpdateSslMode = {
  Require: "require",
  VerifyCa: "verify-ca",
  VerifyFull: "verify-full",
} as const;
/**
 * SSL mode such as require, verify-ca, verify-full as applicable
 */
export type DboDatabaseSslOptionsUpdateSslMode = ClosedEnum<
  typeof DboDatabaseSslOptionsUpdateSslMode
>;

export type DboDatabaseSslOptionsUpdate = {
  /**
   * SSL mode such as require, verify-ca, verify-full as applicable
   */
  sslMode?: DboDatabaseSslOptionsUpdateSslMode | undefined;
  /**
   * CA file path
   */
  sslCAPath?: string | undefined;
  /**
   * SSL key file path
   */
  sslKeyPath?: string | undefined;
  /**
   * SSL cert file path
   */
  sslCertPath?: string | undefined;
};

/** @internal */
export const DboDatabaseSslOptionsUpdateSslMode$outboundSchema: z.ZodNativeEnum<
  typeof DboDatabaseSslOptionsUpdateSslMode
> = z.nativeEnum(DboDatabaseSslOptionsUpdateSslMode);

/** @internal */
export type DboDatabaseSslOptionsUpdate$Outbound = {
  sslMode: string;
  sslCAPath: string;
  sslKeyPath: string;
  sslCertPath: string;
};

/** @internal */
export const DboDatabaseSslOptionsUpdate$outboundSchema: z.ZodType<
  DboDatabaseSslOptionsUpdate$Outbound,
  z.ZodTypeDef,
  DboDatabaseSslOptionsUpdate
> = z.object({
  sslMode: DboDatabaseSslOptionsUpdateSslMode$outboundSchema.default("require"),
  sslCAPath: z.string().default(""),
  sslKeyPath: z.string().default(""),
  sslCertPath: z.string().default(""),
});

export function dboDatabaseSslOptionsUpdateToJSON(
  dboDatabaseSslOptionsUpdate: DboDatabaseSslOptionsUpdate,
): string {
  return JSON.stringify(
    DboDatabaseSslOptionsUpdate$outboundSchema.parse(
      dboDatabaseSslOptionsUpdate,
    ),
  );
}
