/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DemCustomHeaders = {
  /**
   * Name of a request header. Must contain only characters allowed by RFC: a-z, A-Z, 0-9, - and _.
   */
  name: string;
  /**
   * Value of a request header.
   */
  value: string;
};

/** @internal */
export const DemCustomHeaders$inboundSchema: z.ZodType<
  DemCustomHeaders,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  value: z.string(),
});

/** @internal */
export type DemCustomHeaders$Outbound = {
  name: string;
  value: string;
};

/** @internal */
export const DemCustomHeaders$outboundSchema: z.ZodType<
  DemCustomHeaders$Outbound,
  z.ZodTypeDef,
  DemCustomHeaders
> = z.object({
  name: z.string(),
  value: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DemCustomHeaders$ {
  /** @deprecated use `DemCustomHeaders$inboundSchema` instead. */
  export const inboundSchema = DemCustomHeaders$inboundSchema;
  /** @deprecated use `DemCustomHeaders$outboundSchema` instead. */
  export const outboundSchema = DemCustomHeaders$outboundSchema;
  /** @deprecated use `DemCustomHeaders$Outbound` instead. */
  export type Outbound = DemCustomHeaders$Outbound;
}

export function demCustomHeadersToJSON(
  demCustomHeaders: DemCustomHeaders,
): string {
  return JSON.stringify(
    DemCustomHeaders$outboundSchema.parse(demCustomHeaders),
  );
}

export function demCustomHeadersFromJSON(
  jsonString: string,
): SafeParseResult<DemCustomHeaders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DemCustomHeaders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemCustomHeaders' from JSON`,
  );
}
