/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DemProbe,
  DemProbe$inboundSchema,
  DemProbe$Outbound,
  DemProbe$outboundSchema,
} from "./demprobe.js";

export type DemListProbesResponse = {
  /**
   * Synthetic probes used to perform availability tests.
   */
  probes: Array<DemProbe>;
};

/** @internal */
export const DemListProbesResponse$inboundSchema: z.ZodType<
  DemListProbesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  probes: z.array(DemProbe$inboundSchema),
});
/** @internal */
export type DemListProbesResponse$Outbound = {
  probes: Array<DemProbe$Outbound>;
};

/** @internal */
export const DemListProbesResponse$outboundSchema: z.ZodType<
  DemListProbesResponse$Outbound,
  z.ZodTypeDef,
  DemListProbesResponse
> = z.object({
  probes: z.array(DemProbe$outboundSchema),
});

export function demListProbesResponseToJSON(
  demListProbesResponse: DemListProbesResponse,
): string {
  return JSON.stringify(
    DemListProbesResponse$outboundSchema.parse(demListProbesResponse),
  );
}
export function demListProbesResponseFromJSON(
  jsonString: string,
): SafeParseResult<DemListProbesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DemListProbesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemListProbesResponse' from JSON`,
  );
}
