/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DemOutageConfiguration,
  DemOutageConfiguration$inboundSchema,
} from "./demoutageconfiguration.js";

export type DemOrganizationSettings = {
  /**
   * Configure outage conditions for Website/URI entities.
   */
  availabilityOutageConfiguration: DemOutageConfiguration;
  /**
   * Configure outage conditions for Synthetic Transaction entities.
   */
  transactionOutageConfiguration: DemOutageConfiguration;
};

/** @internal */
export const DemOrganizationSettings$inboundSchema: z.ZodType<
  DemOrganizationSettings,
  z.ZodTypeDef,
  unknown
> = z.object({
  availabilityOutageConfiguration: DemOutageConfiguration$inboundSchema,
  transactionOutageConfiguration: DemOutageConfiguration$inboundSchema,
});

export function demOrganizationSettingsFromJSON(
  jsonString: string,
): SafeParseResult<DemOrganizationSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DemOrganizationSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemOrganizationSettings' from JSON`,
  );
}
