/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Status of the outage
 */
export const DemOutageStatusStatus = {
  Up: "up",
  Down: "down",
  Maintenance: "maintenance",
  Paused: "paused",
  Unknown: "unknown",
} as const;
/**
 * Status of the outage
 */
export type DemOutageStatusStatus = ClosedEnum<typeof DemOutageStatusStatus>;

export type DemOutageStatus = {
  /**
   * Timestamp of the start of the outage
   */
  startTime: Date;
  /**
   * Timestamp of the end of the outage
   */
  endTime: Date;
  /**
   * Status of the outage
   */
  status: DemOutageStatusStatus;
  /**
   * Reference to the result
   */
  resultId?: string | undefined;
  /**
   * Reference to the root cause analysis
   */
  analysisId?: string | undefined;
};

/** @internal */
export const DemOutageStatusStatus$inboundSchema: z.ZodNativeEnum<
  typeof DemOutageStatusStatus
> = z.nativeEnum(DemOutageStatusStatus);

/** @internal */
export const DemOutageStatus$inboundSchema: z.ZodType<
  DemOutageStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  startTime: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  endTime: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  status: DemOutageStatusStatus$inboundSchema,
  resultId: z.string().optional(),
  analysisId: z.string().optional(),
});

export function demOutageStatusFromJSON(
  jsonString: string,
): SafeParseResult<DemOutageStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DemOutageStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemOutageStatus' from JSON`,
  );
}
