/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Cloud platform hosting the probe.
 */
export const Platform = {
  Aws: "AWS",
  Azure: "AZURE",
  GoogleCloud: "GOOGLE_CLOUD",
} as const;
/**
 * Cloud platform hosting the probe.
 */
export type Platform = ClosedEnum<typeof Platform>;

/**
 * Coordinates of the probe.
 */
export type Coordinates = {
  /**
   * Latitude of the location.
   */
  latitude: number;
  /**
   * Longitude of the location.
   */
  longitude: number;
};

export type DemProbe = {
  /**
   * Unique identifier of the probe.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  id: string;
  /**
   * Name of the probe.
   */
  name: string;
  /**
   * True if the probe is active.
   */
  active: boolean;
  /**
   * Cloud platform hosting the probe.
   */
  platform: Platform;
  /**
   * Region where the probe is located.
   */
  region: string;
  /**
   * ISO 3166-1 alpha-2 code of the country where the probe is located.
   */
  country: string;
  /**
   * City where the probe is located.
   */
  city: string;
  /**
   * Coordinates of the probe.
   */
  coordinates: Coordinates;
  /**
   * IPv4 addresses of the probe.
   */
  ipv4Addresses: Array<string>;
  /**
   * IPv6 addresses of the probe. Not all probes support IPv6.
   */
  ipv6Addresses?: Array<string> | undefined;
};

/** @internal */
export const Platform$inboundSchema: z.ZodNativeEnum<typeof Platform> = z
  .nativeEnum(Platform);

/** @internal */
export const Coordinates$inboundSchema: z.ZodType<
  Coordinates,
  z.ZodTypeDef,
  unknown
> = z.object({
  latitude: z.number(),
  longitude: z.number(),
});

export function coordinatesFromJSON(
  jsonString: string,
): SafeParseResult<Coordinates, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Coordinates$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Coordinates' from JSON`,
  );
}

/** @internal */
export const DemProbe$inboundSchema: z.ZodType<
  DemProbe,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  active: z.boolean(),
  platform: Platform$inboundSchema,
  region: z.string(),
  country: z.string(),
  city: z.string(),
  coordinates: z.lazy(() => Coordinates$inboundSchema),
  ipv4Addresses: z.array(z.string()),
  ipv6Addresses: z.array(z.string()).optional(),
});

export function demProbeFromJSON(
  jsonString: string,
): SafeParseResult<DemProbe, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DemProbe$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemProbe' from JSON`,
  );
}
