/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DemTransactionCommandName,
  DemTransactionCommandName$inboundSchema,
  DemTransactionCommandName$outboundSchema,
} from "./demtransactioncommandname.js";

export type DemTransactionCommand = {
  /**
   * Name of the transaction command.
   */
  command: DemTransactionCommandName;
  /**
   * Target of the command, e.g. a URL to navigate to, or an element to interact with. All SIDE commands require a target, but some internal commands (e.g. "SWO_RESET") do not.
   */
  target?: string | undefined;
  /**
   * Human-readable representation of the target element. Usually derived from element's text content, alt attribute or id attribute. Must be omitted for commands that do not target elements ("OPEN", "PAUSE" etc.).
   */
  displayText?: string | undefined;
  /**
   * Value of the command, e.g. a text to type into a text field. Most commands do not require value.
   */
  value?: string | undefined;
};

/** @internal */
export const DemTransactionCommand$inboundSchema: z.ZodType<
  DemTransactionCommand,
  z.ZodTypeDef,
  unknown
> = z.object({
  command: DemTransactionCommandName$inboundSchema,
  target: z.string().optional(),
  displayText: z.string().optional(),
  value: z.string().optional(),
});
/** @internal */
export type DemTransactionCommand$Outbound = {
  command: string;
  target?: string | undefined;
  displayText?: string | undefined;
  value?: string | undefined;
};

/** @internal */
export const DemTransactionCommand$outboundSchema: z.ZodType<
  DemTransactionCommand$Outbound,
  z.ZodTypeDef,
  DemTransactionCommand
> = z.object({
  command: DemTransactionCommandName$outboundSchema,
  target: z.string().optional(),
  displayText: z.string().optional(),
  value: z.string().optional(),
});

export function demTransactionCommandToJSON(
  demTransactionCommand: DemTransactionCommand,
): string {
  return JSON.stringify(
    DemTransactionCommand$outboundSchema.parse(demTransactionCommand),
  );
}
export function demTransactionCommandFromJSON(
  jsonString: string,
): SafeParseResult<DemTransactionCommand, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DemTransactionCommand$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemTransactionCommand' from JSON`,
  );
}
