/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Geographic scope for selecting synthetic probe locations.
 */
export const DemTestFromType = {
  Region: "REGION",
  Country: "COUNTRY",
  City: "CITY",
} as const;
/**
 * Geographic scope for selecting synthetic probe locations.
 */
export type DemTestFromType = ClosedEnum<typeof DemTestFromType>;

export type DemTestFrom = {
  /**
   * Geographic scope for selecting synthetic probe locations.
   */
  type: DemTestFromType;
  /**
   * A list of probe location values of the selected type. At least one value matching an existing probe must be provided.
   */
  values: Array<string>;
};

/** @internal */
export const DemTestFromType$inboundSchema: z.ZodNativeEnum<
  typeof DemTestFromType
> = z.nativeEnum(DemTestFromType);
/** @internal */
export const DemTestFromType$outboundSchema: z.ZodNativeEnum<
  typeof DemTestFromType
> = DemTestFromType$inboundSchema;

/** @internal */
export const DemTestFrom$inboundSchema: z.ZodType<
  DemTestFrom,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: DemTestFromType$inboundSchema,
  values: z.array(z.string()),
});
/** @internal */
export type DemTestFrom$Outbound = {
  type: string;
  values: Array<string>;
};

/** @internal */
export const DemTestFrom$outboundSchema: z.ZodType<
  DemTestFrom$Outbound,
  z.ZodTypeDef,
  DemTestFrom
> = z.object({
  type: DemTestFromType$outboundSchema,
  values: z.array(z.string()),
});

export function demTestFromToJSON(demTestFrom: DemTestFrom): string {
  return JSON.stringify(DemTestFrom$outboundSchema.parse(demTestFrom));
}
export function demTestFromFromJSON(
  jsonString: string,
): SafeParseResult<DemTestFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DemTestFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemTestFrom' from JSON`,
  );
}
