/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const DemTransactionCommandName = {
  AssertChecked: "ASSERT_CHECKED",
  AssertElementNotPresent: "ASSERT_ELEMENT_NOT_PRESENT",
  AssertElementPresent: "ASSERT_ELEMENT_PRESENT",
  AssertNotChecked: "ASSERT_NOT_CHECKED",
  AssertNotSelectedValue: "ASSERT_NOT_SELECTED_VALUE",
  AssertNotText: "ASSERT_NOT_TEXT",
  AssertSelectedValue: "ASSERT_SELECTED_VALUE",
  AssertText: "ASSERT_TEXT",
  AssertValue: "ASSERT_VALUE",
  Check: "CHECK",
  Click: "CLICK",
  ClickAt: "CLICK_AT",
  Open: "OPEN",
  Pause: "PAUSE",
  SwoAssertTextContains: "SWO_ASSERT_TEXT_CONTAINS",
  SwoAssertTextNotContains: "SWO_ASSERT_TEXT_NOT_CONTAINS",
  SwoAssertValueContains: "SWO_ASSERT_VALUE_CONTAINS",
  SwoAssertValueNotContains: "SWO_ASSERT_VALUE_NOT_CONTAINS",
  Select: "SELECT",
  SelectFrame: "SELECT_FRAME",
  Submit: "SUBMIT",
  SwoAssertUrl: "SWO_ASSERT_URL",
  SwoWaitForElementTextContains: "SWO_WAIT_FOR_ELEMENT_TEXT_CONTAINS",
  Type: "TYPE",
  Uncheck: "UNCHECK",
  WaitForElementPresent: "WAIT_FOR_ELEMENT_PRESENT",
} as const;
export type DemTransactionCommandName = ClosedEnum<
  typeof DemTransactionCommandName
>;

/** @internal */
export const DemTransactionCommandName$inboundSchema: z.ZodNativeEnum<
  typeof DemTransactionCommandName
> = z.nativeEnum(DemTransactionCommandName);
/** @internal */
export const DemTransactionCommandName$outboundSchema: z.ZodNativeEnum<
  typeof DemTransactionCommandName
> = DemTransactionCommandName$inboundSchema;
