/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DemProbePlatform,
  DemProbePlatform$inboundSchema,
} from "./demprobeplatform.js";
import { DemTestFrom, DemTestFrom$inboundSchema } from "./demtestfrom.js";

/**
 * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, any available cloud platform may be chosen.
 */
export type DemUriAvailabilityCheckSettingsPlatformOptions = {
  /**
   * Cloud platforms hosting synthetic probes.
   */
  probePlatforms: Array<DemProbePlatform>;
  /**
   *   Use this field to configure whether availability tests should be performed from all selected
   *
   * @remarks
   *   platforms or one randomly selected platform. It has no effect if you provided only one platform
   *   in the `probePlatforms` field.
   *
   *   If set to true, a separate test is made from each of the selected platforms.
   *
   *   If set to false, only one of the selected platforms is chosen every time.
   *
   *   If omitted, the previous setting will stay in effect. If there is no previous setting, the value
   *   will default to false.
   */
  testFromAll?: boolean | undefined;
};

/**
 * How many locations must report a failure for an entity to be considered down.
 */
export const DemUriAvailabilityCheckSettingsFailingTestLocations = {
  All: "all",
  Any: "any",
} as const;
/**
 * How many locations must report a failure for an entity to be considered down.
 */
export type DemUriAvailabilityCheckSettingsFailingTestLocations = ClosedEnum<
  typeof DemUriAvailabilityCheckSettingsFailingTestLocations
>;

/**
 *   Default conditions when the entity is considered down.
 *
 * @remarks
 *   If omitted or set to null, organization configuration will be used for this entity.
 */
export type DemUriAvailabilityCheckSettingsOutageConfiguration = {
  /**
   * How many locations must report a failure for an entity to be considered down.
   */
  failingTestLocations: DemUriAvailabilityCheckSettingsFailingTestLocations;
  /**
   * Number of consecutive failing tests for an entity to be considered down.
   */
  consecutiveForDown: number;
};

/**
 * DNS tests configuration for the URI. If omitted or set to null, DNS tests are disabled.
 */
export type DemUriAvailabilityCheckSettingsDns = {
  /**
   * Enables or disables DNS tests for the URI.
   *
   * @remarks
   * Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
   */
  enabled: boolean;
  /**
   * Nameserver to be used for DNS queries. Can be an IP address or domain name.
   */
  nameserver: string;
  /**
   * Port number to be used for DNS queries.
   */
  port?: number | null | undefined;
  /**
   * Expected IP address in DNS response.
   */
  ipToExpect: string;
};

/**
 * Ping tests configuration for the URI. If omitted or set to null, ping tests are disabled.
 */
export type DemUriAvailabilityCheckSettingsPing = {
  /**
   * Enables or disables ping tests for the URI.
   *
   * @remarks
   * Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
   */
  enabled: boolean;
};

/**
 * TCP tests configuration for the URI. If omitted or set to null, TCP tests are disabled.
 */
export type DemUriAvailabilityCheckSettingsTcp = {
  /**
   * Enables or disables TCP tests for the URI.
   *
   * @remarks
   * Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
   */
  enabled: boolean;
  /**
   * Port number to be used in TCP tests.
   */
  port: number;
  /**
   * String to send in the body of a TCP request.
   */
  stringToSend?: string | null | undefined;
  /**
   * String to search for in the body of a TCP response.
   */
  stringToExpect?: string | null | undefined;
};

/**
 * UDP tests configuration for the URI. If omitted or set to null, UDP tests are disabled.
 */
export type DemUriAvailabilityCheckSettingsUdp = {
  /**
   * Enables or disables UDP tests for the URI.
   *
   * @remarks
   * Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
   */
  enabled: boolean;
  /**
   * Port number to be used in UDP tests.
   */
  port: number;
  /**
   * String to send in the body of a UDP request.
   */
  stringToSend: string;
  /**
   * String to search for in the body of a UDP response.
   */
  stringToExpect: string;
};

/**
 * Protocol used to test availability of the URI.
 */
export const Protocol = {
  Dns: "DNS",
  Ping: "PING",
  Tcp: "TCP",
  Udp: "UDP",
} as const;
/**
 * Protocol used to test availability of the URI.
 */
export type Protocol = ClosedEnum<typeof Protocol>;

export type DemUriAvailabilityCheckSettings = {
  /**
   * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, any available cloud platform may be chosen.
   */
  platformOptions?:
    | DemUriAvailabilityCheckSettingsPlatformOptions
    | null
    | undefined;
  /**
   *   Configure locations of the synthetic availability test probes.
   *
   * @remarks
   *   Acceptable values depend on the selected type and actual values of existing probes.
   */
  testFrom?: DemTestFrom | undefined;
  /**
   * Configure how often availability tests should be performed. Provide a number of seconds that is one of 60, 300, 600, 900, 1800, 3600, 7200, 14400.
   */
  testIntervalInSeconds: number;
  /**
   *   Default conditions when the entity is considered down.
   *
   * @remarks
   *   If omitted or set to null, organization configuration will be used for this entity.
   */
  outageConfiguration?:
    | DemUriAvailabilityCheckSettingsOutageConfiguration
    | null
    | undefined;
  /**
   * DNS tests configuration for the URI. If omitted or set to null, DNS tests are disabled.
   */
  dns?: DemUriAvailabilityCheckSettingsDns | null | undefined;
  /**
   * Ping tests configuration for the URI. If omitted or set to null, ping tests are disabled.
   */
  ping?: DemUriAvailabilityCheckSettingsPing | null | undefined;
  /**
   * TCP tests configuration for the URI. If omitted or set to null, TCP tests are disabled.
   */
  tcp?: DemUriAvailabilityCheckSettingsTcp | null | undefined;
  /**
   * UDP tests configuration for the URI. If omitted or set to null, UDP tests are disabled.
   */
  udp?: DemUriAvailabilityCheckSettingsUdp | null | undefined;
  /**
   * Protocol used to test availability of the URI.
   */
  protocol: Protocol;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsPlatformOptions$inboundSchema:
  z.ZodType<
    DemUriAvailabilityCheckSettingsPlatformOptions,
    z.ZodTypeDef,
    unknown
  > = z.object({
    probePlatforms: z.array(DemProbePlatform$inboundSchema),
    testFromAll: z.boolean().optional(),
  });

export function demUriAvailabilityCheckSettingsPlatformOptionsFromJSON(
  jsonString: string,
): SafeParseResult<
  DemUriAvailabilityCheckSettingsPlatformOptions,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsPlatformOptions$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DemUriAvailabilityCheckSettingsPlatformOptions' from JSON`,
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsFailingTestLocations$inboundSchema:
  z.ZodNativeEnum<typeof DemUriAvailabilityCheckSettingsFailingTestLocations> =
    z.nativeEnum(DemUriAvailabilityCheckSettingsFailingTestLocations);

/** @internal */
export const DemUriAvailabilityCheckSettingsOutageConfiguration$inboundSchema:
  z.ZodType<
    DemUriAvailabilityCheckSettingsOutageConfiguration,
    z.ZodTypeDef,
    unknown
  > = z.object({
    failingTestLocations:
      DemUriAvailabilityCheckSettingsFailingTestLocations$inboundSchema,
    consecutiveForDown: z.number().int(),
  });

export function demUriAvailabilityCheckSettingsOutageConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<
  DemUriAvailabilityCheckSettingsOutageConfiguration,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsOutageConfiguration$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DemUriAvailabilityCheckSettingsOutageConfiguration' from JSON`,
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsDns$inboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsDns,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean(),
  nameserver: z.string(),
  port: z.nullable(z.number().int()).optional(),
  ipToExpect: z.string(),
});

export function demUriAvailabilityCheckSettingsDnsFromJSON(
  jsonString: string,
): SafeParseResult<DemUriAvailabilityCheckSettingsDns, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsDns$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemUriAvailabilityCheckSettingsDns' from JSON`,
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsPing$inboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsPing,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean(),
});

export function demUriAvailabilityCheckSettingsPingFromJSON(
  jsonString: string,
): SafeParseResult<DemUriAvailabilityCheckSettingsPing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsPing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemUriAvailabilityCheckSettingsPing' from JSON`,
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsTcp$inboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsTcp,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean(),
  port: z.number().int(),
  stringToSend: z.nullable(z.string()).optional(),
  stringToExpect: z.nullable(z.string()).optional(),
});

export function demUriAvailabilityCheckSettingsTcpFromJSON(
  jsonString: string,
): SafeParseResult<DemUriAvailabilityCheckSettingsTcp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsTcp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemUriAvailabilityCheckSettingsTcp' from JSON`,
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsUdp$inboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsUdp,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean(),
  port: z.number().int(),
  stringToSend: z.string(),
  stringToExpect: z.string(),
});

export function demUriAvailabilityCheckSettingsUdpFromJSON(
  jsonString: string,
): SafeParseResult<DemUriAvailabilityCheckSettingsUdp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsUdp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemUriAvailabilityCheckSettingsUdp' from JSON`,
  );
}

/** @internal */
export const Protocol$inboundSchema: z.ZodNativeEnum<typeof Protocol> = z
  .nativeEnum(Protocol);

/** @internal */
export const DemUriAvailabilityCheckSettings$inboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettings,
  z.ZodTypeDef,
  unknown
> = z.object({
  platformOptions: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsPlatformOptions$inboundSchema),
  ).optional(),
  testFrom: DemTestFrom$inboundSchema.optional(),
  testIntervalInSeconds: z.number(),
  outageConfiguration: z.nullable(
    z.lazy(() =>
      DemUriAvailabilityCheckSettingsOutageConfiguration$inboundSchema
    ),
  ).optional(),
  dns: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsDns$inboundSchema),
  ).optional(),
  ping: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsPing$inboundSchema),
  ).optional(),
  tcp: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsTcp$inboundSchema),
  ).optional(),
  udp: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsUdp$inboundSchema),
  ).optional(),
  protocol: Protocol$inboundSchema,
});

export function demUriAvailabilityCheckSettingsFromJSON(
  jsonString: string,
): SafeParseResult<DemUriAvailabilityCheckSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DemUriAvailabilityCheckSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemUriAvailabilityCheckSettings' from JSON`,
  );
}
