/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import {
  DemProbePlatform,
  DemProbePlatform$outboundSchema,
} from "./demprobeplatform.js";
import {
  DemTestFrom,
  DemTestFrom$Outbound,
  DemTestFrom$outboundSchema,
} from "./demtestfrom.js";

/**
 * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, any available cloud platform may be chosen.
 */
export type DemUriAvailabilityCheckSettingsInputPlatformOptions = {
  /**
   * Cloud platforms hosting synthetic probes.
   */
  probePlatforms: Array<DemProbePlatform>;
  /**
   *   Use this field to configure whether availability tests should be performed from all selected
   *
   * @remarks
   *   platforms or one randomly selected platform. It has no effect if you provided only one platform
   *   in the `probePlatforms` field.
   *
   *   If set to true, a separate test is made from each of the selected platforms.
   *
   *   If set to false, only one of the selected platforms is chosen every time.
   *
   *   If omitted, the previous setting will stay in effect. If there is no previous setting, the value
   *   will default to false.
   */
  testFromAll?: boolean | undefined;
};

/**
 * How many locations must report a failure for an entity to be considered down.
 */
export const DemUriAvailabilityCheckSettingsInputFailingTestLocations = {
  All: "all",
  Any: "any",
} as const;
/**
 * How many locations must report a failure for an entity to be considered down.
 */
export type DemUriAvailabilityCheckSettingsInputFailingTestLocations =
  ClosedEnum<typeof DemUriAvailabilityCheckSettingsInputFailingTestLocations>;

/**
 *   Default conditions when the entity is considered down.
 *
 * @remarks
 *   If omitted or set to null, organization configuration will be used for this entity.
 */
export type DemUriAvailabilityCheckSettingsInputOutageConfiguration = {
  /**
   * How many locations must report a failure for an entity to be considered down.
   */
  failingTestLocations:
    DemUriAvailabilityCheckSettingsInputFailingTestLocations;
  /**
   * Number of consecutive failing tests for an entity to be considered down.
   */
  consecutiveForDown: number;
};

/**
 * DNS tests configuration for the URI. If omitted or set to null, DNS tests are disabled.
 */
export type DemUriAvailabilityCheckSettingsInputDns = {
  /**
   * Enables or disables DNS tests for the URI.
   *
   * @remarks
   * Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
   */
  enabled: boolean;
  /**
   * Nameserver to be used for DNS queries. Can be an IP address or domain name.
   */
  nameserver: string;
  /**
   * Port number to be used for DNS queries.
   */
  port?: number | null | undefined;
  /**
   * Expected IP address in DNS response.
   */
  ipToExpect: string;
};

/**
 * Ping tests configuration for the URI. If omitted or set to null, ping tests are disabled.
 */
export type DemUriAvailabilityCheckSettingsInputPing = {
  /**
   * Enables or disables ping tests for the URI.
   *
   * @remarks
   * Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
   */
  enabled: boolean;
};

/**
 * TCP tests configuration for the URI. If omitted or set to null, TCP tests are disabled.
 */
export type DemUriAvailabilityCheckSettingsInputTcp = {
  /**
   * Enables or disables TCP tests for the URI.
   *
   * @remarks
   * Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
   */
  enabled: boolean;
  /**
   * Port number to be used in TCP tests.
   */
  port: number;
  /**
   * String to send in the body of a TCP request.
   */
  stringToSend?: string | null | undefined;
  /**
   * String to search for in the body of a TCP response.
   */
  stringToExpect?: string | null | undefined;
};

/**
 * UDP tests configuration for the URI. If omitted or set to null, UDP tests are disabled.
 */
export type DemUriAvailabilityCheckSettingsInputUdp = {
  /**
   * Enables or disables UDP tests for the URI.
   *
   * @remarks
   * Exactly one test type (DNS, ping, TCP, or UDP) must be enabled for a URI.
   */
  enabled: boolean;
  /**
   * Port number to be used in UDP tests.
   */
  port: number;
  /**
   * String to send in the body of a UDP request.
   */
  stringToSend: string;
  /**
   * String to search for in the body of a UDP response.
   */
  stringToExpect: string;
};

export type DemUriAvailabilityCheckSettingsInput = {
  /**
   * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, any available cloud platform may be chosen.
   */
  platformOptions?:
    | DemUriAvailabilityCheckSettingsInputPlatformOptions
    | null
    | undefined;
  /**
   *   Configure locations of the synthetic availability test probes.
   *
   * @remarks
   *   Acceptable values depend on the selected type and actual values of existing probes.
   */
  testFrom?: DemTestFrom | undefined;
  /**
   * Configure how often availability tests should be performed. Provide a number of seconds that is one of 60, 300, 600, 900, 1800, 3600, 7200, 14400.
   */
  testIntervalInSeconds: number;
  /**
   *   Default conditions when the entity is considered down.
   *
   * @remarks
   *   If omitted or set to null, organization configuration will be used for this entity.
   */
  outageConfiguration?:
    | DemUriAvailabilityCheckSettingsInputOutageConfiguration
    | null
    | undefined;
  /**
   * DNS tests configuration for the URI. If omitted or set to null, DNS tests are disabled.
   */
  dns?: DemUriAvailabilityCheckSettingsInputDns | null | undefined;
  /**
   * Ping tests configuration for the URI. If omitted or set to null, ping tests are disabled.
   */
  ping?: DemUriAvailabilityCheckSettingsInputPing | null | undefined;
  /**
   * TCP tests configuration for the URI. If omitted or set to null, TCP tests are disabled.
   */
  tcp?: DemUriAvailabilityCheckSettingsInputTcp | null | undefined;
  /**
   * UDP tests configuration for the URI. If omitted or set to null, UDP tests are disabled.
   */
  udp?: DemUriAvailabilityCheckSettingsInputUdp | null | undefined;
};

/** @internal */
export type DemUriAvailabilityCheckSettingsInputPlatformOptions$Outbound = {
  probePlatforms: Array<string>;
  testFromAll?: boolean | undefined;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputPlatformOptions$outboundSchema:
  z.ZodType<
    DemUriAvailabilityCheckSettingsInputPlatformOptions$Outbound,
    z.ZodTypeDef,
    DemUriAvailabilityCheckSettingsInputPlatformOptions
  > = z.object({
    probePlatforms: z.array(DemProbePlatform$outboundSchema),
    testFromAll: z.boolean().optional(),
  });

export function demUriAvailabilityCheckSettingsInputPlatformOptionsToJSON(
  demUriAvailabilityCheckSettingsInputPlatformOptions:
    DemUriAvailabilityCheckSettingsInputPlatformOptions,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputPlatformOptions$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInputPlatformOptions,
    ),
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsInputFailingTestLocations$outboundSchema:
  z.ZodNativeEnum<
    typeof DemUriAvailabilityCheckSettingsInputFailingTestLocations
  > = z.nativeEnum(DemUriAvailabilityCheckSettingsInputFailingTestLocations);

/** @internal */
export type DemUriAvailabilityCheckSettingsInputOutageConfiguration$Outbound = {
  failingTestLocations: string;
  consecutiveForDown: number;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputOutageConfiguration$outboundSchema:
  z.ZodType<
    DemUriAvailabilityCheckSettingsInputOutageConfiguration$Outbound,
    z.ZodTypeDef,
    DemUriAvailabilityCheckSettingsInputOutageConfiguration
  > = z.object({
    failingTestLocations:
      DemUriAvailabilityCheckSettingsInputFailingTestLocations$outboundSchema,
    consecutiveForDown: z.number().int(),
  });

export function demUriAvailabilityCheckSettingsInputOutageConfigurationToJSON(
  demUriAvailabilityCheckSettingsInputOutageConfiguration:
    DemUriAvailabilityCheckSettingsInputOutageConfiguration,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputOutageConfiguration$outboundSchema
      .parse(demUriAvailabilityCheckSettingsInputOutageConfiguration),
  );
}

/** @internal */
export type DemUriAvailabilityCheckSettingsInputDns$Outbound = {
  enabled: boolean;
  nameserver: string;
  port?: number | null | undefined;
  ipToExpect: string;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputDns$outboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInputDns$Outbound,
  z.ZodTypeDef,
  DemUriAvailabilityCheckSettingsInputDns
> = z.object({
  enabled: z.boolean(),
  nameserver: z.string(),
  port: z.nullable(z.number().int()).optional(),
  ipToExpect: z.string(),
});

export function demUriAvailabilityCheckSettingsInputDnsToJSON(
  demUriAvailabilityCheckSettingsInputDns:
    DemUriAvailabilityCheckSettingsInputDns,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputDns$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInputDns,
    ),
  );
}

/** @internal */
export type DemUriAvailabilityCheckSettingsInputPing$Outbound = {
  enabled: boolean;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputPing$outboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInputPing$Outbound,
  z.ZodTypeDef,
  DemUriAvailabilityCheckSettingsInputPing
> = z.object({
  enabled: z.boolean(),
});

export function demUriAvailabilityCheckSettingsInputPingToJSON(
  demUriAvailabilityCheckSettingsInputPing:
    DemUriAvailabilityCheckSettingsInputPing,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputPing$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInputPing,
    ),
  );
}

/** @internal */
export type DemUriAvailabilityCheckSettingsInputTcp$Outbound = {
  enabled: boolean;
  port: number;
  stringToSend?: string | null | undefined;
  stringToExpect?: string | null | undefined;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputTcp$outboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInputTcp$Outbound,
  z.ZodTypeDef,
  DemUriAvailabilityCheckSettingsInputTcp
> = z.object({
  enabled: z.boolean(),
  port: z.number().int(),
  stringToSend: z.nullable(z.string()).optional(),
  stringToExpect: z.nullable(z.string()).optional(),
});

export function demUriAvailabilityCheckSettingsInputTcpToJSON(
  demUriAvailabilityCheckSettingsInputTcp:
    DemUriAvailabilityCheckSettingsInputTcp,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputTcp$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInputTcp,
    ),
  );
}

/** @internal */
export type DemUriAvailabilityCheckSettingsInputUdp$Outbound = {
  enabled: boolean;
  port: number;
  stringToSend: string;
  stringToExpect: string;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputUdp$outboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInputUdp$Outbound,
  z.ZodTypeDef,
  DemUriAvailabilityCheckSettingsInputUdp
> = z.object({
  enabled: z.boolean(),
  port: z.number().int(),
  stringToSend: z.string(),
  stringToExpect: z.string(),
});

export function demUriAvailabilityCheckSettingsInputUdpToJSON(
  demUriAvailabilityCheckSettingsInputUdp:
    DemUriAvailabilityCheckSettingsInputUdp,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputUdp$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInputUdp,
    ),
  );
}

/** @internal */
export type DemUriAvailabilityCheckSettingsInput$Outbound = {
  platformOptions?:
    | DemUriAvailabilityCheckSettingsInputPlatformOptions$Outbound
    | null
    | undefined;
  testFrom?: DemTestFrom$Outbound | undefined;
  testIntervalInSeconds: number;
  outageConfiguration?:
    | DemUriAvailabilityCheckSettingsInputOutageConfiguration$Outbound
    | null
    | undefined;
  dns?: DemUriAvailabilityCheckSettingsInputDns$Outbound | null | undefined;
  ping?: DemUriAvailabilityCheckSettingsInputPing$Outbound | null | undefined;
  tcp?: DemUriAvailabilityCheckSettingsInputTcp$Outbound | null | undefined;
  udp?: DemUriAvailabilityCheckSettingsInputUdp$Outbound | null | undefined;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInput$outboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInput$Outbound,
  z.ZodTypeDef,
  DemUriAvailabilityCheckSettingsInput
> = z.object({
  platformOptions: z.nullable(
    z.lazy(() =>
      DemUriAvailabilityCheckSettingsInputPlatformOptions$outboundSchema
    ),
  ).optional(),
  testFrom: DemTestFrom$outboundSchema.optional(),
  testIntervalInSeconds: z.number(),
  outageConfiguration: z.nullable(
    z.lazy(() =>
      DemUriAvailabilityCheckSettingsInputOutageConfiguration$outboundSchema
    ),
  ).optional(),
  dns: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsInputDns$outboundSchema),
  ).optional(),
  ping: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsInputPing$outboundSchema),
  ).optional(),
  tcp: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsInputTcp$outboundSchema),
  ).optional(),
  udp: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsInputUdp$outboundSchema),
  ).optional(),
});

export function demUriAvailabilityCheckSettingsInputToJSON(
  demUriAvailabilityCheckSettingsInput: DemUriAvailabilityCheckSettingsInput,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInput$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInput,
    ),
  );
}
