/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DemProbePlatform,
  DemProbePlatform$inboundSchema,
  DemProbePlatform$outboundSchema,
} from "./demprobeplatform.js";
import {
  DemTestFrom,
  DemTestFrom$inboundSchema,
  DemTestFrom$Outbound,
  DemTestFrom$outboundSchema,
} from "./demtestfrom.js";

/**
 * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, any available cloud platform may be chosen.
 */
export type DemUriAvailabilityCheckSettingsInputPlatformOptions = {
  /**
   * Cloud platforms hosting synthetic probes.
   */
  probePlatforms: Array<DemProbePlatform>;
  /**
   *   Use this field to configure whether availability tests should be performed from all selected
   *
   * @remarks
   *   platforms or one randomly selected platform. It has no effect if you provided only one platform
   *   in the `probePlatforms` field.
   *
   *   If set to true, a separate test is made from each of the selected platforms.
   *
   *   If set to false, only one of the selected platforms is chosen every time.
   *
   *   If omitted, the previous setting will stay in effect. If there is no previous setting, the value
   *   will default to false.
   */
  testFromAll?: boolean | undefined;
};

/**
 * How many locations must report a failure for an entity to be considered down.
 */
export const DemUriAvailabilityCheckSettingsInputFailingTestLocations = {
  All: "all",
  Any: "any",
} as const;
/**
 * How many locations must report a failure for an entity to be considered down.
 */
export type DemUriAvailabilityCheckSettingsInputFailingTestLocations =
  ClosedEnum<typeof DemUriAvailabilityCheckSettingsInputFailingTestLocations>;

/**
 *   Default conditions when the entity is considered down.
 *
 * @remarks
 *   If omitted or set to null, organization configuration will be used for this entity.
 */
export type DemUriAvailabilityCheckSettingsInputOutageConfiguration = {
  /**
   * How many locations must report a failure for an entity to be considered down.
   */
  failingTestLocations:
    DemUriAvailabilityCheckSettingsInputFailingTestLocations;
  /**
   * Number of consecutive failing tests for an entity to be considered down.
   */
  consecutiveForDown: number;
};

/**
 *   Use this field to configure ping tests for the URI. If omitted or set to null, ping tests will be disabled.
 *
 * @remarks
 *   One test type (ping or TCP) must be enabled for a URI.
 */
export type DemUriAvailabilityCheckSettingsInputPing = {
  /**
   * Use this field to configure ping tests for the URI. If omitted or set to false, ping tests will be disabled.
   *
   * @remarks
   * One test type (ping or TCP) must be enabled for a URI.
   */
  enabled: boolean;
};

/**
 *   Use this field to configure TCP tests for the URI. If omitted or set to null, TCP tests will be disabled.
 *
 * @remarks
 *   One test type (ping or TCP) must be enabled for a URI.
 */
export type DemUriAvailabilityCheckSettingsInputTcp = {
  /**
   * Use this field to configure TCP tests for the URI. If omitted or set to false, TCP tests will be disabled.
   *
   * @remarks
   * One test type (ping or TCP) must be enabled for a URI.
   */
  enabled: boolean;
  /**
   * Port number to be used in TCP tests.
   */
  port: number;
  /**
   * Use this field to specify a string to send in the body of a TCP request.
   */
  stringToSend?: string | null | undefined;
  /**
   * Use this field to specify a string to search for in the body of a TCP response.
   */
  stringToExpect?: string | null | undefined;
};

export type DemUriAvailabilityCheckSettingsInput = {
  /**
   * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, any available cloud platform may be chosen.
   */
  platformOptions?:
    | DemUriAvailabilityCheckSettingsInputPlatformOptions
    | null
    | undefined;
  /**
   *   Configure locations of the synthetic availability test probes.
   *
   * @remarks
   *   Acceptable values depend on the selected type and actual values of existing probes.
   */
  testFrom: DemTestFrom;
  /**
   * Configure how often availability tests should be performed. Provide a number of seconds that is one of 60, 300, 600, 900, 1800, 3600, 7200, 14400.
   */
  testIntervalInSeconds: number;
  /**
   *   Default conditions when the entity is considered down.
   *
   * @remarks
   *   If omitted or set to null, organization configuration will be used for this entity.
   */
  outageConfiguration?:
    | DemUriAvailabilityCheckSettingsInputOutageConfiguration
    | null
    | undefined;
  /**
   *   Use this field to configure ping tests for the URI. If omitted or set to null, ping tests will be disabled.
   *
   * @remarks
   *   One test type (ping or TCP) must be enabled for a URI.
   */
  ping?: DemUriAvailabilityCheckSettingsInputPing | null | undefined;
  /**
   *   Use this field to configure TCP tests for the URI. If omitted or set to null, TCP tests will be disabled.
   *
   * @remarks
   *   One test type (ping or TCP) must be enabled for a URI.
   */
  tcp?: DemUriAvailabilityCheckSettingsInputTcp | null | undefined;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputPlatformOptions$inboundSchema:
  z.ZodType<
    DemUriAvailabilityCheckSettingsInputPlatformOptions,
    z.ZodTypeDef,
    unknown
  > = z.object({
    probePlatforms: z.array(DemProbePlatform$inboundSchema),
    testFromAll: z.boolean().optional(),
  });

/** @internal */
export type DemUriAvailabilityCheckSettingsInputPlatformOptions$Outbound = {
  probePlatforms: Array<string>;
  testFromAll?: boolean | undefined;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputPlatformOptions$outboundSchema:
  z.ZodType<
    DemUriAvailabilityCheckSettingsInputPlatformOptions$Outbound,
    z.ZodTypeDef,
    DemUriAvailabilityCheckSettingsInputPlatformOptions
  > = z.object({
    probePlatforms: z.array(DemProbePlatform$outboundSchema),
    testFromAll: z.boolean().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DemUriAvailabilityCheckSettingsInputPlatformOptions$ {
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputPlatformOptions$inboundSchema` instead. */
  export const inboundSchema =
    DemUriAvailabilityCheckSettingsInputPlatformOptions$inboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputPlatformOptions$outboundSchema` instead. */
  export const outboundSchema =
    DemUriAvailabilityCheckSettingsInputPlatformOptions$outboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputPlatformOptions$Outbound` instead. */
  export type Outbound =
    DemUriAvailabilityCheckSettingsInputPlatformOptions$Outbound;
}

export function demUriAvailabilityCheckSettingsInputPlatformOptionsToJSON(
  demUriAvailabilityCheckSettingsInputPlatformOptions:
    DemUriAvailabilityCheckSettingsInputPlatformOptions,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputPlatformOptions$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInputPlatformOptions,
    ),
  );
}

export function demUriAvailabilityCheckSettingsInputPlatformOptionsFromJSON(
  jsonString: string,
): SafeParseResult<
  DemUriAvailabilityCheckSettingsInputPlatformOptions,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsInputPlatformOptions$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DemUriAvailabilityCheckSettingsInputPlatformOptions' from JSON`,
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsInputFailingTestLocations$inboundSchema:
  z.ZodNativeEnum<
    typeof DemUriAvailabilityCheckSettingsInputFailingTestLocations
  > = z.nativeEnum(DemUriAvailabilityCheckSettingsInputFailingTestLocations);

/** @internal */
export const DemUriAvailabilityCheckSettingsInputFailingTestLocations$outboundSchema:
  z.ZodNativeEnum<
    typeof DemUriAvailabilityCheckSettingsInputFailingTestLocations
  > = DemUriAvailabilityCheckSettingsInputFailingTestLocations$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DemUriAvailabilityCheckSettingsInputFailingTestLocations$ {
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputFailingTestLocations$inboundSchema` instead. */
  export const inboundSchema =
    DemUriAvailabilityCheckSettingsInputFailingTestLocations$inboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputFailingTestLocations$outboundSchema` instead. */
  export const outboundSchema =
    DemUriAvailabilityCheckSettingsInputFailingTestLocations$outboundSchema;
}

/** @internal */
export const DemUriAvailabilityCheckSettingsInputOutageConfiguration$inboundSchema:
  z.ZodType<
    DemUriAvailabilityCheckSettingsInputOutageConfiguration,
    z.ZodTypeDef,
    unknown
  > = z.object({
    failingTestLocations:
      DemUriAvailabilityCheckSettingsInputFailingTestLocations$inboundSchema,
    consecutiveForDown: z.number().int(),
  });

/** @internal */
export type DemUriAvailabilityCheckSettingsInputOutageConfiguration$Outbound = {
  failingTestLocations: string;
  consecutiveForDown: number;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputOutageConfiguration$outboundSchema:
  z.ZodType<
    DemUriAvailabilityCheckSettingsInputOutageConfiguration$Outbound,
    z.ZodTypeDef,
    DemUriAvailabilityCheckSettingsInputOutageConfiguration
  > = z.object({
    failingTestLocations:
      DemUriAvailabilityCheckSettingsInputFailingTestLocations$outboundSchema,
    consecutiveForDown: z.number().int(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DemUriAvailabilityCheckSettingsInputOutageConfiguration$ {
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputOutageConfiguration$inboundSchema` instead. */
  export const inboundSchema =
    DemUriAvailabilityCheckSettingsInputOutageConfiguration$inboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputOutageConfiguration$outboundSchema` instead. */
  export const outboundSchema =
    DemUriAvailabilityCheckSettingsInputOutageConfiguration$outboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputOutageConfiguration$Outbound` instead. */
  export type Outbound =
    DemUriAvailabilityCheckSettingsInputOutageConfiguration$Outbound;
}

export function demUriAvailabilityCheckSettingsInputOutageConfigurationToJSON(
  demUriAvailabilityCheckSettingsInputOutageConfiguration:
    DemUriAvailabilityCheckSettingsInputOutageConfiguration,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputOutageConfiguration$outboundSchema
      .parse(demUriAvailabilityCheckSettingsInputOutageConfiguration),
  );
}

export function demUriAvailabilityCheckSettingsInputOutageConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<
  DemUriAvailabilityCheckSettingsInputOutageConfiguration,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsInputOutageConfiguration$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DemUriAvailabilityCheckSettingsInputOutageConfiguration' from JSON`,
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsInputPing$inboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInputPing,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean(),
});

/** @internal */
export type DemUriAvailabilityCheckSettingsInputPing$Outbound = {
  enabled: boolean;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputPing$outboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInputPing$Outbound,
  z.ZodTypeDef,
  DemUriAvailabilityCheckSettingsInputPing
> = z.object({
  enabled: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DemUriAvailabilityCheckSettingsInputPing$ {
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputPing$inboundSchema` instead. */
  export const inboundSchema =
    DemUriAvailabilityCheckSettingsInputPing$inboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputPing$outboundSchema` instead. */
  export const outboundSchema =
    DemUriAvailabilityCheckSettingsInputPing$outboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputPing$Outbound` instead. */
  export type Outbound = DemUriAvailabilityCheckSettingsInputPing$Outbound;
}

export function demUriAvailabilityCheckSettingsInputPingToJSON(
  demUriAvailabilityCheckSettingsInputPing:
    DemUriAvailabilityCheckSettingsInputPing,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputPing$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInputPing,
    ),
  );
}

export function demUriAvailabilityCheckSettingsInputPingFromJSON(
  jsonString: string,
): SafeParseResult<
  DemUriAvailabilityCheckSettingsInputPing,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsInputPing$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DemUriAvailabilityCheckSettingsInputPing' from JSON`,
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsInputTcp$inboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInputTcp,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean(),
  port: z.number().int(),
  stringToSend: z.nullable(z.string()).optional(),
  stringToExpect: z.nullable(z.string()).optional(),
});

/** @internal */
export type DemUriAvailabilityCheckSettingsInputTcp$Outbound = {
  enabled: boolean;
  port: number;
  stringToSend?: string | null | undefined;
  stringToExpect?: string | null | undefined;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInputTcp$outboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInputTcp$Outbound,
  z.ZodTypeDef,
  DemUriAvailabilityCheckSettingsInputTcp
> = z.object({
  enabled: z.boolean(),
  port: z.number().int(),
  stringToSend: z.nullable(z.string()).optional(),
  stringToExpect: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DemUriAvailabilityCheckSettingsInputTcp$ {
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputTcp$inboundSchema` instead. */
  export const inboundSchema =
    DemUriAvailabilityCheckSettingsInputTcp$inboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputTcp$outboundSchema` instead. */
  export const outboundSchema =
    DemUriAvailabilityCheckSettingsInputTcp$outboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInputTcp$Outbound` instead. */
  export type Outbound = DemUriAvailabilityCheckSettingsInputTcp$Outbound;
}

export function demUriAvailabilityCheckSettingsInputTcpToJSON(
  demUriAvailabilityCheckSettingsInputTcp:
    DemUriAvailabilityCheckSettingsInputTcp,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInputTcp$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInputTcp,
    ),
  );
}

export function demUriAvailabilityCheckSettingsInputTcpFromJSON(
  jsonString: string,
): SafeParseResult<
  DemUriAvailabilityCheckSettingsInputTcp,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsInputTcp$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DemUriAvailabilityCheckSettingsInputTcp' from JSON`,
  );
}

/** @internal */
export const DemUriAvailabilityCheckSettingsInput$inboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  platformOptions: z.nullable(
    z.lazy(() =>
      DemUriAvailabilityCheckSettingsInputPlatformOptions$inboundSchema
    ),
  ).optional(),
  testFrom: DemTestFrom$inboundSchema,
  testIntervalInSeconds: z.number(),
  outageConfiguration: z.nullable(
    z.lazy(() =>
      DemUriAvailabilityCheckSettingsInputOutageConfiguration$inboundSchema
    ),
  ).optional(),
  ping: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsInputPing$inboundSchema),
  ).optional(),
  tcp: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsInputTcp$inboundSchema),
  ).optional(),
});

/** @internal */
export type DemUriAvailabilityCheckSettingsInput$Outbound = {
  platformOptions?:
    | DemUriAvailabilityCheckSettingsInputPlatformOptions$Outbound
    | null
    | undefined;
  testFrom: DemTestFrom$Outbound;
  testIntervalInSeconds: number;
  outageConfiguration?:
    | DemUriAvailabilityCheckSettingsInputOutageConfiguration$Outbound
    | null
    | undefined;
  ping?: DemUriAvailabilityCheckSettingsInputPing$Outbound | null | undefined;
  tcp?: DemUriAvailabilityCheckSettingsInputTcp$Outbound | null | undefined;
};

/** @internal */
export const DemUriAvailabilityCheckSettingsInput$outboundSchema: z.ZodType<
  DemUriAvailabilityCheckSettingsInput$Outbound,
  z.ZodTypeDef,
  DemUriAvailabilityCheckSettingsInput
> = z.object({
  platformOptions: z.nullable(
    z.lazy(() =>
      DemUriAvailabilityCheckSettingsInputPlatformOptions$outboundSchema
    ),
  ).optional(),
  testFrom: DemTestFrom$outboundSchema,
  testIntervalInSeconds: z.number(),
  outageConfiguration: z.nullable(
    z.lazy(() =>
      DemUriAvailabilityCheckSettingsInputOutageConfiguration$outboundSchema
    ),
  ).optional(),
  ping: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsInputPing$outboundSchema),
  ).optional(),
  tcp: z.nullable(
    z.lazy(() => DemUriAvailabilityCheckSettingsInputTcp$outboundSchema),
  ).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DemUriAvailabilityCheckSettingsInput$ {
  /** @deprecated use `DemUriAvailabilityCheckSettingsInput$inboundSchema` instead. */
  export const inboundSchema =
    DemUriAvailabilityCheckSettingsInput$inboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInput$outboundSchema` instead. */
  export const outboundSchema =
    DemUriAvailabilityCheckSettingsInput$outboundSchema;
  /** @deprecated use `DemUriAvailabilityCheckSettingsInput$Outbound` instead. */
  export type Outbound = DemUriAvailabilityCheckSettingsInput$Outbound;
}

export function demUriAvailabilityCheckSettingsInputToJSON(
  demUriAvailabilityCheckSettingsInput: DemUriAvailabilityCheckSettingsInput,
): string {
  return JSON.stringify(
    DemUriAvailabilityCheckSettingsInput$outboundSchema.parse(
      demUriAvailabilityCheckSettingsInput,
    ),
  );
}

export function demUriAvailabilityCheckSettingsInputFromJSON(
  jsonString: string,
): SafeParseResult<DemUriAvailabilityCheckSettingsInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DemUriAvailabilityCheckSettingsInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DemUriAvailabilityCheckSettingsInput' from JSON`,
  );
}
