/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Protocol to perform availability checks for.
 */
export const DemWebsiteProtocol = {
  Http: "HTTP",
  Https: "HTTPS",
} as const;
/**
 * Protocol to perform availability checks for.
 */
export type DemWebsiteProtocol = ClosedEnum<typeof DemWebsiteProtocol>;

/** @internal */
export const DemWebsiteProtocol$inboundSchema: z.ZodNativeEnum<
  typeof DemWebsiteProtocol
> = z.nativeEnum(DemWebsiteProtocol);

/** @internal */
export const DemWebsiteProtocol$outboundSchema: z.ZodNativeEnum<
  typeof DemWebsiteProtocol
> = DemWebsiteProtocol$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DemWebsiteProtocol$ {
  /** @deprecated use `DemWebsiteProtocol$inboundSchema` instead. */
  export const inboundSchema = DemWebsiteProtocol$inboundSchema;
  /** @deprecated use `DemWebsiteProtocol$outboundSchema` instead. */
  export const outboundSchema = DemWebsiteProtocol$outboundSchema;
}
