/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Health Score category label.
 */
export const Category = {
  Good: "good",
  Bad: "bad",
  Moderate: "moderate",
} as const;
/**
 * Health Score category label.
 */
export type Category = ClosedEnum<typeof Category>;

export type Healthscore = {
  /**
   * Health score value from 0 to 100.
   */
  score?: number | undefined;
  /**
   * Health Score category label.
   */
  category?: Category | undefined;
};

export type EntitiesEntity = {
  /**
   * The ID of the entity.
   */
  id: string;
  /**
   * The type of the entity.
   */
  type: string;
  /**
   * The name of the entity.
   */
  name?: string | undefined;
  /**
   * Entity display name / alias. This value is equal to name unless it is explicitly overridden.
   */
  displayName?: string | null | undefined;
  /**
   * Date and time of entity creation in UTC.
   */
  createdTime?: Date | undefined;
  /**
   * Date and time of last entity update in UTC.
   */
  updatedTime?: Date | undefined;
  /**
   * Date and time when the entity has last received telemetry in UTC.
   */
  lastSeenTime: Date;
  /**
   * Flag telling if given entity is in maintenance mode.
   */
  inMaintenance: boolean;
  healthscore?: Healthscore | undefined;
  /**
   * Entity tags. Tag is a key-value pair, where there may be only a single tag value for the same key.
   */
  tags: { [k: string]: string | null };
  /**
   * Map of available attributes.
   */
  attributes?: { [k: string]: any } | undefined;
};

/** @internal */
export const Category$inboundSchema: z.ZodNativeEnum<typeof Category> = z
  .nativeEnum(Category);
/** @internal */
export const Category$outboundSchema: z.ZodNativeEnum<typeof Category> =
  Category$inboundSchema;

/** @internal */
export const Healthscore$inboundSchema: z.ZodType<
  Healthscore,
  z.ZodTypeDef,
  unknown
> = z.object({
  score: z.number().int().optional(),
  category: Category$inboundSchema.optional(),
});
/** @internal */
export type Healthscore$Outbound = {
  score?: number | undefined;
  category?: string | undefined;
};

/** @internal */
export const Healthscore$outboundSchema: z.ZodType<
  Healthscore$Outbound,
  z.ZodTypeDef,
  Healthscore
> = z.object({
  score: z.number().int().optional(),
  category: Category$outboundSchema.optional(),
});

export function healthscoreToJSON(healthscore: Healthscore): string {
  return JSON.stringify(Healthscore$outboundSchema.parse(healthscore));
}
export function healthscoreFromJSON(
  jsonString: string,
): SafeParseResult<Healthscore, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Healthscore$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Healthscore' from JSON`,
  );
}

/** @internal */
export const EntitiesEntity$inboundSchema: z.ZodType<
  EntitiesEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.string(),
  name: z.string().optional(),
  displayName: z.nullable(z.string()).optional(),
  createdTime: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updatedTime: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  lastSeenTime: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  inMaintenance: z.boolean(),
  healthscore: z.lazy(() => Healthscore$inboundSchema).optional(),
  tags: z.record(z.nullable(z.string())),
  attributes: z.record(z.any()).optional(),
});
/** @internal */
export type EntitiesEntity$Outbound = {
  id: string;
  type: string;
  name?: string | undefined;
  displayName?: string | null | undefined;
  createdTime?: string | undefined;
  updatedTime?: string | undefined;
  lastSeenTime: string;
  inMaintenance: boolean;
  healthscore?: Healthscore$Outbound | undefined;
  tags: { [k: string]: string | null };
  attributes?: { [k: string]: any } | undefined;
};

/** @internal */
export const EntitiesEntity$outboundSchema: z.ZodType<
  EntitiesEntity$Outbound,
  z.ZodTypeDef,
  EntitiesEntity
> = z.object({
  id: z.string(),
  type: z.string(),
  name: z.string().optional(),
  displayName: z.nullable(z.string()).optional(),
  createdTime: z.date().transform(v => v.toISOString()).optional(),
  updatedTime: z.date().transform(v => v.toISOString()).optional(),
  lastSeenTime: z.date().transform(v => v.toISOString()),
  inMaintenance: z.boolean(),
  healthscore: z.lazy(() => Healthscore$outboundSchema).optional(),
  tags: z.record(z.nullable(z.string())),
  attributes: z.record(z.any()).optional(),
});

export function entitiesEntityToJSON(entitiesEntity: EntitiesEntity): string {
  return JSON.stringify(EntitiesEntity$outboundSchema.parse(entitiesEntity));
}
export function entitiesEntityFromJSON(
  jsonString: string,
): SafeParseResult<EntitiesEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EntitiesEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EntitiesEntity' from JSON`,
  );
}
