/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomHeaders,
  CustomHeaders$inboundSchema,
  CustomHeaders$Outbound,
  CustomHeaders$outboundSchema,
} from "./customheaders.js";
import {
  ProbePlatform,
  ProbePlatform$inboundSchema,
  ProbePlatform$outboundSchema,
} from "./probeplatform.js";
import {
  Tag,
  Tag$inboundSchema,
  Tag$Outbound,
  Tag$outboundSchema,
} from "./tag.js";
import {
  TestFrom,
  TestFrom$inboundSchema,
  TestFrom$Outbound,
  TestFrom$outboundSchema,
} from "./testfrom.js";
import {
  WebsiteProtocol,
  WebsiteProtocol$inboundSchema,
  WebsiteProtocol$outboundSchema,
} from "./websiteprotocol.js";

export const GetWebsiteResponseStatus = {
  Up: "up",
  Down: "down",
  Paused: "paused",
  Maintenance: "maintenance",
  Unknown: "unknown",
} as const;
export type GetWebsiteResponseStatus = ClosedEnum<
  typeof GetWebsiteResponseStatus
>;

/**
 * Defines which monitoring features are enabled for a website.
 */
export type MonitoringOptions = {
  /**
   * True if the availability monitoring is active.
   */
  isAvailabilityActive: boolean;
  /**
   * True if the real user monitoring (RUM) is active.
   */
  isRumActive: boolean;
};

/**
 * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, no particular cloud platform will be enforced.
 */
export type GetWebsiteResponsePlatformOptions = {
  /**
   * Cloud platforms hosting synthetic probes.
   */
  probePlatforms: Array<ProbePlatform>;
  /**
   *   Use this field to configure whether availability tests should be performed from all selected
   *
   * @remarks
   *   platforms or one randomly selected platform. It has no effect if you provided only one platform
   *   in the `probePlatforms` field.
   *
   *   If set to true, a separate test is made from each of the selected platforms.
   *
   *   If set to false, only one of the selected platforms is chosen every time.
   *
   *   If omitted, the previous setting will stay in effect. If there is no previous setting, the value
   *   will default to false.
   */
  testFromAll?: boolean | undefined;
};

/**
 * How many locations must report a failure for an entity to be considered down.
 */
export const GetWebsiteResponseFailingTestLocations = {
  All: "all",
  Any: "any",
} as const;
/**
 * How many locations must report a failure for an entity to be considered down.
 */
export type GetWebsiteResponseFailingTestLocations = ClosedEnum<
  typeof GetWebsiteResponseFailingTestLocations
>;

/**
 *   Default conditions when the entity is considered down.
 *
 * @remarks
 *   If omitted or set to null, organization configuration will be used for this entity.
 */
export type GetWebsiteResponseOutageConfiguration = {
  /**
   * How many locations must report a failure for an entity to be considered down.
   */
  failingTestLocations: GetWebsiteResponseFailingTestLocations;
  /**
   * Number of consecutive failing tests for an entity to be considered down.
   */
  consecutiveForDown: number;
};

/**
 * Defines whether the check should pass only when the string is present on the page (CONTAINS) or only when it is absent (DOES_NOT_CONTAIN).
 */
export const GetWebsiteResponseOperator = {
  Contains: "CONTAINS",
  DoesNotContain: "DOES_NOT_CONTAIN",
} as const;
/**
 * Defines whether the check should pass only when the string is present on the page (CONTAINS) or only when it is absent (DOES_NOT_CONTAIN).
 */
export type GetWebsiteResponseOperator = ClosedEnum<
  typeof GetWebsiteResponseOperator
>;

/**
 *   Use this field to configure whether availability tests should check for presence or absence of a particular string on a page.
 *
 * @remarks
 *   If the operator is DOES_NOT_CONTAIN and the value is found on the page, the availability test will fail.
 *   Likewise, if the operator is CONTAINS and the value is not found on the page, the availability test will fail.
 *   If omitted or set to null, the string checking functionality will be disabled.
 */
export type GetWebsiteResponseCheckForString = {
  /**
   * Defines whether the check should pass only when the string is present on the page (CONTAINS) or only when it is absent (DOES_NOT_CONTAIN).
   */
  operator: GetWebsiteResponseOperator;
  /**
   * The string that which will be searched in the page source code.
   */
  value: string;
};

/**
 *   Configure monitoring of SSL/TLS certificates validity. This option is relevant for HTTPS protocol only.
 *
 * @remarks
 *   If omitted or set to null, SSL monitoring will be disabled and its previous configuration discarded.
 */
export type GetWebsiteResponseSsl = {
  /**
   *   Whether SSL monitoring is enabled for the website.
   *
   * @remarks
   *   If set to false, SSL monitoring will be disabled, but the other settings will be remembered in case you re-enable it later.
   *   If omitted, the previous setting will stay in effect. If there is no previous setting, the value will default to false.
   */
  enabled?: boolean | null | undefined;
  /**
   * Number of days before the expiration date an SSL certificate will be considered 'expiring.'
   */
  daysPriorToExpiration?: number | null | undefined;
  /**
   *   Use this option to limit the certificate expiration check to only the first certificate in the chain (normally the host certificate).
   *
   * @remarks
   *   This way you will not be warned about impending expiration of intermediate or root Certification Authority certificates in the chain.
   *   This option does not affect any other certificate validity checks besides expiration.
   *   If omitted, the previous setting will stay in effect. If there is no previous setting, the value will default to false.
   */
  ignoreIntermediateCertificates?: boolean | null | undefined;
};

/**
 *   Use this field to configure availability tests for the website.
 *
 * @remarks
 *   You are required to configure at least availability monitoring or real user monitoring to be able to create website.
 */
export type GetWebsiteResponseAvailabilityCheckSettings = {
  /**
   * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, no particular cloud platform will be enforced.
   */
  platformOptions?: GetWebsiteResponsePlatformOptions | null | undefined;
  /**
   *   Configure locations of the synthetic availability test probes.
   *
   * @remarks
   *   Acceptable values depend on the selected type and actual values of existing probes.
   */
  testFrom: TestFrom;
  /**
   * Configure how often availability tests should be performed. Provide a number of seconds that is one of 60, 300, 600, 900, 1800, 3600, 7200, 14400.
   */
  testIntervalInSeconds: number;
  /**
   *   Default conditions when the entity is considered down.
   *
   * @remarks
   *   If omitted or set to null, organization configuration will be used for this entity.
   */
  outageConfiguration?:
    | GetWebsiteResponseOutageConfiguration
    | null
    | undefined;
  /**
   *   Use this field to configure whether availability tests should check for presence or absence of a particular string on a page.
   *
   * @remarks
   *   If the operator is DOES_NOT_CONTAIN and the value is found on the page, the availability test will fail.
   *   Likewise, if the operator is CONTAINS and the value is not found on the page, the availability test will fail.
   *   If omitted or set to null, the string checking functionality will be disabled.
   */
  checkForString?: GetWebsiteResponseCheckForString | null | undefined;
  /**
   * Configure which protocols need availability tests to be performed. At least one protocol must be provided.
   */
  protocols: Array<WebsiteProtocol>;
  /**
   *   Configure monitoring of SSL/TLS certificates validity. This option is relevant for HTTPS protocol only.
   *
   * @remarks
   *   If omitted or set to null, SSL monitoring will be disabled and its previous configuration discarded.
   */
  ssl?: GetWebsiteResponseSsl | null | undefined;
  /**
   *   Configure custom request headers to be sent with each availability test. It is possible to provide multiple headers with the same name.
   *
   * @remarks
   *   If omitted, set to null or set to an empty array, no custom headers will be sent.
   */
  customHeaders?: Array<CustomHeaders> | null | undefined;
  /**
   *   Allow insecure SSL renegotiation which introduces a security risk in the communication process.
   *
   * @remarks
   *   Checking this option could lead to exposing credentials to unauthorized entities and the possibility of unauthorized access, interception, or manipulation of sensitive data, compromising the integrity and security of the communication channel.
   *   Available only with HTTPS check.
   *   If omitted or set to null, insecure SSL renegotiation won't be allowed.
   */
  allowInsecureRenegotiation?: boolean | undefined;
  /**
   *   Configure data that will be sent as POST request body by the synthetic probe.
   *
   * @remarks
   *   If omitted or set to null/empty string, the probe will send the usual GET requests.
   */
  postData?: string | null | undefined;
};

/**
 * Use this field to configure real user monitoring (RUM) for the website.
 *
 * @remarks
 * You are required to configure at least availability monitoring or real user monitoring to be able to create website.
 */
export type GetWebsiteResponseRum = {
  apdexTimeInSeconds?: number | undefined;
  snippet?: string | undefined;
  spa: boolean;
};

export type GetWebsiteResponse = {
  id: string;
  type: string;
  status: GetWebsiteResponseStatus;
  /**
   *   Name of the website, which must be unique within the organization.
   *
   * @remarks
   *   The website must also not contain any control characters, any white space other than space (U+0020), or any consecutive, leading or trailing spaces.
   */
  name: string;
  /**
   * URL of the website. Must be a valid URL with no leading or trailing white space. Must not contain invalid port number (>65535).
   */
  url: string;
  /**
   * Defines which monitoring features are enabled for a website.
   */
  monitoringOptions: MonitoringOptions;
  /**
   *   Use this field to configure availability tests for the website.
   *
   * @remarks
   *   You are required to configure at least availability monitoring or real user monitoring to be able to create website.
   */
  availabilityCheckSettings?:
    | GetWebsiteResponseAvailabilityCheckSettings
    | null
    | undefined;
  /**
   * Entity tags. Tag is a key-value pair, where there may be only single tag value for the same key.
   */
  tags?: Array<Tag> | undefined;
  /**
   * Use this field to configure real user monitoring (RUM) for the website.
   *
   * @remarks
   * You are required to configure at least availability monitoring or real user monitoring to be able to create website.
   */
  rum?: GetWebsiteResponseRum | undefined;
  /**
   * Time when the last outage started.
   */
  lastOutageStartTime?: Date | null | undefined;
  /**
   * Time when the last outage ended.
   */
  lastOutageEndTime?: Date | null | undefined;
  /**
   * Time when the last test was performed.
   */
  lastTestTime?: Date | null | undefined;
  /**
   * Last time when a synthetic test failed.
   */
  lastErrorTime?: Date | null | undefined;
  /**
   * Response time from the last synthetic check in milliseconds.
   */
  lastResponseTime?: number | null | undefined;
  /**
   * Timestamp for when the next on-demand check could be executed. If at '0', it means you can execute it anytime.
   */
  nextOnDemandAvailabilityTime?: number | undefined;
};

/** @internal */
export const GetWebsiteResponseStatus$inboundSchema: z.ZodNativeEnum<
  typeof GetWebsiteResponseStatus
> = z.nativeEnum(GetWebsiteResponseStatus);

/** @internal */
export const GetWebsiteResponseStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetWebsiteResponseStatus
> = GetWebsiteResponseStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponseStatus$ {
  /** @deprecated use `GetWebsiteResponseStatus$inboundSchema` instead. */
  export const inboundSchema = GetWebsiteResponseStatus$inboundSchema;
  /** @deprecated use `GetWebsiteResponseStatus$outboundSchema` instead. */
  export const outboundSchema = GetWebsiteResponseStatus$outboundSchema;
}

/** @internal */
export const MonitoringOptions$inboundSchema: z.ZodType<
  MonitoringOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  isAvailabilityActive: z.boolean(),
  isRumActive: z.boolean(),
});

/** @internal */
export type MonitoringOptions$Outbound = {
  isAvailabilityActive: boolean;
  isRumActive: boolean;
};

/** @internal */
export const MonitoringOptions$outboundSchema: z.ZodType<
  MonitoringOptions$Outbound,
  z.ZodTypeDef,
  MonitoringOptions
> = z.object({
  isAvailabilityActive: z.boolean(),
  isRumActive: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MonitoringOptions$ {
  /** @deprecated use `MonitoringOptions$inboundSchema` instead. */
  export const inboundSchema = MonitoringOptions$inboundSchema;
  /** @deprecated use `MonitoringOptions$outboundSchema` instead. */
  export const outboundSchema = MonitoringOptions$outboundSchema;
  /** @deprecated use `MonitoringOptions$Outbound` instead. */
  export type Outbound = MonitoringOptions$Outbound;
}

export function monitoringOptionsToJSON(
  monitoringOptions: MonitoringOptions,
): string {
  return JSON.stringify(
    MonitoringOptions$outboundSchema.parse(monitoringOptions),
  );
}

export function monitoringOptionsFromJSON(
  jsonString: string,
): SafeParseResult<MonitoringOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MonitoringOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MonitoringOptions' from JSON`,
  );
}

/** @internal */
export const GetWebsiteResponsePlatformOptions$inboundSchema: z.ZodType<
  GetWebsiteResponsePlatformOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  probePlatforms: z.array(ProbePlatform$inboundSchema),
  testFromAll: z.boolean().optional(),
});

/** @internal */
export type GetWebsiteResponsePlatformOptions$Outbound = {
  probePlatforms: Array<string>;
  testFromAll?: boolean | undefined;
};

/** @internal */
export const GetWebsiteResponsePlatformOptions$outboundSchema: z.ZodType<
  GetWebsiteResponsePlatformOptions$Outbound,
  z.ZodTypeDef,
  GetWebsiteResponsePlatformOptions
> = z.object({
  probePlatforms: z.array(ProbePlatform$outboundSchema),
  testFromAll: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponsePlatformOptions$ {
  /** @deprecated use `GetWebsiteResponsePlatformOptions$inboundSchema` instead. */
  export const inboundSchema = GetWebsiteResponsePlatformOptions$inboundSchema;
  /** @deprecated use `GetWebsiteResponsePlatformOptions$outboundSchema` instead. */
  export const outboundSchema =
    GetWebsiteResponsePlatformOptions$outboundSchema;
  /** @deprecated use `GetWebsiteResponsePlatformOptions$Outbound` instead. */
  export type Outbound = GetWebsiteResponsePlatformOptions$Outbound;
}

export function getWebsiteResponsePlatformOptionsToJSON(
  getWebsiteResponsePlatformOptions: GetWebsiteResponsePlatformOptions,
): string {
  return JSON.stringify(
    GetWebsiteResponsePlatformOptions$outboundSchema.parse(
      getWebsiteResponsePlatformOptions,
    ),
  );
}

export function getWebsiteResponsePlatformOptionsFromJSON(
  jsonString: string,
): SafeParseResult<GetWebsiteResponsePlatformOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebsiteResponsePlatformOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebsiteResponsePlatformOptions' from JSON`,
  );
}

/** @internal */
export const GetWebsiteResponseFailingTestLocations$inboundSchema:
  z.ZodNativeEnum<typeof GetWebsiteResponseFailingTestLocations> = z.nativeEnum(
    GetWebsiteResponseFailingTestLocations,
  );

/** @internal */
export const GetWebsiteResponseFailingTestLocations$outboundSchema:
  z.ZodNativeEnum<typeof GetWebsiteResponseFailingTestLocations> =
    GetWebsiteResponseFailingTestLocations$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponseFailingTestLocations$ {
  /** @deprecated use `GetWebsiteResponseFailingTestLocations$inboundSchema` instead. */
  export const inboundSchema =
    GetWebsiteResponseFailingTestLocations$inboundSchema;
  /** @deprecated use `GetWebsiteResponseFailingTestLocations$outboundSchema` instead. */
  export const outboundSchema =
    GetWebsiteResponseFailingTestLocations$outboundSchema;
}

/** @internal */
export const GetWebsiteResponseOutageConfiguration$inboundSchema: z.ZodType<
  GetWebsiteResponseOutageConfiguration,
  z.ZodTypeDef,
  unknown
> = z.object({
  failingTestLocations: GetWebsiteResponseFailingTestLocations$inboundSchema,
  consecutiveForDown: z.number().int(),
});

/** @internal */
export type GetWebsiteResponseOutageConfiguration$Outbound = {
  failingTestLocations: string;
  consecutiveForDown: number;
};

/** @internal */
export const GetWebsiteResponseOutageConfiguration$outboundSchema: z.ZodType<
  GetWebsiteResponseOutageConfiguration$Outbound,
  z.ZodTypeDef,
  GetWebsiteResponseOutageConfiguration
> = z.object({
  failingTestLocations: GetWebsiteResponseFailingTestLocations$outboundSchema,
  consecutiveForDown: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponseOutageConfiguration$ {
  /** @deprecated use `GetWebsiteResponseOutageConfiguration$inboundSchema` instead. */
  export const inboundSchema =
    GetWebsiteResponseOutageConfiguration$inboundSchema;
  /** @deprecated use `GetWebsiteResponseOutageConfiguration$outboundSchema` instead. */
  export const outboundSchema =
    GetWebsiteResponseOutageConfiguration$outboundSchema;
  /** @deprecated use `GetWebsiteResponseOutageConfiguration$Outbound` instead. */
  export type Outbound = GetWebsiteResponseOutageConfiguration$Outbound;
}

export function getWebsiteResponseOutageConfigurationToJSON(
  getWebsiteResponseOutageConfiguration: GetWebsiteResponseOutageConfiguration,
): string {
  return JSON.stringify(
    GetWebsiteResponseOutageConfiguration$outboundSchema.parse(
      getWebsiteResponseOutageConfiguration,
    ),
  );
}

export function getWebsiteResponseOutageConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<GetWebsiteResponseOutageConfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetWebsiteResponseOutageConfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebsiteResponseOutageConfiguration' from JSON`,
  );
}

/** @internal */
export const GetWebsiteResponseOperator$inboundSchema: z.ZodNativeEnum<
  typeof GetWebsiteResponseOperator
> = z.nativeEnum(GetWebsiteResponseOperator);

/** @internal */
export const GetWebsiteResponseOperator$outboundSchema: z.ZodNativeEnum<
  typeof GetWebsiteResponseOperator
> = GetWebsiteResponseOperator$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponseOperator$ {
  /** @deprecated use `GetWebsiteResponseOperator$inboundSchema` instead. */
  export const inboundSchema = GetWebsiteResponseOperator$inboundSchema;
  /** @deprecated use `GetWebsiteResponseOperator$outboundSchema` instead. */
  export const outboundSchema = GetWebsiteResponseOperator$outboundSchema;
}

/** @internal */
export const GetWebsiteResponseCheckForString$inboundSchema: z.ZodType<
  GetWebsiteResponseCheckForString,
  z.ZodTypeDef,
  unknown
> = z.object({
  operator: GetWebsiteResponseOperator$inboundSchema,
  value: z.string(),
});

/** @internal */
export type GetWebsiteResponseCheckForString$Outbound = {
  operator: string;
  value: string;
};

/** @internal */
export const GetWebsiteResponseCheckForString$outboundSchema: z.ZodType<
  GetWebsiteResponseCheckForString$Outbound,
  z.ZodTypeDef,
  GetWebsiteResponseCheckForString
> = z.object({
  operator: GetWebsiteResponseOperator$outboundSchema,
  value: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponseCheckForString$ {
  /** @deprecated use `GetWebsiteResponseCheckForString$inboundSchema` instead. */
  export const inboundSchema = GetWebsiteResponseCheckForString$inboundSchema;
  /** @deprecated use `GetWebsiteResponseCheckForString$outboundSchema` instead. */
  export const outboundSchema = GetWebsiteResponseCheckForString$outboundSchema;
  /** @deprecated use `GetWebsiteResponseCheckForString$Outbound` instead. */
  export type Outbound = GetWebsiteResponseCheckForString$Outbound;
}

export function getWebsiteResponseCheckForStringToJSON(
  getWebsiteResponseCheckForString: GetWebsiteResponseCheckForString,
): string {
  return JSON.stringify(
    GetWebsiteResponseCheckForString$outboundSchema.parse(
      getWebsiteResponseCheckForString,
    ),
  );
}

export function getWebsiteResponseCheckForStringFromJSON(
  jsonString: string,
): SafeParseResult<GetWebsiteResponseCheckForString, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebsiteResponseCheckForString$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebsiteResponseCheckForString' from JSON`,
  );
}

/** @internal */
export const GetWebsiteResponseSsl$inboundSchema: z.ZodType<
  GetWebsiteResponseSsl,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.nullable(z.boolean()).optional(),
  daysPriorToExpiration: z.nullable(z.number().int()).optional(),
  ignoreIntermediateCertificates: z.nullable(z.boolean()).optional(),
});

/** @internal */
export type GetWebsiteResponseSsl$Outbound = {
  enabled?: boolean | null | undefined;
  daysPriorToExpiration?: number | null | undefined;
  ignoreIntermediateCertificates?: boolean | null | undefined;
};

/** @internal */
export const GetWebsiteResponseSsl$outboundSchema: z.ZodType<
  GetWebsiteResponseSsl$Outbound,
  z.ZodTypeDef,
  GetWebsiteResponseSsl
> = z.object({
  enabled: z.nullable(z.boolean()).optional(),
  daysPriorToExpiration: z.nullable(z.number().int()).optional(),
  ignoreIntermediateCertificates: z.nullable(z.boolean()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponseSsl$ {
  /** @deprecated use `GetWebsiteResponseSsl$inboundSchema` instead. */
  export const inboundSchema = GetWebsiteResponseSsl$inboundSchema;
  /** @deprecated use `GetWebsiteResponseSsl$outboundSchema` instead. */
  export const outboundSchema = GetWebsiteResponseSsl$outboundSchema;
  /** @deprecated use `GetWebsiteResponseSsl$Outbound` instead. */
  export type Outbound = GetWebsiteResponseSsl$Outbound;
}

export function getWebsiteResponseSslToJSON(
  getWebsiteResponseSsl: GetWebsiteResponseSsl,
): string {
  return JSON.stringify(
    GetWebsiteResponseSsl$outboundSchema.parse(getWebsiteResponseSsl),
  );
}

export function getWebsiteResponseSslFromJSON(
  jsonString: string,
): SafeParseResult<GetWebsiteResponseSsl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebsiteResponseSsl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebsiteResponseSsl' from JSON`,
  );
}

/** @internal */
export const GetWebsiteResponseAvailabilityCheckSettings$inboundSchema:
  z.ZodType<
    GetWebsiteResponseAvailabilityCheckSettings,
    z.ZodTypeDef,
    unknown
  > = z.object({
    platformOptions: z.nullable(
      z.lazy(() => GetWebsiteResponsePlatformOptions$inboundSchema),
    ).optional(),
    testFrom: TestFrom$inboundSchema,
    testIntervalInSeconds: z.number(),
    outageConfiguration: z.nullable(
      z.lazy(() => GetWebsiteResponseOutageConfiguration$inboundSchema),
    ).optional(),
    checkForString: z.nullable(
      z.lazy(() => GetWebsiteResponseCheckForString$inboundSchema),
    ).optional(),
    protocols: z.array(WebsiteProtocol$inboundSchema),
    ssl: z.nullable(z.lazy(() => GetWebsiteResponseSsl$inboundSchema))
      .optional(),
    customHeaders: z.nullable(z.array(CustomHeaders$inboundSchema)).optional(),
    allowInsecureRenegotiation: z.boolean().optional(),
    postData: z.nullable(z.string()).optional(),
  });

/** @internal */
export type GetWebsiteResponseAvailabilityCheckSettings$Outbound = {
  platformOptions?:
    | GetWebsiteResponsePlatformOptions$Outbound
    | null
    | undefined;
  testFrom: TestFrom$Outbound;
  testIntervalInSeconds: number;
  outageConfiguration?:
    | GetWebsiteResponseOutageConfiguration$Outbound
    | null
    | undefined;
  checkForString?: GetWebsiteResponseCheckForString$Outbound | null | undefined;
  protocols: Array<string>;
  ssl?: GetWebsiteResponseSsl$Outbound | null | undefined;
  customHeaders?: Array<CustomHeaders$Outbound> | null | undefined;
  allowInsecureRenegotiation?: boolean | undefined;
  postData?: string | null | undefined;
};

/** @internal */
export const GetWebsiteResponseAvailabilityCheckSettings$outboundSchema:
  z.ZodType<
    GetWebsiteResponseAvailabilityCheckSettings$Outbound,
    z.ZodTypeDef,
    GetWebsiteResponseAvailabilityCheckSettings
  > = z.object({
    platformOptions: z.nullable(
      z.lazy(() => GetWebsiteResponsePlatformOptions$outboundSchema),
    ).optional(),
    testFrom: TestFrom$outboundSchema,
    testIntervalInSeconds: z.number(),
    outageConfiguration: z.nullable(
      z.lazy(() => GetWebsiteResponseOutageConfiguration$outboundSchema),
    ).optional(),
    checkForString: z.nullable(
      z.lazy(() => GetWebsiteResponseCheckForString$outboundSchema),
    ).optional(),
    protocols: z.array(WebsiteProtocol$outboundSchema),
    ssl: z.nullable(z.lazy(() => GetWebsiteResponseSsl$outboundSchema))
      .optional(),
    customHeaders: z.nullable(z.array(CustomHeaders$outboundSchema)).optional(),
    allowInsecureRenegotiation: z.boolean().optional(),
    postData: z.nullable(z.string()).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponseAvailabilityCheckSettings$ {
  /** @deprecated use `GetWebsiteResponseAvailabilityCheckSettings$inboundSchema` instead. */
  export const inboundSchema =
    GetWebsiteResponseAvailabilityCheckSettings$inboundSchema;
  /** @deprecated use `GetWebsiteResponseAvailabilityCheckSettings$outboundSchema` instead. */
  export const outboundSchema =
    GetWebsiteResponseAvailabilityCheckSettings$outboundSchema;
  /** @deprecated use `GetWebsiteResponseAvailabilityCheckSettings$Outbound` instead. */
  export type Outbound = GetWebsiteResponseAvailabilityCheckSettings$Outbound;
}

export function getWebsiteResponseAvailabilityCheckSettingsToJSON(
  getWebsiteResponseAvailabilityCheckSettings:
    GetWebsiteResponseAvailabilityCheckSettings,
): string {
  return JSON.stringify(
    GetWebsiteResponseAvailabilityCheckSettings$outboundSchema.parse(
      getWebsiteResponseAvailabilityCheckSettings,
    ),
  );
}

export function getWebsiteResponseAvailabilityCheckSettingsFromJSON(
  jsonString: string,
): SafeParseResult<
  GetWebsiteResponseAvailabilityCheckSettings,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetWebsiteResponseAvailabilityCheckSettings$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetWebsiteResponseAvailabilityCheckSettings' from JSON`,
  );
}

/** @internal */
export const GetWebsiteResponseRum$inboundSchema: z.ZodType<
  GetWebsiteResponseRum,
  z.ZodTypeDef,
  unknown
> = z.object({
  apdexTimeInSeconds: z.number().int().optional(),
  snippet: z.string().optional(),
  spa: z.boolean(),
});

/** @internal */
export type GetWebsiteResponseRum$Outbound = {
  apdexTimeInSeconds?: number | undefined;
  snippet?: string | undefined;
  spa: boolean;
};

/** @internal */
export const GetWebsiteResponseRum$outboundSchema: z.ZodType<
  GetWebsiteResponseRum$Outbound,
  z.ZodTypeDef,
  GetWebsiteResponseRum
> = z.object({
  apdexTimeInSeconds: z.number().int().optional(),
  snippet: z.string().optional(),
  spa: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponseRum$ {
  /** @deprecated use `GetWebsiteResponseRum$inboundSchema` instead. */
  export const inboundSchema = GetWebsiteResponseRum$inboundSchema;
  /** @deprecated use `GetWebsiteResponseRum$outboundSchema` instead. */
  export const outboundSchema = GetWebsiteResponseRum$outboundSchema;
  /** @deprecated use `GetWebsiteResponseRum$Outbound` instead. */
  export type Outbound = GetWebsiteResponseRum$Outbound;
}

export function getWebsiteResponseRumToJSON(
  getWebsiteResponseRum: GetWebsiteResponseRum,
): string {
  return JSON.stringify(
    GetWebsiteResponseRum$outboundSchema.parse(getWebsiteResponseRum),
  );
}

export function getWebsiteResponseRumFromJSON(
  jsonString: string,
): SafeParseResult<GetWebsiteResponseRum, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebsiteResponseRum$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebsiteResponseRum' from JSON`,
  );
}

/** @internal */
export const GetWebsiteResponse$inboundSchema: z.ZodType<
  GetWebsiteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.string(),
  status: GetWebsiteResponseStatus$inboundSchema,
  name: z.string(),
  url: z.string(),
  monitoringOptions: z.lazy(() => MonitoringOptions$inboundSchema),
  availabilityCheckSettings: z.nullable(
    z.lazy(() => GetWebsiteResponseAvailabilityCheckSettings$inboundSchema),
  ).optional(),
  tags: z.array(Tag$inboundSchema).optional(),
  rum: z.lazy(() => GetWebsiteResponseRum$inboundSchema).optional(),
  lastOutageStartTime: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  lastOutageEndTime: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  lastTestTime: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  lastErrorTime: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  lastResponseTime: z.nullable(z.number().int()).optional(),
  nextOnDemandAvailabilityTime: z.number().int().optional(),
});

/** @internal */
export type GetWebsiteResponse$Outbound = {
  id: string;
  type: string;
  status: string;
  name: string;
  url: string;
  monitoringOptions: MonitoringOptions$Outbound;
  availabilityCheckSettings?:
    | GetWebsiteResponseAvailabilityCheckSettings$Outbound
    | null
    | undefined;
  tags?: Array<Tag$Outbound> | undefined;
  rum?: GetWebsiteResponseRum$Outbound | undefined;
  lastOutageStartTime?: string | null | undefined;
  lastOutageEndTime?: string | null | undefined;
  lastTestTime?: string | null | undefined;
  lastErrorTime?: string | null | undefined;
  lastResponseTime?: number | null | undefined;
  nextOnDemandAvailabilityTime?: number | undefined;
};

/** @internal */
export const GetWebsiteResponse$outboundSchema: z.ZodType<
  GetWebsiteResponse$Outbound,
  z.ZodTypeDef,
  GetWebsiteResponse
> = z.object({
  id: z.string(),
  type: z.string(),
  status: GetWebsiteResponseStatus$outboundSchema,
  name: z.string(),
  url: z.string(),
  monitoringOptions: z.lazy(() => MonitoringOptions$outboundSchema),
  availabilityCheckSettings: z.nullable(
    z.lazy(() => GetWebsiteResponseAvailabilityCheckSettings$outboundSchema),
  ).optional(),
  tags: z.array(Tag$outboundSchema).optional(),
  rum: z.lazy(() => GetWebsiteResponseRum$outboundSchema).optional(),
  lastOutageStartTime: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  lastOutageEndTime: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  lastTestTime: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  lastErrorTime: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  lastResponseTime: z.nullable(z.number().int()).optional(),
  nextOnDemandAvailabilityTime: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWebsiteResponse$ {
  /** @deprecated use `GetWebsiteResponse$inboundSchema` instead. */
  export const inboundSchema = GetWebsiteResponse$inboundSchema;
  /** @deprecated use `GetWebsiteResponse$outboundSchema` instead. */
  export const outboundSchema = GetWebsiteResponse$outboundSchema;
  /** @deprecated use `GetWebsiteResponse$Outbound` instead. */
  export type Outbound = GetWebsiteResponse$Outbound;
}

export function getWebsiteResponseToJSON(
  getWebsiteResponse: GetWebsiteResponse,
): string {
  return JSON.stringify(
    GetWebsiteResponse$outboundSchema.parse(getWebsiteResponse),
  );
}

export function getWebsiteResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWebsiteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebsiteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebsiteResponse' from JSON`,
  );
}
