/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LogsEvent = {
  id: string;
  time: string;
  message: string;
  hostname: string;
  severity: string;
  program: string;
};

/** @internal */
export const LogsEvent$inboundSchema: z.ZodType<
  LogsEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  time: z.string(),
  message: z.string(),
  hostname: z.string(),
  severity: z.string(),
  program: z.string(),
});

export function logsEventFromJSON(
  jsonString: string,
): SafeParseResult<LogsEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LogsEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LogsEvent' from JSON`,
  );
}
