/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const MetricsAggregationMethods = {
  Avg: "AVG",
  Count: "COUNT",
  Min: "MIN",
  Max: "MAX",
  Sum: "SUM",
  Last: "LAST",
} as const;
export type MetricsAggregationMethods = ClosedEnum<
  typeof MetricsAggregationMethods
>;

/** @internal */
export const MetricsAggregationMethods$inboundSchema: z.ZodNativeEnum<
  typeof MetricsAggregationMethods
> = z.nativeEnum(MetricsAggregationMethods);

/** @internal */
export const MetricsAggregationMethods$outboundSchema: z.ZodNativeEnum<
  typeof MetricsAggregationMethods
> = MetricsAggregationMethods$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MetricsAggregationMethods$ {
  /** @deprecated use `MetricsAggregationMethods$inboundSchema` instead. */
  export const inboundSchema = MetricsAggregationMethods$inboundSchema;
  /** @deprecated use `MetricsAggregationMethods$outboundSchema` instead. */
  export const outboundSchema = MetricsAggregationMethods$outboundSchema;
}
