/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MetricsMeasurement = {
  /**
   * Time of the measurement.
   */
  time: Date;
  /**
   * Value of the measurement.
   */
  value: number;
};

/** @internal */
export const MetricsMeasurement$inboundSchema: z.ZodType<
  MetricsMeasurement,
  z.ZodTypeDef,
  unknown
> = z.object({
  time: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  value: z.number(),
});

export function metricsMeasurementFromJSON(
  jsonString: string,
): SafeParseResult<MetricsMeasurement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricsMeasurement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricsMeasurement' from JSON`,
  );
}
