/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MetricsCompositeMetric = {
  /**
   * Name of the composite metric.
   */
  name: string;
  /**
   * Display name of the composite metric. A short description of the metric.
   */
  displayName?: string | null | undefined;
  /**
   * Description of the composite metric. A detailed description of the metric.
   */
  description?: string | null | undefined;
  /**
   * PromQL query to calculate the composite metric.
   */
  formula: string;
  /**
   * Unit of the composite metric.
   */
  units?: string | null | undefined;
};

/** @internal */
export const MetricsCompositeMetric$inboundSchema: z.ZodType<
  MetricsCompositeMetric,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  displayName: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  formula: z.string(),
  units: z.nullable(z.string()).optional(),
});

/** @internal */
export type MetricsCompositeMetric$Outbound = {
  name: string;
  displayName?: string | null | undefined;
  description?: string | null | undefined;
  formula: string;
  units?: string | null | undefined;
};

/** @internal */
export const MetricsCompositeMetric$outboundSchema: z.ZodType<
  MetricsCompositeMetric$Outbound,
  z.ZodTypeDef,
  MetricsCompositeMetric
> = z.object({
  name: z.string(),
  displayName: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  formula: z.string(),
  units: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MetricsCompositeMetric$ {
  /** @deprecated use `MetricsCompositeMetric$inboundSchema` instead. */
  export const inboundSchema = MetricsCompositeMetric$inboundSchema;
  /** @deprecated use `MetricsCompositeMetric$outboundSchema` instead. */
  export const outboundSchema = MetricsCompositeMetric$outboundSchema;
  /** @deprecated use `MetricsCompositeMetric$Outbound` instead. */
  export type Outbound = MetricsCompositeMetric$Outbound;
}

export function metricsCompositeMetricToJSON(
  metricsCompositeMetric: MetricsCompositeMetric,
): string {
  return JSON.stringify(
    MetricsCompositeMetric$outboundSchema.parse(metricsCompositeMetric),
  );
}

export function metricsCompositeMetricFromJSON(
  jsonString: string,
): SafeParseResult<MetricsCompositeMetric, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricsCompositeMetric$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricsCompositeMetric' from JSON`,
  );
}
