/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const MetricErrorCode = {
  AccessForbidden: "AccessForbidden",
  InternalError: "InternalError",
  InvalidRequest: "InvalidRequest",
  ResourceNotFound: "ResourceNotFound",
  ServiceUnavailable: "ServiceUnavailable",
  Unauthorized: "Unauthorized",
  CannotModifyMetric: "CannotModifyMetric",
  MetricNameExists: "MetricNameExists",
} as const;
export type MetricErrorCode = ClosedEnum<typeof MetricErrorCode>;

/** @internal */
export const MetricErrorCode$inboundSchema: z.ZodNativeEnum<
  typeof MetricErrorCode
> = z.nativeEnum(MetricErrorCode);

/** @internal */
export const MetricErrorCode$outboundSchema: z.ZodNativeEnum<
  typeof MetricErrorCode
> = MetricErrorCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MetricErrorCode$ {
  /** @deprecated use `MetricErrorCode$inboundSchema` instead. */
  export const inboundSchema = MetricErrorCode$inboundSchema;
  /** @deprecated use `MetricErrorCode$outboundSchema` instead. */
  export const outboundSchema = MetricErrorCode$outboundSchema;
}
