/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MetricsMeasurement = {
  /**
   * Time of the measurement.
   */
  time: Date;
  /**
   * Value of the measurement.
   */
  value: number;
};

/** @internal */
export const MetricsMeasurement$inboundSchema: z.ZodType<
  MetricsMeasurement,
  z.ZodTypeDef,
  unknown
> = z.object({
  time: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  value: z.number(),
});

/** @internal */
export type MetricsMeasurement$Outbound = {
  time: string;
  value: number;
};

/** @internal */
export const MetricsMeasurement$outboundSchema: z.ZodType<
  MetricsMeasurement$Outbound,
  z.ZodTypeDef,
  MetricsMeasurement
> = z.object({
  time: z.date().transform(v => v.toISOString()),
  value: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MetricsMeasurement$ {
  /** @deprecated use `MetricsMeasurement$inboundSchema` instead. */
  export const inboundSchema = MetricsMeasurement$inboundSchema;
  /** @deprecated use `MetricsMeasurement$outboundSchema` instead. */
  export const outboundSchema = MetricsMeasurement$outboundSchema;
  /** @deprecated use `MetricsMeasurement$Outbound` instead. */
  export type Outbound = MetricsMeasurement$Outbound;
}

export function metricsMeasurementToJSON(
  metricsMeasurement: MetricsMeasurement,
): string {
  return JSON.stringify(
    MetricsMeasurement$outboundSchema.parse(metricsMeasurement),
  );
}

export function metricsMeasurementFromJSON(
  jsonString: string,
): SafeParseResult<MetricsMeasurement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricsMeasurement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricsMeasurement' from JSON`,
  );
}
