/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MgmtAccountOnboardingRequest = {
  /**
   * AWS Control Tower Management Account ID.
   */
  managementAccountId: string;
};

/** @internal */
export const MgmtAccountOnboardingRequest$inboundSchema: z.ZodType<
  MgmtAccountOnboardingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  managementAccountId: z.string(),
});

/** @internal */
export type MgmtAccountOnboardingRequest$Outbound = {
  managementAccountId: string;
};

/** @internal */
export const MgmtAccountOnboardingRequest$outboundSchema: z.ZodType<
  MgmtAccountOnboardingRequest$Outbound,
  z.ZodTypeDef,
  MgmtAccountOnboardingRequest
> = z.object({
  managementAccountId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MgmtAccountOnboardingRequest$ {
  /** @deprecated use `MgmtAccountOnboardingRequest$inboundSchema` instead. */
  export const inboundSchema = MgmtAccountOnboardingRequest$inboundSchema;
  /** @deprecated use `MgmtAccountOnboardingRequest$outboundSchema` instead. */
  export const outboundSchema = MgmtAccountOnboardingRequest$outboundSchema;
  /** @deprecated use `MgmtAccountOnboardingRequest$Outbound` instead. */
  export type Outbound = MgmtAccountOnboardingRequest$Outbound;
}

export function mgmtAccountOnboardingRequestToJSON(
  mgmtAccountOnboardingRequest: MgmtAccountOnboardingRequest,
): string {
  return JSON.stringify(
    MgmtAccountOnboardingRequest$outboundSchema.parse(
      mgmtAccountOnboardingRequest,
    ),
  );
}

export function mgmtAccountOnboardingRequestFromJSON(
  jsonString: string,
): SafeParseResult<MgmtAccountOnboardingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MgmtAccountOnboardingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MgmtAccountOnboardingRequest' from JSON`,
  );
}
