/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CommonKeyValuePair,
  CommonKeyValuePair$inboundSchema,
  CommonKeyValuePair$Outbound,
  CommonKeyValuePair$outboundSchema,
} from "./commonkeyvaluepair.js";
import {
  DatabaseAuthMethod,
  DatabaseAuthMethod$inboundSchema,
  DatabaseAuthMethod$outboundSchema,
} from "./databaseauthmethod.js";
import {
  DatabaseConnectionOptions,
  DatabaseConnectionOptions$inboundSchema,
  DatabaseConnectionOptions$Outbound,
  DatabaseConnectionOptions$outboundSchema,
} from "./databaseconnectionoptions.js";
import {
  DatabaseType,
  DatabaseType$inboundSchema,
  DatabaseType$outboundSchema,
} from "./databasetype.js";

/**
 * Method for capturing metrics from database server: sniff/profiler/slow-log/poll, ignored for SqlServer and Redis
 */
export const CaptureMethod = {
  Sniffer: "sniffer",
  Poll: "poll",
  Profiler: "profiler",
  SlowLog: "slow-log",
} as const;
/**
 * Method for capturing metrics from database server: sniff/profiler/slow-log/poll, ignored for SqlServer and Redis
 */
export type CaptureMethod = ClosedEnum<typeof CaptureMethod>;

export type ObserveDatabaseRequest = {
  /**
   * Name for the observed database entity
   */
  name: string;
  /**
   * Swo Agent ID wehre the plugins for observing database server should run
   */
  agentId: string;
  /**
   * Database server type: mysql/mongo/mssql/pgsql/redis
   */
  dbType: DatabaseType;
  /**
   * Auth method to be used by the agent to connect to database server
   */
  authMethod: DatabaseAuthMethod;
  /**
   * Method for capturing metrics from database server: sniff/profiler/slow-log/poll, ignored for SqlServer and Redis
   */
  captureMethod?: CaptureMethod | null | undefined;
  /**
   * Optional advanced configuration options for plugins, e.g. disable-sampling
   */
  configOptions: Array<CommonKeyValuePair> | null;
  /**
   * Options specifying how plugins connect to database server
   */
  dbConnOptions: DatabaseConnectionOptions;
  /**
   * Tags for observed database entity
   */
  tags: Array<CommonKeyValuePair> | null;
};

/** @internal */
export const CaptureMethod$inboundSchema: z.ZodNativeEnum<
  typeof CaptureMethod
> = z.nativeEnum(CaptureMethod);

/** @internal */
export const CaptureMethod$outboundSchema: z.ZodNativeEnum<
  typeof CaptureMethod
> = CaptureMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CaptureMethod$ {
  /** @deprecated use `CaptureMethod$inboundSchema` instead. */
  export const inboundSchema = CaptureMethod$inboundSchema;
  /** @deprecated use `CaptureMethod$outboundSchema` instead. */
  export const outboundSchema = CaptureMethod$outboundSchema;
}

/** @internal */
export const ObserveDatabaseRequest$inboundSchema: z.ZodType<
  ObserveDatabaseRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  agentId: z.string(),
  dbType: DatabaseType$inboundSchema,
  authMethod: DatabaseAuthMethod$inboundSchema,
  captureMethod: z.nullable(CaptureMethod$inboundSchema).default(null),
  configOptions: z.nullable(z.array(CommonKeyValuePair$inboundSchema)),
  dbConnOptions: DatabaseConnectionOptions$inboundSchema,
  tags: z.nullable(z.array(CommonKeyValuePair$inboundSchema)),
});

/** @internal */
export type ObserveDatabaseRequest$Outbound = {
  name: string;
  agentId: string;
  dbType: string;
  authMethod: string;
  captureMethod: string | null;
  configOptions: Array<CommonKeyValuePair$Outbound> | null;
  dbConnOptions: DatabaseConnectionOptions$Outbound;
  tags: Array<CommonKeyValuePair$Outbound> | null;
};

/** @internal */
export const ObserveDatabaseRequest$outboundSchema: z.ZodType<
  ObserveDatabaseRequest$Outbound,
  z.ZodTypeDef,
  ObserveDatabaseRequest
> = z.object({
  name: z.string(),
  agentId: z.string(),
  dbType: DatabaseType$outboundSchema,
  authMethod: DatabaseAuthMethod$outboundSchema,
  captureMethod: z.nullable(CaptureMethod$outboundSchema).default(null),
  configOptions: z.nullable(z.array(CommonKeyValuePair$outboundSchema)),
  dbConnOptions: DatabaseConnectionOptions$outboundSchema,
  tags: z.nullable(z.array(CommonKeyValuePair$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ObserveDatabaseRequest$ {
  /** @deprecated use `ObserveDatabaseRequest$inboundSchema` instead. */
  export const inboundSchema = ObserveDatabaseRequest$inboundSchema;
  /** @deprecated use `ObserveDatabaseRequest$outboundSchema` instead. */
  export const outboundSchema = ObserveDatabaseRequest$outboundSchema;
  /** @deprecated use `ObserveDatabaseRequest$Outbound` instead. */
  export type Outbound = ObserveDatabaseRequest$Outbound;
}

export function observeDatabaseRequestToJSON(
  observeDatabaseRequest: ObserveDatabaseRequest,
): string {
  return JSON.stringify(
    ObserveDatabaseRequest$outboundSchema.parse(observeDatabaseRequest),
  );
}

export function observeDatabaseRequestFromJSON(
  jsonString: string,
): SafeParseResult<ObserveDatabaseRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ObserveDatabaseRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ObserveDatabaseRequest' from JSON`,
  );
}
