/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * How many locations must report a failure for an entity to be considered down.
 */
export const OutageConfigurationFailingTestLocations = {
  All: "all",
  Any: "any",
} as const;
/**
 * How many locations must report a failure for an entity to be considered down.
 */
export type OutageConfigurationFailingTestLocations = ClosedEnum<
  typeof OutageConfigurationFailingTestLocations
>;

export type OutageConfiguration = {
  /**
   * How many locations must report a failure for an entity to be considered down.
   */
  failingTestLocations: OutageConfigurationFailingTestLocations;
  /**
   * Number of consecutive failing tests for an entity to be considered down.
   */
  consecutiveForDown: number;
};

/** @internal */
export const OutageConfigurationFailingTestLocations$inboundSchema:
  z.ZodNativeEnum<typeof OutageConfigurationFailingTestLocations> = z
    .nativeEnum(OutageConfigurationFailingTestLocations);

/** @internal */
export const OutageConfigurationFailingTestLocations$outboundSchema:
  z.ZodNativeEnum<typeof OutageConfigurationFailingTestLocations> =
    OutageConfigurationFailingTestLocations$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OutageConfigurationFailingTestLocations$ {
  /** @deprecated use `OutageConfigurationFailingTestLocations$inboundSchema` instead. */
  export const inboundSchema =
    OutageConfigurationFailingTestLocations$inboundSchema;
  /** @deprecated use `OutageConfigurationFailingTestLocations$outboundSchema` instead. */
  export const outboundSchema =
    OutageConfigurationFailingTestLocations$outboundSchema;
}

/** @internal */
export const OutageConfiguration$inboundSchema: z.ZodType<
  OutageConfiguration,
  z.ZodTypeDef,
  unknown
> = z.object({
  failingTestLocations: OutageConfigurationFailingTestLocations$inboundSchema,
  consecutiveForDown: z.number().int(),
});

/** @internal */
export type OutageConfiguration$Outbound = {
  failingTestLocations: string;
  consecutiveForDown: number;
};

/** @internal */
export const OutageConfiguration$outboundSchema: z.ZodType<
  OutageConfiguration$Outbound,
  z.ZodTypeDef,
  OutageConfiguration
> = z.object({
  failingTestLocations: OutageConfigurationFailingTestLocations$outboundSchema,
  consecutiveForDown: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OutageConfiguration$ {
  /** @deprecated use `OutageConfiguration$inboundSchema` instead. */
  export const inboundSchema = OutageConfiguration$inboundSchema;
  /** @deprecated use `OutageConfiguration$outboundSchema` instead. */
  export const outboundSchema = OutageConfiguration$outboundSchema;
  /** @deprecated use `OutageConfiguration$Outbound` instead. */
  export type Outbound = OutageConfiguration$Outbound;
}

export function outageConfigurationToJSON(
  outageConfiguration: OutageConfiguration,
): string {
  return JSON.stringify(
    OutageConfiguration$outboundSchema.parse(outageConfiguration),
  );
}

export function outageConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<OutageConfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutageConfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutageConfiguration' from JSON`,
  );
}
