/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ProbePlatform,
  ProbePlatform$inboundSchema,
  ProbePlatform$outboundSchema,
} from "./probeplatform.js";

export type ProbePlatformOptions = {
  /**
   * Cloud platforms hosting synthetic probes.
   */
  probePlatforms: Array<ProbePlatform>;
  testFromAll?: boolean | undefined;
};

/** @internal */
export const ProbePlatformOptions$inboundSchema: z.ZodType<
  ProbePlatformOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  probePlatforms: z.array(ProbePlatform$inboundSchema),
  testFromAll: z.boolean().optional(),
});

/** @internal */
export type ProbePlatformOptions$Outbound = {
  probePlatforms: Array<string>;
  testFromAll?: boolean | undefined;
};

/** @internal */
export const ProbePlatformOptions$outboundSchema: z.ZodType<
  ProbePlatformOptions$Outbound,
  z.ZodTypeDef,
  ProbePlatformOptions
> = z.object({
  probePlatforms: z.array(ProbePlatform$outboundSchema),
  testFromAll: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProbePlatformOptions$ {
  /** @deprecated use `ProbePlatformOptions$inboundSchema` instead. */
  export const inboundSchema = ProbePlatformOptions$inboundSchema;
  /** @deprecated use `ProbePlatformOptions$outboundSchema` instead. */
  export const outboundSchema = ProbePlatformOptions$outboundSchema;
  /** @deprecated use `ProbePlatformOptions$Outbound` instead. */
  export type Outbound = ProbePlatformOptions$Outbound;
}

export function probePlatformOptionsToJSON(
  probePlatformOptions: ProbePlatformOptions,
): string {
  return JSON.stringify(
    ProbePlatformOptions$outboundSchema.parse(probePlatformOptions),
  );
}

export function probePlatformOptionsFromJSON(
  jsonString: string,
): SafeParseResult<ProbePlatformOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProbePlatformOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProbePlatformOptions' from JSON`,
  );
}
