/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CommonKeyValuePair,
  CommonKeyValuePair$inboundSchema,
  CommonKeyValuePair$Outbound,
  CommonKeyValuePair$outboundSchema,
} from "./commonkeyvaluepair.js";

/**
 * SSL mode such as require, verify-ca, verify-full as applicable
 */
export const UpdateDatabaseRequestSslMode = {
  Require: "require",
  VerfifyCa: "verfify-ca",
  VerifyFull: "verify-full",
} as const;
/**
 * SSL mode such as require, verify-ca, verify-full as applicable
 */
export type UpdateDatabaseRequestSslMode = ClosedEnum<
  typeof UpdateDatabaseRequestSslMode
>;

/**
 * SSL connection options, when sslEnabled is true
 */
export type UpdateDatabaseRequestSslOptions = {
  /**
   * SSL mode such as require, verify-ca, verify-full as applicable
   */
  sslMode?: UpdateDatabaseRequestSslMode | undefined;
  /**
   * CA file path
   */
  sslCAPath?: string | undefined;
  /**
   * SSL key file path
   */
  sslKeyPath?: string | undefined;
  /**
   * SSL cert file path
   */
  sslCertPath?: string | undefined;
};

/**
 * Options specifying how plugins connect to database server, authentication method change is not supported
 */
export type DbConnOptions = {
  /**
   * Database server host
   */
  host?: string | undefined;
  /**
   * Database server port
   */
  port?: string | null | undefined;
  /**
   * Encrypted credentials for connecting to database server when using basic auth method (username, password)
   */
  encryptedCredentials?: string | undefined;
  /**
   * Username for connecting to database server needed only for auth methods other than basic auth
   */
  user?: string | undefined;
  /**
   * Enable ssl when agent connects to database server
   */
  sslEnabled?: boolean | undefined;
  /**
   * SSL connection options, when sslEnabled is true
   */
  sslOptions?: UpdateDatabaseRequestSslOptions | null | undefined;
  /**
   * Cloud region in case of database managed by cloud provider, required for IAM authentication
   */
  cloudRegion?: string | undefined;
};

export type UpdateDatabaseRequest = {
  /**
   * Name for the observed database entity
   */
  name?: string | undefined;
  /**
   * Optional advanced configuration options for plugins, e.g. disable-sampling
   */
  configOptions?: Array<CommonKeyValuePair> | null | undefined;
  /**
   * Options specifying how plugins connect to database server, authentication method change is not supported
   */
  dbConnOptions?: DbConnOptions | null | undefined;
  /**
   * Tags for observed database entity
   */
  tags?: Array<CommonKeyValuePair> | null | undefined;
};

/** @internal */
export const UpdateDatabaseRequestSslMode$inboundSchema: z.ZodNativeEnum<
  typeof UpdateDatabaseRequestSslMode
> = z.nativeEnum(UpdateDatabaseRequestSslMode);

/** @internal */
export const UpdateDatabaseRequestSslMode$outboundSchema: z.ZodNativeEnum<
  typeof UpdateDatabaseRequestSslMode
> = UpdateDatabaseRequestSslMode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDatabaseRequestSslMode$ {
  /** @deprecated use `UpdateDatabaseRequestSslMode$inboundSchema` instead. */
  export const inboundSchema = UpdateDatabaseRequestSslMode$inboundSchema;
  /** @deprecated use `UpdateDatabaseRequestSslMode$outboundSchema` instead. */
  export const outboundSchema = UpdateDatabaseRequestSslMode$outboundSchema;
}

/** @internal */
export const UpdateDatabaseRequestSslOptions$inboundSchema: z.ZodType<
  UpdateDatabaseRequestSslOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  sslMode: UpdateDatabaseRequestSslMode$inboundSchema.default("require"),
  sslCAPath: z.string().default(""),
  sslKeyPath: z.string().default(""),
  sslCertPath: z.string().default(""),
});

/** @internal */
export type UpdateDatabaseRequestSslOptions$Outbound = {
  sslMode: string;
  sslCAPath: string;
  sslKeyPath: string;
  sslCertPath: string;
};

/** @internal */
export const UpdateDatabaseRequestSslOptions$outboundSchema: z.ZodType<
  UpdateDatabaseRequestSslOptions$Outbound,
  z.ZodTypeDef,
  UpdateDatabaseRequestSslOptions
> = z.object({
  sslMode: UpdateDatabaseRequestSslMode$outboundSchema.default("require"),
  sslCAPath: z.string().default(""),
  sslKeyPath: z.string().default(""),
  sslCertPath: z.string().default(""),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDatabaseRequestSslOptions$ {
  /** @deprecated use `UpdateDatabaseRequestSslOptions$inboundSchema` instead. */
  export const inboundSchema = UpdateDatabaseRequestSslOptions$inboundSchema;
  /** @deprecated use `UpdateDatabaseRequestSslOptions$outboundSchema` instead. */
  export const outboundSchema = UpdateDatabaseRequestSslOptions$outboundSchema;
  /** @deprecated use `UpdateDatabaseRequestSslOptions$Outbound` instead. */
  export type Outbound = UpdateDatabaseRequestSslOptions$Outbound;
}

export function updateDatabaseRequestSslOptionsToJSON(
  updateDatabaseRequestSslOptions: UpdateDatabaseRequestSslOptions,
): string {
  return JSON.stringify(
    UpdateDatabaseRequestSslOptions$outboundSchema.parse(
      updateDatabaseRequestSslOptions,
    ),
  );
}

export function updateDatabaseRequestSslOptionsFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDatabaseRequestSslOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDatabaseRequestSslOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDatabaseRequestSslOptions' from JSON`,
  );
}

/** @internal */
export const DbConnOptions$inboundSchema: z.ZodType<
  DbConnOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  host: z.string().optional(),
  port: z.nullable(z.string()).optional(),
  encryptedCredentials: z.string().default(""),
  user: z.string().default(""),
  sslEnabled: z.boolean().default(false),
  sslOptions: z.nullable(
    z.lazy(() => UpdateDatabaseRequestSslOptions$inboundSchema),
  ).optional(),
  cloudRegion: z.string().default(""),
});

/** @internal */
export type DbConnOptions$Outbound = {
  host?: string | undefined;
  port?: string | null | undefined;
  encryptedCredentials: string;
  user: string;
  sslEnabled: boolean;
  sslOptions?: UpdateDatabaseRequestSslOptions$Outbound | null | undefined;
  cloudRegion: string;
};

/** @internal */
export const DbConnOptions$outboundSchema: z.ZodType<
  DbConnOptions$Outbound,
  z.ZodTypeDef,
  DbConnOptions
> = z.object({
  host: z.string().optional(),
  port: z.nullable(z.string()).optional(),
  encryptedCredentials: z.string().default(""),
  user: z.string().default(""),
  sslEnabled: z.boolean().default(false),
  sslOptions: z.nullable(
    z.lazy(() => UpdateDatabaseRequestSslOptions$outboundSchema),
  ).optional(),
  cloudRegion: z.string().default(""),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DbConnOptions$ {
  /** @deprecated use `DbConnOptions$inboundSchema` instead. */
  export const inboundSchema = DbConnOptions$inboundSchema;
  /** @deprecated use `DbConnOptions$outboundSchema` instead. */
  export const outboundSchema = DbConnOptions$outboundSchema;
  /** @deprecated use `DbConnOptions$Outbound` instead. */
  export type Outbound = DbConnOptions$Outbound;
}

export function dbConnOptionsToJSON(dbConnOptions: DbConnOptions): string {
  return JSON.stringify(DbConnOptions$outboundSchema.parse(dbConnOptions));
}

export function dbConnOptionsFromJSON(
  jsonString: string,
): SafeParseResult<DbConnOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DbConnOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DbConnOptions' from JSON`,
  );
}

/** @internal */
export const UpdateDatabaseRequest$inboundSchema: z.ZodType<
  UpdateDatabaseRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().default(""),
  configOptions: z.nullable(z.array(CommonKeyValuePair$inboundSchema))
    .optional(),
  dbConnOptions: z.nullable(z.lazy(() => DbConnOptions$inboundSchema))
    .optional(),
  tags: z.nullable(z.array(CommonKeyValuePair$inboundSchema)).optional(),
});

/** @internal */
export type UpdateDatabaseRequest$Outbound = {
  name: string;
  configOptions?: Array<CommonKeyValuePair$Outbound> | null | undefined;
  dbConnOptions?: DbConnOptions$Outbound | null | undefined;
  tags?: Array<CommonKeyValuePair$Outbound> | null | undefined;
};

/** @internal */
export const UpdateDatabaseRequest$outboundSchema: z.ZodType<
  UpdateDatabaseRequest$Outbound,
  z.ZodTypeDef,
  UpdateDatabaseRequest
> = z.object({
  name: z.string().default(""),
  configOptions: z.nullable(z.array(CommonKeyValuePair$outboundSchema))
    .optional(),
  dbConnOptions: z.nullable(z.lazy(() => DbConnOptions$outboundSchema))
    .optional(),
  tags: z.nullable(z.array(CommonKeyValuePair$outboundSchema)).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDatabaseRequest$ {
  /** @deprecated use `UpdateDatabaseRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateDatabaseRequest$inboundSchema;
  /** @deprecated use `UpdateDatabaseRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateDatabaseRequest$outboundSchema;
  /** @deprecated use `UpdateDatabaseRequest$Outbound` instead. */
  export type Outbound = UpdateDatabaseRequest$Outbound;
}

export function updateDatabaseRequestToJSON(
  updateDatabaseRequest: UpdateDatabaseRequest,
): string {
  return JSON.stringify(
    UpdateDatabaseRequest$outboundSchema.parse(updateDatabaseRequest),
  );
}

export function updateDatabaseRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDatabaseRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDatabaseRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDatabaseRequest' from JSON`,
  );
}
