/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Protocol to perform availability checks for.
 */
export const WebsiteProtocol = {
  Http: "HTTP",
  Https: "HTTPS",
} as const;
/**
 * Protocol to perform availability checks for.
 */
export type WebsiteProtocol = ClosedEnum<typeof WebsiteProtocol>;

/** @internal */
export const WebsiteProtocol$inboundSchema: z.ZodNativeEnum<
  typeof WebsiteProtocol
> = z.nativeEnum(WebsiteProtocol);

/** @internal */
export const WebsiteProtocol$outboundSchema: z.ZodNativeEnum<
  typeof WebsiteProtocol
> = WebsiteProtocol$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WebsiteProtocol$ {
  /** @deprecated use `WebsiteProtocol$inboundSchema` instead. */
  export const inboundSchema = WebsiteProtocol$inboundSchema;
  /** @deprecated use `WebsiteProtocol$outboundSchema` instead. */
  export const outboundSchema = WebsiteProtocol$outboundSchema;
}
