/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteWebsiteRequest = {
  /**
   * Entity ID.
   */
  entityId: string;
};

/** @internal */
export type DeleteWebsiteRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const DeleteWebsiteRequest$outboundSchema: z.ZodType<
  DeleteWebsiteRequest$Outbound,
  z.ZodTypeDef,
  DeleteWebsiteRequest
> = z.object({
  entityId: z.string(),
});

export function deleteWebsiteRequestToJSON(
  deleteWebsiteRequest: DeleteWebsiteRequest,
): string {
  return JSON.stringify(
    DeleteWebsiteRequest$outboundSchema.parse(deleteWebsiteRequest),
  );
}
