/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetEntityByIdRequest = {
  /**
   * The entity's ID
   */
  id: string;
};

/** @internal */
export const GetEntityByIdRequest$inboundSchema: z.ZodType<
  GetEntityByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetEntityByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetEntityByIdRequest$outboundSchema: z.ZodType<
  GetEntityByIdRequest$Outbound,
  z.ZodTypeDef,
  GetEntityByIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetEntityByIdRequest$ {
  /** @deprecated use `GetEntityByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetEntityByIdRequest$inboundSchema;
  /** @deprecated use `GetEntityByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetEntityByIdRequest$outboundSchema;
  /** @deprecated use `GetEntityByIdRequest$Outbound` instead. */
  export type Outbound = GetEntityByIdRequest$Outbound;
}

export function getEntityByIdRequestToJSON(
  getEntityByIdRequest: GetEntityByIdRequest,
): string {
  return JSON.stringify(
    GetEntityByIdRequest$outboundSchema.parse(getEntityByIdRequest),
  );
}

export function getEntityByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetEntityByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEntityByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEntityByIdRequest' from JSON`,
  );
}
