/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPluginsRequest = {
  entityId: string;
};

/** @internal */
export const GetPluginsRequest$inboundSchema: z.ZodType<
  GetPluginsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityId: z.string(),
});
/** @internal */
export type GetPluginsRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const GetPluginsRequest$outboundSchema: z.ZodType<
  GetPluginsRequest$Outbound,
  z.ZodTypeDef,
  GetPluginsRequest
> = z.object({
  entityId: z.string(),
});

export function getPluginsRequestToJSON(
  getPluginsRequest: GetPluginsRequest,
): string {
  return JSON.stringify(
    GetPluginsRequest$outboundSchema.parse(getPluginsRequest),
  );
}
export function getPluginsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPluginsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPluginsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPluginsRequest' from JSON`,
  );
}
