/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetPluginConfigRequest = {
  /**
   * Entity ID.
   */
  entityId: string;
};

/** @internal */
export type GetPluginConfigRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const GetPluginConfigRequest$outboundSchema: z.ZodType<
  GetPluginConfigRequest$Outbound,
  z.ZodTypeDef,
  GetPluginConfigRequest
> = z.object({
  entityId: z.string(),
});

export function getPluginConfigRequestToJSON(
  getPluginConfigRequest: GetPluginConfigRequest,
): string {
  return JSON.stringify(
    GetPluginConfigRequest$outboundSchema.parse(getPluginConfigRequest),
  );
}
