/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUriRequest = {
  entityId: string;
};

export const GetUriStatus = {
  Up: "up",
  Down: "down",
  Paused: "paused",
  Maintenance: "maintenance",
  Unknown: "unknown",
} as const;
export type GetUriStatus = ClosedEnum<typeof GetUriStatus>;

/**
 * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, no particular cloud platform will be enforced.
 */
export type GetUriPlatformOptions = {
  /**
   * Cloud platforms hosting synthetic probes.
   */
  probePlatforms: Array<components.ProbePlatform>;
  /**
   *   Use this field to configure whether availability tests should be performed from all selected
   *
   * @remarks
   *   platforms or one randomly selected platform. It has no effect if you provided only one platform
   *   in the `probePlatforms` field.
   *
   *   If set to true, a separate test is made from each of the selected platforms.
   *
   *   If set to false, only one of the selected platforms is chosen every time.
   *
   *   If omitted, the previous setting will stay in effect. If there is no previous setting, the value
   *   will default to false.
   */
  testFromAll?: boolean | undefined;
};

/**
 * How many locations must report a failure for an entity to be considered down.
 */
export const GetUriFailingTestLocations = {
  All: "all",
  Any: "any",
} as const;
/**
 * How many locations must report a failure for an entity to be considered down.
 */
export type GetUriFailingTestLocations = ClosedEnum<
  typeof GetUriFailingTestLocations
>;

/**
 *   Default conditions when the entity is considered down.
 *
 * @remarks
 *   If omitted or set to null, organization configuration will be used for this entity.
 */
export type GetUriOutageConfiguration = {
  /**
   * How many locations must report a failure for an entity to be considered down.
   */
  failingTestLocations: GetUriFailingTestLocations;
  /**
   * Number of consecutive failing tests for an entity to be considered down.
   */
  consecutiveForDown: number;
};

/**
 *   Use this field to configure ping tests for the URI. If omitted or set to null, ping tests will be disabled.
 *
 * @remarks
 *   One test type (ping or TCP) must be enabled for a URI.
 */
export type Ping = {
  /**
   * Use this field to configure ping tests for the URI. If omitted or set to false, ping tests will be disabled.
   *
   * @remarks
   * One test type (ping or TCP) must be enabled for a URI.
   */
  enabled: boolean;
};

/**
 *   Use this field to configure TCP tests for the URI. If omitted or set to null, TCP tests will be disabled.
 *
 * @remarks
 *   One test type (ping or TCP) must be enabled for a URI.
 */
export type Tcp = {
  /**
   * Use this field to configure TCP tests for the URI. If omitted or set to false, TCP tests will be disabled.
   *
   * @remarks
   * One test type (ping or TCP) must be enabled for a URI.
   */
  enabled: boolean;
  /**
   * Port number to be used in TCP tests.
   */
  port: number;
  /**
   * Use this field to specify a string to send in the body of a TCP request.
   */
  stringToSend?: string | null | undefined;
  /**
   * Use this field to specify a string to search for in the body of a TCP response.
   */
  stringToExpect?: string | null | undefined;
};

/**
 * Protocol used to test availability of the URI.
 */
export const Protocol = {
  Ping: "PING",
  Tcp: "TCP",
} as const;
/**
 * Protocol used to test availability of the URI.
 */
export type Protocol = ClosedEnum<typeof Protocol>;

/**
 * Availability tests configuration for the URI.
 */
export type GetUriAvailabilityCheckSettings = {
  /**
   * Configure cloud platforms of the synthetic availability test probes. If omitted or set to null, no particular cloud platform will be enforced.
   */
  platformOptions?: GetUriPlatformOptions | null | undefined;
  /**
   *   Configure locations of the synthetic availability test probes.
   *
   * @remarks
   *   Acceptable values depend on the selected type and actual values of existing probes.
   */
  testFrom: components.TestFrom;
  /**
   * Configure how often availability tests should be performed. Provide a number of seconds that is one of 60, 300, 600, 900, 1800, 3600, 7200, 14400.
   */
  testIntervalInSeconds: number;
  /**
   *   Default conditions when the entity is considered down.
   *
   * @remarks
   *   If omitted or set to null, organization configuration will be used for this entity.
   */
  outageConfiguration?: GetUriOutageConfiguration | null | undefined;
  /**
   *   Use this field to configure ping tests for the URI. If omitted or set to null, ping tests will be disabled.
   *
   * @remarks
   *   One test type (ping or TCP) must be enabled for a URI.
   */
  ping?: Ping | null | undefined;
  /**
   *   Use this field to configure TCP tests for the URI. If omitted or set to null, TCP tests will be disabled.
   *
   * @remarks
   *   One test type (ping or TCP) must be enabled for a URI.
   */
  tcp?: Tcp | null | undefined;
  /**
   * Protocol used to test availability of the URI.
   */
  protocol: Protocol;
};

/**
 * The request has succeeded.
 */
export type GetUriResponse = {
  id: string;
  type: string;
  status: GetUriStatus;
  /**
   *   Name of the URI, which must be unique within the organization.
   *
   * @remarks
   *   The name must also not contain any control characters, any white space other than space (U+0020), or any consecutive, leading or trailing spaces.
   */
  name: string;
  /**
   * IP/domain address of the URI.
   */
  ipOrDomain: string;
  /**
   * Availability tests configuration for the URI.
   */
  availabilityCheckSettings: GetUriAvailabilityCheckSettings;
  /**
   * Entity tags. Tag is a key-value pair, where there may be only single tag value for the same key.
   */
  tags?: Array<components.Tag> | undefined;
  /**
   * Time when the last outage started.
   */
  lastOutageStartTime?: Date | null | undefined;
  /**
   * Time when the last outage ended.
   */
  lastOutageEndTime?: Date | null | undefined;
  /**
   * Time when the last test was performed.
   */
  lastTestTime?: Date | null | undefined;
  /**
   * Last time when a synthetic test failed.
   */
  lastErrorTime?: Date | null | undefined;
  /**
   * Response time from the last synthetic check in milliseconds.
   */
  lastResponseTime?: number | null | undefined;
};

/** @internal */
export const GetUriRequest$inboundSchema: z.ZodType<
  GetUriRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityId: z.string(),
});

/** @internal */
export type GetUriRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const GetUriRequest$outboundSchema: z.ZodType<
  GetUriRequest$Outbound,
  z.ZodTypeDef,
  GetUriRequest
> = z.object({
  entityId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUriRequest$ {
  /** @deprecated use `GetUriRequest$inboundSchema` instead. */
  export const inboundSchema = GetUriRequest$inboundSchema;
  /** @deprecated use `GetUriRequest$outboundSchema` instead. */
  export const outboundSchema = GetUriRequest$outboundSchema;
  /** @deprecated use `GetUriRequest$Outbound` instead. */
  export type Outbound = GetUriRequest$Outbound;
}

export function getUriRequestToJSON(getUriRequest: GetUriRequest): string {
  return JSON.stringify(GetUriRequest$outboundSchema.parse(getUriRequest));
}

export function getUriRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetUriRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUriRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUriRequest' from JSON`,
  );
}

/** @internal */
export const GetUriStatus$inboundSchema: z.ZodNativeEnum<typeof GetUriStatus> =
  z.nativeEnum(GetUriStatus);

/** @internal */
export const GetUriStatus$outboundSchema: z.ZodNativeEnum<typeof GetUriStatus> =
  GetUriStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUriStatus$ {
  /** @deprecated use `GetUriStatus$inboundSchema` instead. */
  export const inboundSchema = GetUriStatus$inboundSchema;
  /** @deprecated use `GetUriStatus$outboundSchema` instead. */
  export const outboundSchema = GetUriStatus$outboundSchema;
}

/** @internal */
export const GetUriPlatformOptions$inboundSchema: z.ZodType<
  GetUriPlatformOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  probePlatforms: z.array(components.ProbePlatform$inboundSchema),
  testFromAll: z.boolean().optional(),
});

/** @internal */
export type GetUriPlatformOptions$Outbound = {
  probePlatforms: Array<string>;
  testFromAll?: boolean | undefined;
};

/** @internal */
export const GetUriPlatformOptions$outboundSchema: z.ZodType<
  GetUriPlatformOptions$Outbound,
  z.ZodTypeDef,
  GetUriPlatformOptions
> = z.object({
  probePlatforms: z.array(components.ProbePlatform$outboundSchema),
  testFromAll: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUriPlatformOptions$ {
  /** @deprecated use `GetUriPlatformOptions$inboundSchema` instead. */
  export const inboundSchema = GetUriPlatformOptions$inboundSchema;
  /** @deprecated use `GetUriPlatformOptions$outboundSchema` instead. */
  export const outboundSchema = GetUriPlatformOptions$outboundSchema;
  /** @deprecated use `GetUriPlatformOptions$Outbound` instead. */
  export type Outbound = GetUriPlatformOptions$Outbound;
}

export function getUriPlatformOptionsToJSON(
  getUriPlatformOptions: GetUriPlatformOptions,
): string {
  return JSON.stringify(
    GetUriPlatformOptions$outboundSchema.parse(getUriPlatformOptions),
  );
}

export function getUriPlatformOptionsFromJSON(
  jsonString: string,
): SafeParseResult<GetUriPlatformOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUriPlatformOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUriPlatformOptions' from JSON`,
  );
}

/** @internal */
export const GetUriFailingTestLocations$inboundSchema: z.ZodNativeEnum<
  typeof GetUriFailingTestLocations
> = z.nativeEnum(GetUriFailingTestLocations);

/** @internal */
export const GetUriFailingTestLocations$outboundSchema: z.ZodNativeEnum<
  typeof GetUriFailingTestLocations
> = GetUriFailingTestLocations$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUriFailingTestLocations$ {
  /** @deprecated use `GetUriFailingTestLocations$inboundSchema` instead. */
  export const inboundSchema = GetUriFailingTestLocations$inboundSchema;
  /** @deprecated use `GetUriFailingTestLocations$outboundSchema` instead. */
  export const outboundSchema = GetUriFailingTestLocations$outboundSchema;
}

/** @internal */
export const GetUriOutageConfiguration$inboundSchema: z.ZodType<
  GetUriOutageConfiguration,
  z.ZodTypeDef,
  unknown
> = z.object({
  failingTestLocations: GetUriFailingTestLocations$inboundSchema,
  consecutiveForDown: z.number().int(),
});

/** @internal */
export type GetUriOutageConfiguration$Outbound = {
  failingTestLocations: string;
  consecutiveForDown: number;
};

/** @internal */
export const GetUriOutageConfiguration$outboundSchema: z.ZodType<
  GetUriOutageConfiguration$Outbound,
  z.ZodTypeDef,
  GetUriOutageConfiguration
> = z.object({
  failingTestLocations: GetUriFailingTestLocations$outboundSchema,
  consecutiveForDown: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUriOutageConfiguration$ {
  /** @deprecated use `GetUriOutageConfiguration$inboundSchema` instead. */
  export const inboundSchema = GetUriOutageConfiguration$inboundSchema;
  /** @deprecated use `GetUriOutageConfiguration$outboundSchema` instead. */
  export const outboundSchema = GetUriOutageConfiguration$outboundSchema;
  /** @deprecated use `GetUriOutageConfiguration$Outbound` instead. */
  export type Outbound = GetUriOutageConfiguration$Outbound;
}

export function getUriOutageConfigurationToJSON(
  getUriOutageConfiguration: GetUriOutageConfiguration,
): string {
  return JSON.stringify(
    GetUriOutageConfiguration$outboundSchema.parse(getUriOutageConfiguration),
  );
}

export function getUriOutageConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<GetUriOutageConfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUriOutageConfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUriOutageConfiguration' from JSON`,
  );
}

/** @internal */
export const Ping$inboundSchema: z.ZodType<Ping, z.ZodTypeDef, unknown> = z
  .object({
    enabled: z.boolean(),
  });

/** @internal */
export type Ping$Outbound = {
  enabled: boolean;
};

/** @internal */
export const Ping$outboundSchema: z.ZodType<Ping$Outbound, z.ZodTypeDef, Ping> =
  z.object({
    enabled: z.boolean(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Ping$ {
  /** @deprecated use `Ping$inboundSchema` instead. */
  export const inboundSchema = Ping$inboundSchema;
  /** @deprecated use `Ping$outboundSchema` instead. */
  export const outboundSchema = Ping$outboundSchema;
  /** @deprecated use `Ping$Outbound` instead. */
  export type Outbound = Ping$Outbound;
}

export function pingToJSON(ping: Ping): string {
  return JSON.stringify(Ping$outboundSchema.parse(ping));
}

export function pingFromJSON(
  jsonString: string,
): SafeParseResult<Ping, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ping$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ping' from JSON`,
  );
}

/** @internal */
export const Tcp$inboundSchema: z.ZodType<Tcp, z.ZodTypeDef, unknown> = z
  .object({
    enabled: z.boolean(),
    port: z.number().int(),
    stringToSend: z.nullable(z.string()).optional(),
    stringToExpect: z.nullable(z.string()).optional(),
  });

/** @internal */
export type Tcp$Outbound = {
  enabled: boolean;
  port: number;
  stringToSend?: string | null | undefined;
  stringToExpect?: string | null | undefined;
};

/** @internal */
export const Tcp$outboundSchema: z.ZodType<Tcp$Outbound, z.ZodTypeDef, Tcp> = z
  .object({
    enabled: z.boolean(),
    port: z.number().int(),
    stringToSend: z.nullable(z.string()).optional(),
    stringToExpect: z.nullable(z.string()).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Tcp$ {
  /** @deprecated use `Tcp$inboundSchema` instead. */
  export const inboundSchema = Tcp$inboundSchema;
  /** @deprecated use `Tcp$outboundSchema` instead. */
  export const outboundSchema = Tcp$outboundSchema;
  /** @deprecated use `Tcp$Outbound` instead. */
  export type Outbound = Tcp$Outbound;
}

export function tcpToJSON(tcp: Tcp): string {
  return JSON.stringify(Tcp$outboundSchema.parse(tcp));
}

export function tcpFromJSON(
  jsonString: string,
): SafeParseResult<Tcp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tcp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tcp' from JSON`,
  );
}

/** @internal */
export const Protocol$inboundSchema: z.ZodNativeEnum<typeof Protocol> = z
  .nativeEnum(Protocol);

/** @internal */
export const Protocol$outboundSchema: z.ZodNativeEnum<typeof Protocol> =
  Protocol$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Protocol$ {
  /** @deprecated use `Protocol$inboundSchema` instead. */
  export const inboundSchema = Protocol$inboundSchema;
  /** @deprecated use `Protocol$outboundSchema` instead. */
  export const outboundSchema = Protocol$outboundSchema;
}

/** @internal */
export const GetUriAvailabilityCheckSettings$inboundSchema: z.ZodType<
  GetUriAvailabilityCheckSettings,
  z.ZodTypeDef,
  unknown
> = z.object({
  platformOptions: z.nullable(z.lazy(() => GetUriPlatformOptions$inboundSchema))
    .optional(),
  testFrom: components.TestFrom$inboundSchema,
  testIntervalInSeconds: z.number(),
  outageConfiguration: z.nullable(
    z.lazy(() => GetUriOutageConfiguration$inboundSchema),
  ).optional(),
  ping: z.nullable(z.lazy(() => Ping$inboundSchema)).optional(),
  tcp: z.nullable(z.lazy(() => Tcp$inboundSchema)).optional(),
  protocol: Protocol$inboundSchema,
});

/** @internal */
export type GetUriAvailabilityCheckSettings$Outbound = {
  platformOptions?: GetUriPlatformOptions$Outbound | null | undefined;
  testFrom: components.TestFrom$Outbound;
  testIntervalInSeconds: number;
  outageConfiguration?: GetUriOutageConfiguration$Outbound | null | undefined;
  ping?: Ping$Outbound | null | undefined;
  tcp?: Tcp$Outbound | null | undefined;
  protocol: string;
};

/** @internal */
export const GetUriAvailabilityCheckSettings$outboundSchema: z.ZodType<
  GetUriAvailabilityCheckSettings$Outbound,
  z.ZodTypeDef,
  GetUriAvailabilityCheckSettings
> = z.object({
  platformOptions: z.nullable(
    z.lazy(() => GetUriPlatformOptions$outboundSchema),
  ).optional(),
  testFrom: components.TestFrom$outboundSchema,
  testIntervalInSeconds: z.number(),
  outageConfiguration: z.nullable(
    z.lazy(() => GetUriOutageConfiguration$outboundSchema),
  ).optional(),
  ping: z.nullable(z.lazy(() => Ping$outboundSchema)).optional(),
  tcp: z.nullable(z.lazy(() => Tcp$outboundSchema)).optional(),
  protocol: Protocol$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUriAvailabilityCheckSettings$ {
  /** @deprecated use `GetUriAvailabilityCheckSettings$inboundSchema` instead. */
  export const inboundSchema = GetUriAvailabilityCheckSettings$inboundSchema;
  /** @deprecated use `GetUriAvailabilityCheckSettings$outboundSchema` instead. */
  export const outboundSchema = GetUriAvailabilityCheckSettings$outboundSchema;
  /** @deprecated use `GetUriAvailabilityCheckSettings$Outbound` instead. */
  export type Outbound = GetUriAvailabilityCheckSettings$Outbound;
}

export function getUriAvailabilityCheckSettingsToJSON(
  getUriAvailabilityCheckSettings: GetUriAvailabilityCheckSettings,
): string {
  return JSON.stringify(
    GetUriAvailabilityCheckSettings$outboundSchema.parse(
      getUriAvailabilityCheckSettings,
    ),
  );
}

export function getUriAvailabilityCheckSettingsFromJSON(
  jsonString: string,
): SafeParseResult<GetUriAvailabilityCheckSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUriAvailabilityCheckSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUriAvailabilityCheckSettings' from JSON`,
  );
}

/** @internal */
export const GetUriResponse$inboundSchema: z.ZodType<
  GetUriResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.string(),
  status: GetUriStatus$inboundSchema,
  name: z.string(),
  ipOrDomain: z.string(),
  availabilityCheckSettings: z.lazy(() =>
    GetUriAvailabilityCheckSettings$inboundSchema
  ),
  tags: z.array(components.Tag$inboundSchema).optional(),
  lastOutageStartTime: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  lastOutageEndTime: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  lastTestTime: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  lastErrorTime: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  lastResponseTime: z.nullable(z.number().int()).optional(),
});

/** @internal */
export type GetUriResponse$Outbound = {
  id: string;
  type: string;
  status: string;
  name: string;
  ipOrDomain: string;
  availabilityCheckSettings: GetUriAvailabilityCheckSettings$Outbound;
  tags?: Array<components.Tag$Outbound> | undefined;
  lastOutageStartTime?: string | null | undefined;
  lastOutageEndTime?: string | null | undefined;
  lastTestTime?: string | null | undefined;
  lastErrorTime?: string | null | undefined;
  lastResponseTime?: number | null | undefined;
};

/** @internal */
export const GetUriResponse$outboundSchema: z.ZodType<
  GetUriResponse$Outbound,
  z.ZodTypeDef,
  GetUriResponse
> = z.object({
  id: z.string(),
  type: z.string(),
  status: GetUriStatus$outboundSchema,
  name: z.string(),
  ipOrDomain: z.string(),
  availabilityCheckSettings: z.lazy(() =>
    GetUriAvailabilityCheckSettings$outboundSchema
  ),
  tags: z.array(components.Tag$outboundSchema).optional(),
  lastOutageStartTime: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  lastOutageEndTime: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  lastTestTime: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  lastErrorTime: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  lastResponseTime: z.nullable(z.number().int()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUriResponse$ {
  /** @deprecated use `GetUriResponse$inboundSchema` instead. */
  export const inboundSchema = GetUriResponse$inboundSchema;
  /** @deprecated use `GetUriResponse$outboundSchema` instead. */
  export const outboundSchema = GetUriResponse$outboundSchema;
  /** @deprecated use `GetUriResponse$Outbound` instead. */
  export type Outbound = GetUriResponse$Outbound;
}

export function getUriResponseToJSON(getUriResponse: GetUriResponse): string {
  return JSON.stringify(GetUriResponse$outboundSchema.parse(getUriResponse));
}

export function getUriResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUriResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUriResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUriResponse' from JSON`,
  );
}
