/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetWebsiteRequest = {
  entityId: string;
};

/** @internal */
export const GetWebsiteRequest$inboundSchema: z.ZodType<
  GetWebsiteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityId: z.string(),
});
/** @internal */
export type GetWebsiteRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const GetWebsiteRequest$outboundSchema: z.ZodType<
  GetWebsiteRequest$Outbound,
  z.ZodTypeDef,
  GetWebsiteRequest
> = z.object({
  entityId: z.string(),
});

export function getWebsiteRequestToJSON(
  getWebsiteRequest: GetWebsiteRequest,
): string {
  return JSON.stringify(
    GetWebsiteRequest$outboundSchema.parse(getWebsiteRequest),
  );
}
export function getWebsiteRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetWebsiteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebsiteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebsiteRequest' from JSON`,
  );
}
