/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListMultiMetricMeasurementsRequestBody = {
  metrics: Array<components.MetricsMeasurementsRequest>;
  /**
   * Timestamp in ISO 8601 format in UTC timezone: yyyy-MM-ddTHH:mm:ssZ
   */
  startTime?: Date | undefined;
  /**
   * Timestamp in ISO 8601 format in UTC timezone: yyyy-MM-ddTHH:mm:ssZ
   */
  endTime?: Date | undefined;
};

export type ListMultiMetricMeasurementsRequest = {
  /**
   * Forces a positional response; see the operation description.
   */
  forcePositional?: boolean | undefined;
  /**
   * Number of items in a response page. Default varies by API.
   */
  pageSize?: number | undefined;
  /**
   * Token for the requested page.
   */
  skipToken?: string | undefined;
  requestBody: ListMultiMetricMeasurementsRequestBody;
};

export type Metric = {
  /**
   * Entry identification, as (if) provided in the corresponding request entry.
   */
  id?: string | undefined;
  /**
   * Metric name.
   */
  name: string;
  /**
   * Collection of attributes and measurements.
   */
  groupings: Array<components.MetricsGrouping>;
  /**
   * Bucket size used for computing points in this entry.
   */
  bucketSizeInSeconds: number;
};

/**
 * The request has succeeded.
 */
export type ListMultiMetricMeasurementsResponseBody = {
  metrics: Array<Metric>;
  pageInfo: components.CommonPageInfo;
};

export type ListMultiMetricMeasurementsResponse = {
  result: ListMultiMetricMeasurementsResponseBody;
};

/** @internal */
export const ListMultiMetricMeasurementsRequestBody$inboundSchema: z.ZodType<
  ListMultiMetricMeasurementsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  metrics: z.array(components.MetricsMeasurementsRequest$inboundSchema),
  startTime: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  endTime: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
});
/** @internal */
export type ListMultiMetricMeasurementsRequestBody$Outbound = {
  metrics: Array<components.MetricsMeasurementsRequest$Outbound>;
  startTime?: string | undefined;
  endTime?: string | undefined;
};

/** @internal */
export const ListMultiMetricMeasurementsRequestBody$outboundSchema: z.ZodType<
  ListMultiMetricMeasurementsRequestBody$Outbound,
  z.ZodTypeDef,
  ListMultiMetricMeasurementsRequestBody
> = z.object({
  metrics: z.array(components.MetricsMeasurementsRequest$outboundSchema),
  startTime: z.date().transform(v => v.toISOString()).optional(),
  endTime: z.date().transform(v => v.toISOString()).optional(),
});

export function listMultiMetricMeasurementsRequestBodyToJSON(
  listMultiMetricMeasurementsRequestBody:
    ListMultiMetricMeasurementsRequestBody,
): string {
  return JSON.stringify(
    ListMultiMetricMeasurementsRequestBody$outboundSchema.parse(
      listMultiMetricMeasurementsRequestBody,
    ),
  );
}
export function listMultiMetricMeasurementsRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListMultiMetricMeasurementsRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListMultiMetricMeasurementsRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMultiMetricMeasurementsRequestBody' from JSON`,
  );
}

/** @internal */
export const ListMultiMetricMeasurementsRequest$inboundSchema: z.ZodType<
  ListMultiMetricMeasurementsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  forcePositional: z.boolean().default(false),
  pageSize: z.number().int().optional(),
  skipToken: z.string().optional(),
  RequestBody: z.lazy(() =>
    ListMultiMetricMeasurementsRequestBody$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type ListMultiMetricMeasurementsRequest$Outbound = {
  forcePositional: boolean;
  pageSize?: number | undefined;
  skipToken?: string | undefined;
  RequestBody: ListMultiMetricMeasurementsRequestBody$Outbound;
};

/** @internal */
export const ListMultiMetricMeasurementsRequest$outboundSchema: z.ZodType<
  ListMultiMetricMeasurementsRequest$Outbound,
  z.ZodTypeDef,
  ListMultiMetricMeasurementsRequest
> = z.object({
  forcePositional: z.boolean().default(false),
  pageSize: z.number().int().optional(),
  skipToken: z.string().optional(),
  requestBody: z.lazy(() =>
    ListMultiMetricMeasurementsRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function listMultiMetricMeasurementsRequestToJSON(
  listMultiMetricMeasurementsRequest: ListMultiMetricMeasurementsRequest,
): string {
  return JSON.stringify(
    ListMultiMetricMeasurementsRequest$outboundSchema.parse(
      listMultiMetricMeasurementsRequest,
    ),
  );
}
export function listMultiMetricMeasurementsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListMultiMetricMeasurementsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListMultiMetricMeasurementsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMultiMetricMeasurementsRequest' from JSON`,
  );
}

/** @internal */
export const Metric$inboundSchema: z.ZodType<Metric, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    name: z.string(),
    groupings: z.array(components.MetricsGrouping$inboundSchema),
    bucketSizeInSeconds: z.number().int(),
  });
/** @internal */
export type Metric$Outbound = {
  id?: string | undefined;
  name: string;
  groupings: Array<components.MetricsGrouping$Outbound>;
  bucketSizeInSeconds: number;
};

/** @internal */
export const Metric$outboundSchema: z.ZodType<
  Metric$Outbound,
  z.ZodTypeDef,
  Metric
> = z.object({
  id: z.string().optional(),
  name: z.string(),
  groupings: z.array(components.MetricsGrouping$outboundSchema),
  bucketSizeInSeconds: z.number().int(),
});

export function metricToJSON(metric: Metric): string {
  return JSON.stringify(Metric$outboundSchema.parse(metric));
}
export function metricFromJSON(
  jsonString: string,
): SafeParseResult<Metric, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metric$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metric' from JSON`,
  );
}

/** @internal */
export const ListMultiMetricMeasurementsResponseBody$inboundSchema: z.ZodType<
  ListMultiMetricMeasurementsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  metrics: z.array(z.lazy(() => Metric$inboundSchema)),
  pageInfo: components.CommonPageInfo$inboundSchema,
});
/** @internal */
export type ListMultiMetricMeasurementsResponseBody$Outbound = {
  metrics: Array<Metric$Outbound>;
  pageInfo: components.CommonPageInfo$Outbound;
};

/** @internal */
export const ListMultiMetricMeasurementsResponseBody$outboundSchema: z.ZodType<
  ListMultiMetricMeasurementsResponseBody$Outbound,
  z.ZodTypeDef,
  ListMultiMetricMeasurementsResponseBody
> = z.object({
  metrics: z.array(z.lazy(() => Metric$outboundSchema)),
  pageInfo: components.CommonPageInfo$outboundSchema,
});

export function listMultiMetricMeasurementsResponseBodyToJSON(
  listMultiMetricMeasurementsResponseBody:
    ListMultiMetricMeasurementsResponseBody,
): string {
  return JSON.stringify(
    ListMultiMetricMeasurementsResponseBody$outboundSchema.parse(
      listMultiMetricMeasurementsResponseBody,
    ),
  );
}
export function listMultiMetricMeasurementsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ListMultiMetricMeasurementsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListMultiMetricMeasurementsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListMultiMetricMeasurementsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListMultiMetricMeasurementsResponse$inboundSchema: z.ZodType<
  ListMultiMetricMeasurementsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => ListMultiMetricMeasurementsResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListMultiMetricMeasurementsResponse$Outbound = {
  Result: ListMultiMetricMeasurementsResponseBody$Outbound;
};

/** @internal */
export const ListMultiMetricMeasurementsResponse$outboundSchema: z.ZodType<
  ListMultiMetricMeasurementsResponse$Outbound,
  z.ZodTypeDef,
  ListMultiMetricMeasurementsResponse
> = z.object({
  result: z.lazy(() => ListMultiMetricMeasurementsResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listMultiMetricMeasurementsResponseToJSON(
  listMultiMetricMeasurementsResponse: ListMultiMetricMeasurementsResponse,
): string {
  return JSON.stringify(
    ListMultiMetricMeasurementsResponse$outboundSchema.parse(
      listMultiMetricMeasurementsResponse,
    ),
  );
}
export function listMultiMetricMeasurementsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMultiMetricMeasurementsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListMultiMetricMeasurementsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMultiMetricMeasurementsResponse' from JSON`,
  );
}
