/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListEntitiesRequest = {
  /**
   * The entity type to search for
   */
  type: string;
  /**
   * The entity name to search for
   */
  name?: string | undefined;
  /**
   * Number of items in a response page. Default varies by API.
   */
  pageSize?: number | undefined;
  /**
   * Token for the requested page.
   */
  skipToken?: string | undefined;
};

/**
 * The request has succeeded.
 */
export type ListEntitiesResponseBody = {
  /**
   * List of matching entities.
   */
  entities: Array<components.EntitiesEntity>;
  /**
   * Pagination information.
   */
  pageInfo: components.CommonPageInfo;
};

export type ListEntitiesResponse = {
  result: ListEntitiesResponseBody;
};

/** @internal */
export type ListEntitiesRequest$Outbound = {
  type: string;
  name?: string | undefined;
  pageSize?: number | undefined;
  skipToken?: string | undefined;
};

/** @internal */
export const ListEntitiesRequest$outboundSchema: z.ZodType<
  ListEntitiesRequest$Outbound,
  z.ZodTypeDef,
  ListEntitiesRequest
> = z.object({
  type: z.string(),
  name: z.string().optional(),
  pageSize: z.number().int().optional(),
  skipToken: z.string().optional(),
});

export function listEntitiesRequestToJSON(
  listEntitiesRequest: ListEntitiesRequest,
): string {
  return JSON.stringify(
    ListEntitiesRequest$outboundSchema.parse(listEntitiesRequest),
  );
}

/** @internal */
export const ListEntitiesResponseBody$inboundSchema: z.ZodType<
  ListEntitiesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  entities: z.array(components.EntitiesEntity$inboundSchema),
  pageInfo: components.CommonPageInfo$inboundSchema,
});

export function listEntitiesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListEntitiesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntitiesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntitiesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListEntitiesResponse$inboundSchema: z.ZodType<
  ListEntitiesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => ListEntitiesResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listEntitiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEntitiesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntitiesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntitiesResponse' from JSON`,
  );
}
