/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListEntitiesRequest = {
  /**
   * The entity type to search for
   */
  type: string;
  /**
   * The entity name to search for
   */
  name?: string | undefined;
  /**
   * Number of items in a response page. Default varies by API.
   */
  pageSize?: number | undefined;
  /**
   * Token for the requested page.
   */
  skipToken?: string | undefined;
};

/**
 * The request has succeeded.
 */
export type ListEntitiesResponseBody = {
  entities: Array<components.EntitiesEntity>;
  pageInfo: components.CommonPageInfo;
};

export type ListEntitiesResponse = {
  result: ListEntitiesResponseBody;
};

/** @internal */
export const ListEntitiesRequest$inboundSchema: z.ZodType<
  ListEntitiesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string(),
  name: z.string().optional(),
  pageSize: z.number().int().optional(),
  skipToken: z.string().optional(),
});

/** @internal */
export type ListEntitiesRequest$Outbound = {
  type: string;
  name?: string | undefined;
  pageSize?: number | undefined;
  skipToken?: string | undefined;
};

/** @internal */
export const ListEntitiesRequest$outboundSchema: z.ZodType<
  ListEntitiesRequest$Outbound,
  z.ZodTypeDef,
  ListEntitiesRequest
> = z.object({
  type: z.string(),
  name: z.string().optional(),
  pageSize: z.number().int().optional(),
  skipToken: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListEntitiesRequest$ {
  /** @deprecated use `ListEntitiesRequest$inboundSchema` instead. */
  export const inboundSchema = ListEntitiesRequest$inboundSchema;
  /** @deprecated use `ListEntitiesRequest$outboundSchema` instead. */
  export const outboundSchema = ListEntitiesRequest$outboundSchema;
  /** @deprecated use `ListEntitiesRequest$Outbound` instead. */
  export type Outbound = ListEntitiesRequest$Outbound;
}

export function listEntitiesRequestToJSON(
  listEntitiesRequest: ListEntitiesRequest,
): string {
  return JSON.stringify(
    ListEntitiesRequest$outboundSchema.parse(listEntitiesRequest),
  );
}

export function listEntitiesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListEntitiesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntitiesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntitiesRequest' from JSON`,
  );
}

/** @internal */
export const ListEntitiesResponseBody$inboundSchema: z.ZodType<
  ListEntitiesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  entities: z.array(components.EntitiesEntity$inboundSchema),
  pageInfo: components.CommonPageInfo$inboundSchema,
});

/** @internal */
export type ListEntitiesResponseBody$Outbound = {
  entities: Array<components.EntitiesEntity$Outbound>;
  pageInfo: components.CommonPageInfo$Outbound;
};

/** @internal */
export const ListEntitiesResponseBody$outboundSchema: z.ZodType<
  ListEntitiesResponseBody$Outbound,
  z.ZodTypeDef,
  ListEntitiesResponseBody
> = z.object({
  entities: z.array(components.EntitiesEntity$outboundSchema),
  pageInfo: components.CommonPageInfo$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListEntitiesResponseBody$ {
  /** @deprecated use `ListEntitiesResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListEntitiesResponseBody$inboundSchema;
  /** @deprecated use `ListEntitiesResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListEntitiesResponseBody$outboundSchema;
  /** @deprecated use `ListEntitiesResponseBody$Outbound` instead. */
  export type Outbound = ListEntitiesResponseBody$Outbound;
}

export function listEntitiesResponseBodyToJSON(
  listEntitiesResponseBody: ListEntitiesResponseBody,
): string {
  return JSON.stringify(
    ListEntitiesResponseBody$outboundSchema.parse(listEntitiesResponseBody),
  );
}

export function listEntitiesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListEntitiesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntitiesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntitiesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListEntitiesResponse$inboundSchema: z.ZodType<
  ListEntitiesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => ListEntitiesResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type ListEntitiesResponse$Outbound = {
  Result: ListEntitiesResponseBody$Outbound;
};

/** @internal */
export const ListEntitiesResponse$outboundSchema: z.ZodType<
  ListEntitiesResponse$Outbound,
  z.ZodTypeDef,
  ListEntitiesResponse
> = z.object({
  result: z.lazy(() => ListEntitiesResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListEntitiesResponse$ {
  /** @deprecated use `ListEntitiesResponse$inboundSchema` instead. */
  export const inboundSchema = ListEntitiesResponse$inboundSchema;
  /** @deprecated use `ListEntitiesResponse$outboundSchema` instead. */
  export const outboundSchema = ListEntitiesResponse$outboundSchema;
  /** @deprecated use `ListEntitiesResponse$Outbound` instead. */
  export type Outbound = ListEntitiesResponse$Outbound;
}

export function listEntitiesResponseToJSON(
  listEntitiesResponse: ListEntitiesResponse,
): string {
  return JSON.stringify(
    ListEntitiesResponse$outboundSchema.parse(listEntitiesResponse),
  );
}

export function listEntitiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEntitiesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntitiesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntitiesResponse' from JSON`,
  );
}
