/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListMetricAttributesRequest = {
  /**
   * metric name
   */
  name: string;
  /**
   * Timestamp in ISO 8601 format in UTC timezone: yyyy-MM-ddTHH:mm:ssZ
   */
  startTime?: Date | undefined;
  /**
   * Timestamp in ISO 8601 format in UTC timezone: yyyy-MM-ddTHH:mm:ssZ
   */
  endTime?: Date | undefined;
  /**
   * Number of items in a response page. Default varies by API.
   */
  pageSize?: number | undefined;
  /**
   * Token for the requested page.
   */
  skipToken?: string | undefined;
};

/**
 * The request has succeeded.
 */
export type ListMetricAttributesResponseBody = {
  names: Array<string>;
  pageInfo: components.CommonPageInfo;
};

export type ListMetricAttributesResponse = {
  result: ListMetricAttributesResponseBody;
};

/** @internal */
export const ListMetricAttributesRequest$inboundSchema: z.ZodType<
  ListMetricAttributesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  startTime: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  endTime: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  pageSize: z.number().int().optional(),
  skipToken: z.string().optional(),
});

/** @internal */
export type ListMetricAttributesRequest$Outbound = {
  name: string;
  startTime?: string | undefined;
  endTime?: string | undefined;
  pageSize?: number | undefined;
  skipToken?: string | undefined;
};

/** @internal */
export const ListMetricAttributesRequest$outboundSchema: z.ZodType<
  ListMetricAttributesRequest$Outbound,
  z.ZodTypeDef,
  ListMetricAttributesRequest
> = z.object({
  name: z.string(),
  startTime: z.date().transform(v => v.toISOString()).optional(),
  endTime: z.date().transform(v => v.toISOString()).optional(),
  pageSize: z.number().int().optional(),
  skipToken: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMetricAttributesRequest$ {
  /** @deprecated use `ListMetricAttributesRequest$inboundSchema` instead. */
  export const inboundSchema = ListMetricAttributesRequest$inboundSchema;
  /** @deprecated use `ListMetricAttributesRequest$outboundSchema` instead. */
  export const outboundSchema = ListMetricAttributesRequest$outboundSchema;
  /** @deprecated use `ListMetricAttributesRequest$Outbound` instead. */
  export type Outbound = ListMetricAttributesRequest$Outbound;
}

export function listMetricAttributesRequestToJSON(
  listMetricAttributesRequest: ListMetricAttributesRequest,
): string {
  return JSON.stringify(
    ListMetricAttributesRequest$outboundSchema.parse(
      listMetricAttributesRequest,
    ),
  );
}

export function listMetricAttributesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListMetricAttributesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMetricAttributesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMetricAttributesRequest' from JSON`,
  );
}

/** @internal */
export const ListMetricAttributesResponseBody$inboundSchema: z.ZodType<
  ListMetricAttributesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  names: z.array(z.string()),
  pageInfo: components.CommonPageInfo$inboundSchema,
});

/** @internal */
export type ListMetricAttributesResponseBody$Outbound = {
  names: Array<string>;
  pageInfo: components.CommonPageInfo$Outbound;
};

/** @internal */
export const ListMetricAttributesResponseBody$outboundSchema: z.ZodType<
  ListMetricAttributesResponseBody$Outbound,
  z.ZodTypeDef,
  ListMetricAttributesResponseBody
> = z.object({
  names: z.array(z.string()),
  pageInfo: components.CommonPageInfo$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMetricAttributesResponseBody$ {
  /** @deprecated use `ListMetricAttributesResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListMetricAttributesResponseBody$inboundSchema;
  /** @deprecated use `ListMetricAttributesResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListMetricAttributesResponseBody$outboundSchema;
  /** @deprecated use `ListMetricAttributesResponseBody$Outbound` instead. */
  export type Outbound = ListMetricAttributesResponseBody$Outbound;
}

export function listMetricAttributesResponseBodyToJSON(
  listMetricAttributesResponseBody: ListMetricAttributesResponseBody,
): string {
  return JSON.stringify(
    ListMetricAttributesResponseBody$outboundSchema.parse(
      listMetricAttributesResponseBody,
    ),
  );
}

export function listMetricAttributesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListMetricAttributesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMetricAttributesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMetricAttributesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListMetricAttributesResponse$inboundSchema: z.ZodType<
  ListMetricAttributesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => ListMetricAttributesResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type ListMetricAttributesResponse$Outbound = {
  Result: ListMetricAttributesResponseBody$Outbound;
};

/** @internal */
export const ListMetricAttributesResponse$outboundSchema: z.ZodType<
  ListMetricAttributesResponse$Outbound,
  z.ZodTypeDef,
  ListMetricAttributesResponse
> = z.object({
  result: z.lazy(() => ListMetricAttributesResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMetricAttributesResponse$ {
  /** @deprecated use `ListMetricAttributesResponse$inboundSchema` instead. */
  export const inboundSchema = ListMetricAttributesResponse$inboundSchema;
  /** @deprecated use `ListMetricAttributesResponse$outboundSchema` instead. */
  export const outboundSchema = ListMetricAttributesResponse$outboundSchema;
  /** @deprecated use `ListMetricAttributesResponse$Outbound` instead. */
  export type Outbound = ListMetricAttributesResponse$Outbound;
}

export function listMetricAttributesResponseToJSON(
  listMetricAttributesResponse: ListMetricAttributesResponse,
): string {
  return JSON.stringify(
    ListMetricAttributesResponse$outboundSchema.parse(
      listMetricAttributesResponse,
    ),
  );
}

export function listMetricAttributesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMetricAttributesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMetricAttributesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMetricAttributesResponse' from JSON`,
  );
}
