/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListMetricAttributeValuesRequest = {
  /**
   * Metric name.
   */
  name: string;
  /**
   * attribute name
   */
  attributeName: string;
  /**
   * Timestamp in ISO 8601 format in UTC timezone: yyyy-MM-ddTHH:mm:ssZ
   */
  startTime?: Date | undefined;
  /**
   * Timestamp in ISO 8601 format in UTC timezone: yyyy-MM-ddTHH:mm:ssZ
   */
  endTime?: Date | undefined;
  /**
   * Number of items in a response page. Default varies by API.
   */
  pageSize?: number | undefined;
  /**
   * Token for the requested page.
   */
  skipToken?: string | undefined;
};

/**
 * The request has succeeded.
 */
export type ListMetricAttributeValuesResponseBody = {
  /**
   * Attribute name.
   */
  name: string;
  /**
   * List of attribute values.
   */
  values: Array<string>;
  /**
   * Pagination information.
   */
  pageInfo: components.CommonPageInfo;
};

export type ListMetricAttributeValuesResponse = {
  result: ListMetricAttributeValuesResponseBody;
};

/** @internal */
export type ListMetricAttributeValuesRequest$Outbound = {
  name: string;
  attributeName: string;
  startTime?: string | undefined;
  endTime?: string | undefined;
  pageSize?: number | undefined;
  skipToken?: string | undefined;
};

/** @internal */
export const ListMetricAttributeValuesRequest$outboundSchema: z.ZodType<
  ListMetricAttributeValuesRequest$Outbound,
  z.ZodTypeDef,
  ListMetricAttributeValuesRequest
> = z.object({
  name: z.string(),
  attributeName: z.string(),
  startTime: z.date().transform(v => v.toISOString()).optional(),
  endTime: z.date().transform(v => v.toISOString()).optional(),
  pageSize: z.number().int().optional(),
  skipToken: z.string().optional(),
});

export function listMetricAttributeValuesRequestToJSON(
  listMetricAttributeValuesRequest: ListMetricAttributeValuesRequest,
): string {
  return JSON.stringify(
    ListMetricAttributeValuesRequest$outboundSchema.parse(
      listMetricAttributeValuesRequest,
    ),
  );
}

/** @internal */
export const ListMetricAttributeValuesResponseBody$inboundSchema: z.ZodType<
  ListMetricAttributeValuesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  values: z.array(z.string()),
  pageInfo: components.CommonPageInfo$inboundSchema,
});

export function listMetricAttributeValuesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListMetricAttributeValuesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListMetricAttributeValuesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMetricAttributeValuesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListMetricAttributeValuesResponse$inboundSchema: z.ZodType<
  ListMetricAttributeValuesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => ListMetricAttributeValuesResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listMetricAttributeValuesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMetricAttributeValuesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMetricAttributeValuesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMetricAttributeValuesResponse' from JSON`,
  );
}
