/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The request has succeeded.
 */
export type ListProbesResponse = {
  /**
   * Synthetic probes used to perform availability tests.
   */
  probes: Array<components.Probe>;
};

/** @internal */
export const ListProbesResponse$inboundSchema: z.ZodType<
  ListProbesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  probes: z.array(components.Probe$inboundSchema),
});

/** @internal */
export type ListProbesResponse$Outbound = {
  probes: Array<components.Probe$Outbound>;
};

/** @internal */
export const ListProbesResponse$outboundSchema: z.ZodType<
  ListProbesResponse$Outbound,
  z.ZodTypeDef,
  ListProbesResponse
> = z.object({
  probes: z.array(components.Probe$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListProbesResponse$ {
  /** @deprecated use `ListProbesResponse$inboundSchema` instead. */
  export const inboundSchema = ListProbesResponse$inboundSchema;
  /** @deprecated use `ListProbesResponse$outboundSchema` instead. */
  export const outboundSchema = ListProbesResponse$outboundSchema;
  /** @deprecated use `ListProbesResponse$Outbound` instead. */
  export type Outbound = ListProbesResponse$Outbound;
}

export function listProbesResponseToJSON(
  listProbesResponse: ListProbesResponse,
): string {
  return JSON.stringify(
    ListProbesResponse$outboundSchema.parse(listProbesResponse),
  );
}

export function listProbesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListProbesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProbesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProbesResponse' from JSON`,
  );
}
