/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PauseUriMonitoringRequest = {
  entityId: string;
};

/** @internal */
export const PauseUriMonitoringRequest$inboundSchema: z.ZodType<
  PauseUriMonitoringRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityId: z.string(),
});

/** @internal */
export type PauseUriMonitoringRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const PauseUriMonitoringRequest$outboundSchema: z.ZodType<
  PauseUriMonitoringRequest$Outbound,
  z.ZodTypeDef,
  PauseUriMonitoringRequest
> = z.object({
  entityId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PauseUriMonitoringRequest$ {
  /** @deprecated use `PauseUriMonitoringRequest$inboundSchema` instead. */
  export const inboundSchema = PauseUriMonitoringRequest$inboundSchema;
  /** @deprecated use `PauseUriMonitoringRequest$outboundSchema` instead. */
  export const outboundSchema = PauseUriMonitoringRequest$outboundSchema;
  /** @deprecated use `PauseUriMonitoringRequest$Outbound` instead. */
  export type Outbound = PauseUriMonitoringRequest$Outbound;
}

export function pauseUriMonitoringRequestToJSON(
  pauseUriMonitoringRequest: PauseUriMonitoringRequest,
): string {
  return JSON.stringify(
    PauseUriMonitoringRequest$outboundSchema.parse(pauseUriMonitoringRequest),
  );
}

export function pauseUriMonitoringRequestFromJSON(
  jsonString: string,
): SafeParseResult<PauseUriMonitoringRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PauseUriMonitoringRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PauseUriMonitoringRequest' from JSON`,
  );
}
