/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PauseTransactionMonitoringRequest = {
  entityId: string;
};

/** @internal */
export const PauseTransactionMonitoringRequest$inboundSchema: z.ZodType<
  PauseTransactionMonitoringRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityId: z.string(),
});
/** @internal */
export type PauseTransactionMonitoringRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const PauseTransactionMonitoringRequest$outboundSchema: z.ZodType<
  PauseTransactionMonitoringRequest$Outbound,
  z.ZodTypeDef,
  PauseTransactionMonitoringRequest
> = z.object({
  entityId: z.string(),
});

export function pauseTransactionMonitoringRequestToJSON(
  pauseTransactionMonitoringRequest: PauseTransactionMonitoringRequest,
): string {
  return JSON.stringify(
    PauseTransactionMonitoringRequest$outboundSchema.parse(
      pauseTransactionMonitoringRequest,
    ),
  );
}
export function pauseTransactionMonitoringRequestFromJSON(
  jsonString: string,
): SafeParseResult<PauseTransactionMonitoringRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PauseTransactionMonitoringRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PauseTransactionMonitoringRequest' from JSON`,
  );
}
