/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PauseWebsiteMonitoringRequest = {
  entityId: string;
};

/** @internal */
export const PauseWebsiteMonitoringRequest$inboundSchema: z.ZodType<
  PauseWebsiteMonitoringRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityId: z.string(),
});
/** @internal */
export type PauseWebsiteMonitoringRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const PauseWebsiteMonitoringRequest$outboundSchema: z.ZodType<
  PauseWebsiteMonitoringRequest$Outbound,
  z.ZodTypeDef,
  PauseWebsiteMonitoringRequest
> = z.object({
  entityId: z.string(),
});

export function pauseWebsiteMonitoringRequestToJSON(
  pauseWebsiteMonitoringRequest: PauseWebsiteMonitoringRequest,
): string {
  return JSON.stringify(
    PauseWebsiteMonitoringRequest$outboundSchema.parse(
      pauseWebsiteMonitoringRequest,
    ),
  );
}
export function pauseWebsiteMonitoringRequestFromJSON(
  jsonString: string,
): SafeParseResult<PauseWebsiteMonitoringRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PauseWebsiteMonitoringRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PauseWebsiteMonitoringRequest' from JSON`,
  );
}
