/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type UnobserveDatabaseRequest = {
  /**
   * Entity ID.
   */
  entityId: string;
};

/** @internal */
export type UnobserveDatabaseRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const UnobserveDatabaseRequest$outboundSchema: z.ZodType<
  UnobserveDatabaseRequest$Outbound,
  z.ZodTypeDef,
  UnobserveDatabaseRequest
> = z.object({
  entityId: z.string(),
});

export function unobserveDatabaseRequestToJSON(
  unobserveDatabaseRequest: UnobserveDatabaseRequest,
): string {
  return JSON.stringify(
    UnobserveDatabaseRequest$outboundSchema.parse(unobserveDatabaseRequest),
  );
}
