/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UnpauseWebsiteMonitoringRequest = {
  entityId: string;
};

/** @internal */
export const UnpauseWebsiteMonitoringRequest$inboundSchema: z.ZodType<
  UnpauseWebsiteMonitoringRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityId: z.string(),
});

/** @internal */
export type UnpauseWebsiteMonitoringRequest$Outbound = {
  entityId: string;
};

/** @internal */
export const UnpauseWebsiteMonitoringRequest$outboundSchema: z.ZodType<
  UnpauseWebsiteMonitoringRequest$Outbound,
  z.ZodTypeDef,
  UnpauseWebsiteMonitoringRequest
> = z.object({
  entityId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnpauseWebsiteMonitoringRequest$ {
  /** @deprecated use `UnpauseWebsiteMonitoringRequest$inboundSchema` instead. */
  export const inboundSchema = UnpauseWebsiteMonitoringRequest$inboundSchema;
  /** @deprecated use `UnpauseWebsiteMonitoringRequest$outboundSchema` instead. */
  export const outboundSchema = UnpauseWebsiteMonitoringRequest$outboundSchema;
  /** @deprecated use `UnpauseWebsiteMonitoringRequest$Outbound` instead. */
  export type Outbound = UnpauseWebsiteMonitoringRequest$Outbound;
}

export function unpauseWebsiteMonitoringRequestToJSON(
  unpauseWebsiteMonitoringRequest: UnpauseWebsiteMonitoringRequest,
): string {
  return JSON.stringify(
    UnpauseWebsiteMonitoringRequest$outboundSchema.parse(
      unpauseWebsiteMonitoringRequest,
    ),
  );
}

export function unpauseWebsiteMonitoringRequestFromJSON(
  jsonString: string,
): SafeParseResult<UnpauseWebsiteMonitoringRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnpauseWebsiteMonitoringRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnpauseWebsiteMonitoringRequest' from JSON`,
  );
}
