/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateUriRequest = {
  entityId: string;
  /**
   * The updated URI monitoring configuration
   */
  demUri: components.DemUri;
};

/** @internal */
export const UpdateUriRequest$inboundSchema: z.ZodType<
  UpdateUriRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityId: z.string(),
  "Dem.Uri": components.DemUri$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Dem.Uri": "demUri",
  });
});
/** @internal */
export type UpdateUriRequest$Outbound = {
  entityId: string;
  "Dem.Uri": components.DemUri$Outbound;
};

/** @internal */
export const UpdateUriRequest$outboundSchema: z.ZodType<
  UpdateUriRequest$Outbound,
  z.ZodTypeDef,
  UpdateUriRequest
> = z.object({
  entityId: z.string(),
  demUri: components.DemUri$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    demUri: "Dem.Uri",
  });
});

export function updateUriRequestToJSON(
  updateUriRequest: UpdateUriRequest,
): string {
  return JSON.stringify(
    UpdateUriRequest$outboundSchema.parse(updateUriRequest),
  );
}
export function updateUriRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUriRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateUriRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUriRequest' from JSON`,
  );
}
