/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateUriRequest = {
  /**
   * Entity ID.
   */
  entityId: string;
  /**
   * The updated URI monitoring configuration
   */
  demUri: components.DemUri;
};

/** @internal */
export type UpdateUriRequest$Outbound = {
  entityId: string;
  "Dem.Uri": components.DemUri$Outbound;
};

/** @internal */
export const UpdateUriRequest$outboundSchema: z.ZodType<
  UpdateUriRequest$Outbound,
  z.ZodTypeDef,
  UpdateUriRequest
> = z.object({
  entityId: z.string(),
  demUri: components.DemUri$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    demUri: "Dem.Uri",
  });
});

export function updateUriRequestToJSON(
  updateUriRequest: UpdateUriRequest,
): string {
  return JSON.stringify(
    UpdateUriRequest$outboundSchema.parse(updateUriRequest),
  );
}
