/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateDatabaseRequest = {
  entityId: string;
  dboUpdateDatabaseRequest: components.DboUpdateDatabaseRequest;
};

/** @internal */
export const UpdateDatabaseRequest$inboundSchema: z.ZodType<
  UpdateDatabaseRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityId: z.string(),
  "Dbo.UpdateDatabaseRequest":
    components.DboUpdateDatabaseRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Dbo.UpdateDatabaseRequest": "dboUpdateDatabaseRequest",
  });
});
/** @internal */
export type UpdateDatabaseRequest$Outbound = {
  entityId: string;
  "Dbo.UpdateDatabaseRequest": components.DboUpdateDatabaseRequest$Outbound;
};

/** @internal */
export const UpdateDatabaseRequest$outboundSchema: z.ZodType<
  UpdateDatabaseRequest$Outbound,
  z.ZodTypeDef,
  UpdateDatabaseRequest
> = z.object({
  entityId: z.string(),
  dboUpdateDatabaseRequest: components.DboUpdateDatabaseRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dboUpdateDatabaseRequest: "Dbo.UpdateDatabaseRequest",
  });
});

export function updateDatabaseRequestToJSON(
  updateDatabaseRequest: UpdateDatabaseRequest,
): string {
  return JSON.stringify(
    UpdateDatabaseRequest$outboundSchema.parse(updateDatabaseRequest),
  );
}
export function updateDatabaseRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDatabaseRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDatabaseRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDatabaseRequest' from JSON`,
  );
}
