/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateCompositeMetricRequest = {
  /**
   * The metric name
   */
  name: string;
  /**
   * Metric properties to update
   */
  metricsUpdateCompositeMetricRequest:
    components.MetricsUpdateCompositeMetricRequest;
};

/** @internal */
export const UpdateCompositeMetricRequest$inboundSchema: z.ZodType<
  UpdateCompositeMetricRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  "Metrics.UpdateCompositeMetricRequest":
    components.MetricsUpdateCompositeMetricRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Metrics.UpdateCompositeMetricRequest":
      "metricsUpdateCompositeMetricRequest",
  });
});

/** @internal */
export type UpdateCompositeMetricRequest$Outbound = {
  name: string;
  "Metrics.UpdateCompositeMetricRequest":
    components.MetricsUpdateCompositeMetricRequest$Outbound;
};

/** @internal */
export const UpdateCompositeMetricRequest$outboundSchema: z.ZodType<
  UpdateCompositeMetricRequest$Outbound,
  z.ZodTypeDef,
  UpdateCompositeMetricRequest
> = z.object({
  name: z.string(),
  metricsUpdateCompositeMetricRequest:
    components.MetricsUpdateCompositeMetricRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    metricsUpdateCompositeMetricRequest: "Metrics.UpdateCompositeMetricRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCompositeMetricRequest$ {
  /** @deprecated use `UpdateCompositeMetricRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateCompositeMetricRequest$inboundSchema;
  /** @deprecated use `UpdateCompositeMetricRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateCompositeMetricRequest$outboundSchema;
  /** @deprecated use `UpdateCompositeMetricRequest$Outbound` instead. */
  export type Outbound = UpdateCompositeMetricRequest$Outbound;
}

export function updateCompositeMetricRequestToJSON(
  updateCompositeMetricRequest: UpdateCompositeMetricRequest,
): string {
  return JSON.stringify(
    UpdateCompositeMetricRequest$outboundSchema.parse(
      updateCompositeMetricRequest,
    ),
  );
}

export function updateCompositeMetricRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCompositeMetricRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCompositeMetricRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCompositeMetricRequest' from JSON`,
  );
}
