/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateEntityByIdRequest = {
  /**
   * The entity's ID
   */
  id: string;
  /**
   * Entity properties to update. The entire representation of the entity as to be stored must be provided in the request.
   */
  entitiesEntity: components.EntitiesEntityInput;
};

/** @internal */
export const UpdateEntityByIdRequest$inboundSchema: z.ZodType<
  UpdateEntityByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  "Entities.Entity": components.EntitiesEntityInput$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Entities.Entity": "entitiesEntity",
  });
});

/** @internal */
export type UpdateEntityByIdRequest$Outbound = {
  id: string;
  "Entities.Entity": components.EntitiesEntityInput$Outbound;
};

/** @internal */
export const UpdateEntityByIdRequest$outboundSchema: z.ZodType<
  UpdateEntityByIdRequest$Outbound,
  z.ZodTypeDef,
  UpdateEntityByIdRequest
> = z.object({
  id: z.string(),
  entitiesEntity: components.EntitiesEntityInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    entitiesEntity: "Entities.Entity",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateEntityByIdRequest$ {
  /** @deprecated use `UpdateEntityByIdRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateEntityByIdRequest$inboundSchema;
  /** @deprecated use `UpdateEntityByIdRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateEntityByIdRequest$outboundSchema;
  /** @deprecated use `UpdateEntityByIdRequest$Outbound` instead. */
  export type Outbound = UpdateEntityByIdRequest$Outbound;
}

export function updateEntityByIdRequestToJSON(
  updateEntityByIdRequest: UpdateEntityByIdRequest,
): string {
  return JSON.stringify(
    UpdateEntityByIdRequest$outboundSchema.parse(updateEntityByIdRequest),
  );
}

export function updateEntityByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEntityByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEntityByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEntityByIdRequest' from JSON`,
  );
}
