/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the @solarwinds/swo-sdk-typescript SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx changeEventsCreateChangeEvent.ts
 */

import { Swo } from "@solarwinds/swo-sdk-typescript";

const swo = new Swo({
  apiToken: process.env["SWO_API_TOKEN"] ?? "",
});

async function main() {
  const result = await swo.createChangeEvent({
    id: 1731676626,
    name: "app-deploys",
    title: "deployed v45",
    timestamp: 1731676626,
    source: "foo3.example.com",
    tags: {
      "app": "foo",
      "environment": "production",
    },
    links: [
      {
        rel: "self",
        href: "https://example.com",
      },
    ],
  });

  console.log(result);
}

main().catch(console.error);
