/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { changeEventsCreateChangeEvent } from "../funcs/changeEventsCreateChangeEvent.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ChangeEvents extends ClientSDK {
  /**
   * Create an event
   */
  async createChangeEvent(
    request: components.ChangeEventsChangeEvent,
    options?: RequestOptions,
  ): Promise<operations.CreateChangeEventResponse> {
    return unwrapAsync(changeEventsCreateChangeEvent(
      this,
      request,
      options,
    ));
  }
}
