/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cloudAccountsActivateAwsIntegration } from "../funcs/cloudAccountsActivateAwsIntegration.js";
import { cloudAccountsCreateOrgStructure } from "../funcs/cloudAccountsCreateOrgStructure.js";
import { cloudAccountsUpdateAwsIntegration } from "../funcs/cloudAccountsUpdateAwsIntegration.js";
import { cloudAccountsValidateMgmtAccountOnboarding } from "../funcs/cloudAccountsValidateMgmtAccountOnboarding.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CloudAccounts extends ClientSDK {
  /**
   * Activate AWS Integration
   *
   * @remarks
   * Activate AWS Integration.
   */
  async activateAwsIntegration(
    request: components.CloudAccountsAwsActivateIntegrationRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(cloudAccountsActivateAwsIntegration(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Organizational Structure
   *
   * @remarks
   * Create AWS Organizational Structure.
   */
  async createOrgStructure(
    request: components.CloudAccountsAwsOrganisationalUnitRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(cloudAccountsCreateOrgStructure(
      this,
      request,
      options,
    ));
  }

  /**
   * Update AWS Integration
   *
   * @remarks
   * Update AWS Integration details.
   */
  async updateAwsIntegration(
    request: components.CloudAccountsAwsUpdateIntegrationRequest,
    options?: RequestOptions,
  ): Promise<components.CloudAccountsAwsUpdateIntegrationResponse> {
    return unwrapAsync(cloudAccountsUpdateAwsIntegration(
      this,
      request,
      options,
    ));
  }

  /**
   * Validate Management Account Onboarding
   *
   * @remarks
   * Validate if the management account is onboarded.
   */
  async validateMgmtAccountOnboarding(
    request: operations.ValidateMgmtAccountOnboardingRequest,
    options?: RequestOptions,
  ): Promise<components.CloudAccountsAwsMgmtAccountOnboardingResponse> {
    return unwrapAsync(cloudAccountsValidateMgmtAccountOnboarding(
      this,
      request,
      options,
    ));
  }
}
