/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { demCreateWebsite } from "../funcs/demCreateWebsite.js";
import { demDeleteWebsite } from "../funcs/demDeleteWebsite.js";
import { demGetDemSettings } from "../funcs/demGetDemSettings.js";
import { demGetWebsite } from "../funcs/demGetWebsite.js";
import { demPauseWebsiteMonitoring } from "../funcs/demPauseWebsiteMonitoring.js";
import { demSetDemSettings } from "../funcs/demSetDemSettings.js";
import { demUnpauseWebsiteMonitoring } from "../funcs/demUnpauseWebsiteMonitoring.js";
import { demUpdateWebsite } from "../funcs/demUpdateWebsite.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Dem extends ClientSDK {
  /**
   * Get DEM settings
   */
  async getDemSettings(
    options?: RequestOptions,
  ): Promise<components.OutageConfiguration> {
    return unwrapAsync(demGetDemSettings(
      this,
      options,
    ));
  }

  /**
   * Set DEM settings
   */
  async setDemSettings(
    request: components.OutageConfiguration,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(demSetDemSettings(
      this,
      request,
      options,
    ));
  }

  /**
   * Create website monitoring configuration
   */
  async createWebsite(
    request: components.Website,
    options?: RequestOptions,
  ): Promise<components.EntityId> {
    return unwrapAsync(demCreateWebsite(
      this,
      request,
      options,
    ));
  }

  /**
   * Get website monitoring configuration
   */
  async getWebsite(
    request: operations.GetWebsiteRequest,
    options?: RequestOptions,
  ): Promise<operations.GetWebsiteResponse> {
    return unwrapAsync(demGetWebsite(
      this,
      request,
      options,
    ));
  }

  /**
   * Update website monitoring configuration
   */
  async updateWebsite(
    request: operations.UpdateWebsiteRequest,
    options?: RequestOptions,
  ): Promise<components.EntityId> {
    return unwrapAsync(demUpdateWebsite(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete website
   */
  async deleteWebsite(
    request: operations.DeleteWebsiteRequest,
    options?: RequestOptions,
  ): Promise<components.EntityId> {
    return unwrapAsync(demDeleteWebsite(
      this,
      request,
      options,
    ));
  }

  /**
   * Pause monitoring of a website
   */
  async pauseWebsiteMonitoring(
    request: operations.PauseWebsiteMonitoringRequest,
    options?: RequestOptions,
  ): Promise<components.EntityId> {
    return unwrapAsync(demPauseWebsiteMonitoring(
      this,
      request,
      options,
    ));
  }

  /**
   * Unpause monitoring of a website
   */
  async unpauseWebsiteMonitoring(
    request: operations.UnpauseWebsiteMonitoringRequest,
    options?: RequestOptions,
  ): Promise<components.EntityId> {
    return unwrapAsync(demUnpauseWebsiteMonitoring(
      this,
      request,
      options,
    ));
  }
}
