/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cloudAccountsActivateAwsIntegration } from "../../funcs/cloudAccountsActivateAwsIntegration.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.ActivateAwsIntegrationRequest$inboundSchema,
};

export const tool$cloudAccountsActivateAwsIntegration: ToolDefinition<
  typeof args
> = {
  name: "cloud-accounts-activate-aws-integration",
  description: `Activate AWS Integration

Activate AWS Integration.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await cloudAccountsActivateAwsIntegration(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
