/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cloudAccountsValidateMgmtAccountOnboarding } from "../../funcs/cloudAccountsValidateMgmtAccountOnboarding.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ValidateMgmtAccountOnboardingRequest$inboundSchema,
};

export const tool$cloudAccountsValidateMgmtAccountOnboarding: ToolDefinition<
  typeof args
> = {
  name: "cloud-accounts-validate-mgmt-account-onboarding",
  description: `Validate Management Account Onboarding

Validate if the management account is onboarded.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await cloudAccountsValidateMgmtAccountOnboarding(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
