/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dboDeleteDatabase } from "../../funcs/dboDeleteDatabase.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteDatabaseRequest$inboundSchema,
};

export const tool$dboDeleteDatabase: ToolDefinition<typeof args> = {
  name: "dbo-delete-database",
  description: `Delete an observed database`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await dboDeleteDatabase(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
