/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { demCreateTransaction } from "../../funcs/demCreateTransaction.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.DemTransaction$inboundSchema,
};

export const tool$demCreateTransaction: ToolDefinition<typeof args> = {
  name: "dem-create-transaction",
  description: `Create transaction monitoring configuration`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await demCreateTransaction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
