/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { demPauseTransactionMonitoring } from "../../funcs/demPauseTransactionMonitoring.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PauseTransactionMonitoringRequest$inboundSchema,
};

export const tool$demPauseTransactionMonitoring: ToolDefinition<typeof args> = {
  name: "dem-pause-transaction-monitoring",
  description: `Pause monitoring of the transaction`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await demPauseTransactionMonitoring(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
