/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { logsListLogArchives } from "../../funcs/logsListLogArchives.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListLogArchivesRequest$inboundSchema,
};

export const tool$logsListLogArchives: ToolDefinition<typeof args> = {
  name: "logs-list-log-archives",
  description: `Retrieve location and metadata of log archives

Retrieves a list of log archives within a time period.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await logsListLogArchives(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
