/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsListMetricAttributeValues } from "../../funcs/metricsListMetricAttributeValues.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListMetricAttributeValuesRequest$inboundSchema,
};

export const tool$metricsListMetricAttributeValues: ToolDefinition<
  typeof args
> = {
  name: "metrics_list-metric-attribute-values",
  description: `List metric attribute values

List the values of a given metric's attribute.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsListMetricAttributeValues(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
