/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import { SwoError } from "./swoerror.js";

/**
 * Uniquely identifies an error condition.
 */
export const CommonNotFoundErrorResponseCode = {
  AccessForbidden: "AccessForbidden",
  InternalError: "InternalError",
  InvalidRequest: "InvalidRequest",
  ResourceConflict: "ResourceConflict",
  ResourceNotFound: "ResourceNotFound",
  ServiceUnavailable: "ServiceUnavailable",
  Unauthorized: "Unauthorized",
} as const;
/**
 * Uniquely identifies an error condition.
 */
export type CommonNotFoundErrorResponseCode = ClosedEnum<
  typeof CommonNotFoundErrorResponseCode
>;

export type CommonNotFoundErrorResponseData = {
  /**
   * Supporting description of the error.
   */
  message: string;
  /**
   * Uniquely identifies an error condition.
   */
  code?: CommonNotFoundErrorResponseCode | undefined;
};

export class CommonNotFoundErrorResponse extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: CommonNotFoundErrorResponseCode | undefined;

  /** The original data that was passed to this error instance. */
  data$: CommonNotFoundErrorResponseData;

  constructor(
    err: CommonNotFoundErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name = "CommonNotFoundErrorResponse";
  }
}

/** @internal */
export const CommonNotFoundErrorResponseCode$inboundSchema: z.ZodNativeEnum<
  typeof CommonNotFoundErrorResponseCode
> = z.nativeEnum(CommonNotFoundErrorResponseCode);
/** @internal */
export const CommonNotFoundErrorResponseCode$outboundSchema: z.ZodNativeEnum<
  typeof CommonNotFoundErrorResponseCode
> = CommonNotFoundErrorResponseCode$inboundSchema;

/** @internal */
export const CommonNotFoundErrorResponse$inboundSchema: z.ZodType<
  CommonNotFoundErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: CommonNotFoundErrorResponseCode$inboundSchema.optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CommonNotFoundErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CommonNotFoundErrorResponse$Outbound = {
  message: string;
  code?: string | undefined;
};

/** @internal */
export const CommonNotFoundErrorResponse$outboundSchema: z.ZodType<
  CommonNotFoundErrorResponse$Outbound,
  z.ZodTypeDef,
  CommonNotFoundErrorResponse
> = z.instanceof(CommonNotFoundErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: CommonNotFoundErrorResponseCode$outboundSchema.optional(),
  }));
