/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import { SwoError } from "./swoerror.js";

/**
 * Uniquely identifies an error condition.
 */
export const CommonInternalErrorResponseCode = {
  AccessForbidden: "AccessForbidden",
  InternalError: "InternalError",
  InvalidRequest: "InvalidRequest",
  ResourceConflict: "ResourceConflict",
  ResourceNotFound: "ResourceNotFound",
  ServiceUnavailable: "ServiceUnavailable",
  Unauthorized: "Unauthorized",
} as const;
/**
 * Uniquely identifies an error condition.
 */
export type CommonInternalErrorResponseCode = ClosedEnum<
  typeof CommonInternalErrorResponseCode
>;

export type CommonInternalErrorResponseData = {
  /**
   * Supporting description of the error.
   */
  message: string;
  /**
   * Uniquely identifies an error condition.
   */
  code?: CommonInternalErrorResponseCode | undefined;
};

export class CommonInternalErrorResponse extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: CommonInternalErrorResponseCode | undefined;

  /** The original data that was passed to this error instance. */
  data$: CommonInternalErrorResponseData;

  constructor(
    err: CommonInternalErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name = "CommonInternalErrorResponse";
  }
}

/** @internal */
export const CommonInternalErrorResponseCode$inboundSchema: z.ZodNativeEnum<
  typeof CommonInternalErrorResponseCode
> = z.nativeEnum(CommonInternalErrorResponseCode);

/** @internal */
export const CommonInternalErrorResponseCode$outboundSchema: z.ZodNativeEnum<
  typeof CommonInternalErrorResponseCode
> = CommonInternalErrorResponseCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommonInternalErrorResponseCode$ {
  /** @deprecated use `CommonInternalErrorResponseCode$inboundSchema` instead. */
  export const inboundSchema = CommonInternalErrorResponseCode$inboundSchema;
  /** @deprecated use `CommonInternalErrorResponseCode$outboundSchema` instead. */
  export const outboundSchema = CommonInternalErrorResponseCode$outboundSchema;
}

/** @internal */
export const CommonInternalErrorResponse$inboundSchema: z.ZodType<
  CommonInternalErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: CommonInternalErrorResponseCode$inboundSchema.optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CommonInternalErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CommonInternalErrorResponse$Outbound = {
  message: string;
  code?: string | undefined;
};

/** @internal */
export const CommonInternalErrorResponse$outboundSchema: z.ZodType<
  CommonInternalErrorResponse$Outbound,
  z.ZodTypeDef,
  CommonInternalErrorResponse
> = z.instanceof(CommonInternalErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: CommonInternalErrorResponseCode$outboundSchema.optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommonInternalErrorResponse$ {
  /** @deprecated use `CommonInternalErrorResponse$inboundSchema` instead. */
  export const inboundSchema = CommonInternalErrorResponse$inboundSchema;
  /** @deprecated use `CommonInternalErrorResponse$outboundSchema` instead. */
  export const outboundSchema = CommonInternalErrorResponse$outboundSchema;
  /** @deprecated use `CommonInternalErrorResponse$Outbound` instead. */
  export type Outbound = CommonInternalErrorResponse$Outbound;
}
