/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import { SwoError } from "./swoerror.js";

/**
 * Uniquely identifies an error condition.
 */
export const CommonBadRequestErrorResponseCode = {
  AccessForbidden: "AccessForbidden",
  InternalError: "InternalError",
  InvalidRequest: "InvalidRequest",
  ResourceConflict: "ResourceConflict",
  ResourceNotFound: "ResourceNotFound",
  ServiceUnavailable: "ServiceUnavailable",
  Unauthorized: "Unauthorized",
} as const;
/**
 * Uniquely identifies an error condition.
 */
export type CommonBadRequestErrorResponseCode = ClosedEnum<
  typeof CommonBadRequestErrorResponseCode
>;

export type CommonBadRequestErrorResponseData = {
  /**
   * Supporting description of the error.
   */
  message: string;
  /**
   * Indicates the invalid field.
   */
  target?: string | undefined;
  /**
   * Uniquely identifies an error condition.
   */
  code?: CommonBadRequestErrorResponseCode | undefined;
};

export class CommonBadRequestErrorResponse extends SwoError {
  /**
   * Indicates the invalid field.
   */
  target?: string | undefined;
  /**
   * Uniquely identifies an error condition.
   */
  code?: CommonBadRequestErrorResponseCode | undefined;

  /** The original data that was passed to this error instance. */
  data$: CommonBadRequestErrorResponseData;

  constructor(
    err: CommonBadRequestErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.target != null) this.target = err.target;
    if (err.code != null) this.code = err.code;

    this.name = "CommonBadRequestErrorResponse";
  }
}

/** @internal */
export const CommonBadRequestErrorResponseCode$inboundSchema: z.ZodNativeEnum<
  typeof CommonBadRequestErrorResponseCode
> = z.nativeEnum(CommonBadRequestErrorResponseCode);

/** @internal */
export const CommonBadRequestErrorResponseCode$outboundSchema: z.ZodNativeEnum<
  typeof CommonBadRequestErrorResponseCode
> = CommonBadRequestErrorResponseCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommonBadRequestErrorResponseCode$ {
  /** @deprecated use `CommonBadRequestErrorResponseCode$inboundSchema` instead. */
  export const inboundSchema = CommonBadRequestErrorResponseCode$inboundSchema;
  /** @deprecated use `CommonBadRequestErrorResponseCode$outboundSchema` instead. */
  export const outboundSchema =
    CommonBadRequestErrorResponseCode$outboundSchema;
}

/** @internal */
export const CommonBadRequestErrorResponse$inboundSchema: z.ZodType<
  CommonBadRequestErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  target: z.string().optional(),
  code: CommonBadRequestErrorResponseCode$inboundSchema.optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CommonBadRequestErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CommonBadRequestErrorResponse$Outbound = {
  message: string;
  target?: string | undefined;
  code?: string | undefined;
};

/** @internal */
export const CommonBadRequestErrorResponse$outboundSchema: z.ZodType<
  CommonBadRequestErrorResponse$Outbound,
  z.ZodTypeDef,
  CommonBadRequestErrorResponse
> = z.instanceof(CommonBadRequestErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    target: z.string().optional(),
    code: CommonBadRequestErrorResponseCode$outboundSchema.optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommonBadRequestErrorResponse$ {
  /** @deprecated use `CommonBadRequestErrorResponse$inboundSchema` instead. */
  export const inboundSchema = CommonBadRequestErrorResponse$inboundSchema;
  /** @deprecated use `CommonBadRequestErrorResponse$outboundSchema` instead. */
  export const outboundSchema = CommonBadRequestErrorResponse$outboundSchema;
  /** @deprecated use `CommonBadRequestErrorResponse$Outbound` instead. */
  export type Outbound = CommonBadRequestErrorResponse$Outbound;
}
