/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";
import { SwoError } from "./swoerror.js";

/**
 * The server could not understand the request due to invalid syntax.
 */
export type CreateUriBadRequestErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class CreateUriBadRequestError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateUriBadRequestErrorData;

  constructor(
    err: CreateUriBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "CreateUriBadRequestError";
  }
}

/** @internal */
export const CreateUriBadRequestError$inboundSchema: z.ZodType<
  CreateUriBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CreateUriBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CreateUriBadRequestError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const CreateUriBadRequestError$outboundSchema: z.ZodType<
  CreateUriBadRequestError$Outbound,
  z.ZodTypeDef,
  CreateUriBadRequestError
> = z.instanceof(CreateUriBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateUriBadRequestError$ {
  /** @deprecated use `CreateUriBadRequestError$inboundSchema` instead. */
  export const inboundSchema = CreateUriBadRequestError$inboundSchema;
  /** @deprecated use `CreateUriBadRequestError$outboundSchema` instead. */
  export const outboundSchema = CreateUriBadRequestError$outboundSchema;
  /** @deprecated use `CreateUriBadRequestError$Outbound` instead. */
  export type Outbound = CreateUriBadRequestError$Outbound;
}
