/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The server could not understand the request due to invalid syntax.
 */
export type CreateUriBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class CreateUriBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateUriBadRequestErrorData;

  constructor(err: CreateUriBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "CreateUriBadRequestError";
  }
}

/** @internal */
export const CreateUriBadRequestError$inboundSchema: z.ZodType<
  CreateUriBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new CreateUriBadRequestError(v);
  });

/** @internal */
export type CreateUriBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const CreateUriBadRequestError$outboundSchema: z.ZodType<
  CreateUriBadRequestError$Outbound,
  z.ZodTypeDef,
  CreateUriBadRequestError
> = z.instanceof(CreateUriBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateUriBadRequestError$ {
  /** @deprecated use `CreateUriBadRequestError$inboundSchema` instead. */
  export const inboundSchema = CreateUriBadRequestError$inboundSchema;
  /** @deprecated use `CreateUriBadRequestError$outboundSchema` instead. */
  export const outboundSchema = CreateUriBadRequestError$outboundSchema;
  /** @deprecated use `CreateUriBadRequestError$Outbound` instead. */
  export type Outbound = CreateUriBadRequestError$Outbound;
}
