/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Server error
 */
export type CreateOrgStructureInternalServerErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * Server error
 */
export class CreateOrgStructureInternalServerError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateOrgStructureInternalServerErrorData;

  constructor(err: CreateOrgStructureInternalServerErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "CreateOrgStructureInternalServerError";
  }
}

/**
 * The server cannot find the requested resource.
 */
export type CreateOrgStructureNotFoundErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class CreateOrgStructureNotFoundError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateOrgStructureNotFoundErrorData;

  constructor(err: CreateOrgStructureNotFoundErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "CreateOrgStructureNotFoundError";
  }
}

/**
 * Access is unauthorized.
 */
export type CreateOrgStructureUnauthorizedErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * Access is unauthorized.
 */
export class CreateOrgStructureUnauthorizedError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateOrgStructureUnauthorizedErrorData;

  constructor(err: CreateOrgStructureUnauthorizedErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "CreateOrgStructureUnauthorizedError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type CreateOrgStructureBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class CreateOrgStructureBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateOrgStructureBadRequestErrorData;

  constructor(err: CreateOrgStructureBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "CreateOrgStructureBadRequestError";
  }
}

/** @internal */
export const CreateOrgStructureInternalServerError$inboundSchema: z.ZodType<
  CreateOrgStructureInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new CreateOrgStructureInternalServerError(v);
  });

/** @internal */
export type CreateOrgStructureInternalServerError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const CreateOrgStructureInternalServerError$outboundSchema: z.ZodType<
  CreateOrgStructureInternalServerError$Outbound,
  z.ZodTypeDef,
  CreateOrgStructureInternalServerError
> = z.instanceof(CreateOrgStructureInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateOrgStructureInternalServerError$ {
  /** @deprecated use `CreateOrgStructureInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    CreateOrgStructureInternalServerError$inboundSchema;
  /** @deprecated use `CreateOrgStructureInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    CreateOrgStructureInternalServerError$outboundSchema;
  /** @deprecated use `CreateOrgStructureInternalServerError$Outbound` instead. */
  export type Outbound = CreateOrgStructureInternalServerError$Outbound;
}

/** @internal */
export const CreateOrgStructureNotFoundError$inboundSchema: z.ZodType<
  CreateOrgStructureNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new CreateOrgStructureNotFoundError(v);
  });

/** @internal */
export type CreateOrgStructureNotFoundError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const CreateOrgStructureNotFoundError$outboundSchema: z.ZodType<
  CreateOrgStructureNotFoundError$Outbound,
  z.ZodTypeDef,
  CreateOrgStructureNotFoundError
> = z.instanceof(CreateOrgStructureNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateOrgStructureNotFoundError$ {
  /** @deprecated use `CreateOrgStructureNotFoundError$inboundSchema` instead. */
  export const inboundSchema = CreateOrgStructureNotFoundError$inboundSchema;
  /** @deprecated use `CreateOrgStructureNotFoundError$outboundSchema` instead. */
  export const outboundSchema = CreateOrgStructureNotFoundError$outboundSchema;
  /** @deprecated use `CreateOrgStructureNotFoundError$Outbound` instead. */
  export type Outbound = CreateOrgStructureNotFoundError$Outbound;
}

/** @internal */
export const CreateOrgStructureUnauthorizedError$inboundSchema: z.ZodType<
  CreateOrgStructureUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new CreateOrgStructureUnauthorizedError(v);
  });

/** @internal */
export type CreateOrgStructureUnauthorizedError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const CreateOrgStructureUnauthorizedError$outboundSchema: z.ZodType<
  CreateOrgStructureUnauthorizedError$Outbound,
  z.ZodTypeDef,
  CreateOrgStructureUnauthorizedError
> = z.instanceof(CreateOrgStructureUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateOrgStructureUnauthorizedError$ {
  /** @deprecated use `CreateOrgStructureUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    CreateOrgStructureUnauthorizedError$inboundSchema;
  /** @deprecated use `CreateOrgStructureUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    CreateOrgStructureUnauthorizedError$outboundSchema;
  /** @deprecated use `CreateOrgStructureUnauthorizedError$Outbound` instead. */
  export type Outbound = CreateOrgStructureUnauthorizedError$Outbound;
}

/** @internal */
export const CreateOrgStructureBadRequestError$inboundSchema: z.ZodType<
  CreateOrgStructureBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new CreateOrgStructureBadRequestError(v);
  });

/** @internal */
export type CreateOrgStructureBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const CreateOrgStructureBadRequestError$outboundSchema: z.ZodType<
  CreateOrgStructureBadRequestError$Outbound,
  z.ZodTypeDef,
  CreateOrgStructureBadRequestError
> = z.instanceof(CreateOrgStructureBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateOrgStructureBadRequestError$ {
  /** @deprecated use `CreateOrgStructureBadRequestError$inboundSchema` instead. */
  export const inboundSchema = CreateOrgStructureBadRequestError$inboundSchema;
  /** @deprecated use `CreateOrgStructureBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    CreateOrgStructureBadRequestError$outboundSchema;
  /** @deprecated use `CreateOrgStructureBadRequestError$Outbound` instead. */
  export type Outbound = CreateOrgStructureBadRequestError$Outbound;
}
