/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";
import { SwoError } from "./swoerror.js";

/**
 * The server cannot find the requested resource.
 */
export type DeleteCompositeMetricNotFoundErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class DeleteCompositeMetricNotFoundError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: DeleteCompositeMetricNotFoundErrorData;

  constructor(
    err: DeleteCompositeMetricNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "DeleteCompositeMetricNotFoundError";
  }
}

/**
 * Access is forbidden.
 */
export type DeleteCompositeMetricForbiddenErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.MetricsMetricErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * Access is forbidden.
 */
export class DeleteCompositeMetricForbiddenError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.MetricsMetricErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: DeleteCompositeMetricForbiddenErrorData;

  constructor(
    err: DeleteCompositeMetricForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "DeleteCompositeMetricForbiddenError";
  }
}

/** @internal */
export const DeleteCompositeMetricNotFoundError$inboundSchema: z.ZodType<
  DeleteCompositeMetricNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DeleteCompositeMetricNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DeleteCompositeMetricNotFoundError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const DeleteCompositeMetricNotFoundError$outboundSchema: z.ZodType<
  DeleteCompositeMetricNotFoundError$Outbound,
  z.ZodTypeDef,
  DeleteCompositeMetricNotFoundError
> = z.instanceof(DeleteCompositeMetricNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteCompositeMetricNotFoundError$ {
  /** @deprecated use `DeleteCompositeMetricNotFoundError$inboundSchema` instead. */
  export const inboundSchema = DeleteCompositeMetricNotFoundError$inboundSchema;
  /** @deprecated use `DeleteCompositeMetricNotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    DeleteCompositeMetricNotFoundError$outboundSchema;
  /** @deprecated use `DeleteCompositeMetricNotFoundError$Outbound` instead. */
  export type Outbound = DeleteCompositeMetricNotFoundError$Outbound;
}

/** @internal */
export const DeleteCompositeMetricForbiddenError$inboundSchema: z.ZodType<
  DeleteCompositeMetricForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.MetricsMetricErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DeleteCompositeMetricForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DeleteCompositeMetricForbiddenError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const DeleteCompositeMetricForbiddenError$outboundSchema: z.ZodType<
  DeleteCompositeMetricForbiddenError$Outbound,
  z.ZodTypeDef,
  DeleteCompositeMetricForbiddenError
> = z.instanceof(DeleteCompositeMetricForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.MetricsMetricErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteCompositeMetricForbiddenError$ {
  /** @deprecated use `DeleteCompositeMetricForbiddenError$inboundSchema` instead. */
  export const inboundSchema =
    DeleteCompositeMetricForbiddenError$inboundSchema;
  /** @deprecated use `DeleteCompositeMetricForbiddenError$outboundSchema` instead. */
  export const outboundSchema =
    DeleteCompositeMetricForbiddenError$outboundSchema;
  /** @deprecated use `DeleteCompositeMetricForbiddenError$Outbound` instead. */
  export type Outbound = DeleteCompositeMetricForbiddenError$Outbound;
}
