/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The server cannot find the requested resource.
 */
export type DeleteDatabaseNotFoundErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class DeleteDatabaseNotFoundError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: DeleteDatabaseNotFoundErrorData;

  constructor(err: DeleteDatabaseNotFoundErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "DeleteDatabaseNotFoundError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type DeleteDatabaseBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class DeleteDatabaseBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: DeleteDatabaseBadRequestErrorData;

  constructor(err: DeleteDatabaseBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "DeleteDatabaseBadRequestError";
  }
}

/** @internal */
export const DeleteDatabaseNotFoundError$inboundSchema: z.ZodType<
  DeleteDatabaseNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new DeleteDatabaseNotFoundError(v);
  });

/** @internal */
export type DeleteDatabaseNotFoundError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const DeleteDatabaseNotFoundError$outboundSchema: z.ZodType<
  DeleteDatabaseNotFoundError$Outbound,
  z.ZodTypeDef,
  DeleteDatabaseNotFoundError
> = z.instanceof(DeleteDatabaseNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteDatabaseNotFoundError$ {
  /** @deprecated use `DeleteDatabaseNotFoundError$inboundSchema` instead. */
  export const inboundSchema = DeleteDatabaseNotFoundError$inboundSchema;
  /** @deprecated use `DeleteDatabaseNotFoundError$outboundSchema` instead. */
  export const outboundSchema = DeleteDatabaseNotFoundError$outboundSchema;
  /** @deprecated use `DeleteDatabaseNotFoundError$Outbound` instead. */
  export type Outbound = DeleteDatabaseNotFoundError$Outbound;
}

/** @internal */
export const DeleteDatabaseBadRequestError$inboundSchema: z.ZodType<
  DeleteDatabaseBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new DeleteDatabaseBadRequestError(v);
  });

/** @internal */
export type DeleteDatabaseBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const DeleteDatabaseBadRequestError$outboundSchema: z.ZodType<
  DeleteDatabaseBadRequestError$Outbound,
  z.ZodTypeDef,
  DeleteDatabaseBadRequestError
> = z.instanceof(DeleteDatabaseBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteDatabaseBadRequestError$ {
  /** @deprecated use `DeleteDatabaseBadRequestError$inboundSchema` instead. */
  export const inboundSchema = DeleteDatabaseBadRequestError$inboundSchema;
  /** @deprecated use `DeleteDatabaseBadRequestError$outboundSchema` instead. */
  export const outboundSchema = DeleteDatabaseBadRequestError$outboundSchema;
  /** @deprecated use `DeleteDatabaseBadRequestError$Outbound` instead. */
  export type Outbound = DeleteDatabaseBadRequestError$Outbound;
}
