/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";
import { SwoError } from "./swoerror.js";

/**
 * The server cannot find the requested resource.
 */
export type GetPublicKeyNotFoundErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class GetPublicKeyNotFoundError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetPublicKeyNotFoundErrorData;

  constructor(
    err: GetPublicKeyNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "GetPublicKeyNotFoundError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type GetPublicKeyBadRequestErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class GetPublicKeyBadRequestError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetPublicKeyBadRequestErrorData;

  constructor(
    err: GetPublicKeyBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "GetPublicKeyBadRequestError";
  }
}

/** @internal */
export const GetPublicKeyNotFoundError$inboundSchema: z.ZodType<
  GetPublicKeyNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetPublicKeyNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetPublicKeyNotFoundError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const GetPublicKeyNotFoundError$outboundSchema: z.ZodType<
  GetPublicKeyNotFoundError$Outbound,
  z.ZodTypeDef,
  GetPublicKeyNotFoundError
> = z.instanceof(GetPublicKeyNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPublicKeyNotFoundError$ {
  /** @deprecated use `GetPublicKeyNotFoundError$inboundSchema` instead. */
  export const inboundSchema = GetPublicKeyNotFoundError$inboundSchema;
  /** @deprecated use `GetPublicKeyNotFoundError$outboundSchema` instead. */
  export const outboundSchema = GetPublicKeyNotFoundError$outboundSchema;
  /** @deprecated use `GetPublicKeyNotFoundError$Outbound` instead. */
  export type Outbound = GetPublicKeyNotFoundError$Outbound;
}

/** @internal */
export const GetPublicKeyBadRequestError$inboundSchema: z.ZodType<
  GetPublicKeyBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetPublicKeyBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetPublicKeyBadRequestError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const GetPublicKeyBadRequestError$outboundSchema: z.ZodType<
  GetPublicKeyBadRequestError$Outbound,
  z.ZodTypeDef,
  GetPublicKeyBadRequestError
> = z.instanceof(GetPublicKeyBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPublicKeyBadRequestError$ {
  /** @deprecated use `GetPublicKeyBadRequestError$inboundSchema` instead. */
  export const inboundSchema = GetPublicKeyBadRequestError$inboundSchema;
  /** @deprecated use `GetPublicKeyBadRequestError$outboundSchema` instead. */
  export const outboundSchema = GetPublicKeyBadRequestError$outboundSchema;
  /** @deprecated use `GetPublicKeyBadRequestError$Outbound` instead. */
  export type Outbound = GetPublicKeyBadRequestError$Outbound;
}
