/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The server cannot find the requested resource.
 */
export type GetPluginsNotFoundErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class GetPluginsNotFoundError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetPluginsNotFoundErrorData;

  constructor(err: GetPluginsNotFoundErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "GetPluginsNotFoundError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type GetPluginsBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class GetPluginsBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetPluginsBadRequestErrorData;

  constructor(err: GetPluginsBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "GetPluginsBadRequestError";
  }
}

/** @internal */
export const GetPluginsNotFoundError$inboundSchema: z.ZodType<
  GetPluginsNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new GetPluginsNotFoundError(v);
  });

/** @internal */
export type GetPluginsNotFoundError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const GetPluginsNotFoundError$outboundSchema: z.ZodType<
  GetPluginsNotFoundError$Outbound,
  z.ZodTypeDef,
  GetPluginsNotFoundError
> = z.instanceof(GetPluginsNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPluginsNotFoundError$ {
  /** @deprecated use `GetPluginsNotFoundError$inboundSchema` instead. */
  export const inboundSchema = GetPluginsNotFoundError$inboundSchema;
  /** @deprecated use `GetPluginsNotFoundError$outboundSchema` instead. */
  export const outboundSchema = GetPluginsNotFoundError$outboundSchema;
  /** @deprecated use `GetPluginsNotFoundError$Outbound` instead. */
  export type Outbound = GetPluginsNotFoundError$Outbound;
}

/** @internal */
export const GetPluginsBadRequestError$inboundSchema: z.ZodType<
  GetPluginsBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new GetPluginsBadRequestError(v);
  });

/** @internal */
export type GetPluginsBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const GetPluginsBadRequestError$outboundSchema: z.ZodType<
  GetPluginsBadRequestError$Outbound,
  z.ZodTypeDef,
  GetPluginsBadRequestError
> = z.instanceof(GetPluginsBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPluginsBadRequestError$ {
  /** @deprecated use `GetPluginsBadRequestError$inboundSchema` instead. */
  export const inboundSchema = GetPluginsBadRequestError$inboundSchema;
  /** @deprecated use `GetPluginsBadRequestError$outboundSchema` instead. */
  export const outboundSchema = GetPluginsBadRequestError$outboundSchema;
  /** @deprecated use `GetPluginsBadRequestError$Outbound` instead. */
  export type Outbound = GetPluginsBadRequestError$Outbound;
}
