/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Server error
 */
export type ListEntitiesNotImplementedErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * Server error
 */
export class ListEntitiesNotImplementedError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ListEntitiesNotImplementedErrorData;

  constructor(err: ListEntitiesNotImplementedErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "ListEntitiesNotImplementedError";
  }
}

/**
 * Access is unauthorized.
 */
export type ListEntitiesUnauthorizedErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * Access is unauthorized.
 */
export class ListEntitiesUnauthorizedError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ListEntitiesUnauthorizedErrorData;

  constructor(err: ListEntitiesUnauthorizedErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "ListEntitiesUnauthorizedError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type ListEntitiesBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class ListEntitiesBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ListEntitiesBadRequestErrorData;

  constructor(err: ListEntitiesBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "ListEntitiesBadRequestError";
  }
}

/** @internal */
export const ListEntitiesNotImplementedError$inboundSchema: z.ZodType<
  ListEntitiesNotImplementedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new ListEntitiesNotImplementedError(v);
  });

/** @internal */
export type ListEntitiesNotImplementedError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const ListEntitiesNotImplementedError$outboundSchema: z.ZodType<
  ListEntitiesNotImplementedError$Outbound,
  z.ZodTypeDef,
  ListEntitiesNotImplementedError
> = z.instanceof(ListEntitiesNotImplementedError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListEntitiesNotImplementedError$ {
  /** @deprecated use `ListEntitiesNotImplementedError$inboundSchema` instead. */
  export const inboundSchema = ListEntitiesNotImplementedError$inboundSchema;
  /** @deprecated use `ListEntitiesNotImplementedError$outboundSchema` instead. */
  export const outboundSchema = ListEntitiesNotImplementedError$outboundSchema;
  /** @deprecated use `ListEntitiesNotImplementedError$Outbound` instead. */
  export type Outbound = ListEntitiesNotImplementedError$Outbound;
}

/** @internal */
export const ListEntitiesUnauthorizedError$inboundSchema: z.ZodType<
  ListEntitiesUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new ListEntitiesUnauthorizedError(v);
  });

/** @internal */
export type ListEntitiesUnauthorizedError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const ListEntitiesUnauthorizedError$outboundSchema: z.ZodType<
  ListEntitiesUnauthorizedError$Outbound,
  z.ZodTypeDef,
  ListEntitiesUnauthorizedError
> = z.instanceof(ListEntitiesUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListEntitiesUnauthorizedError$ {
  /** @deprecated use `ListEntitiesUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema = ListEntitiesUnauthorizedError$inboundSchema;
  /** @deprecated use `ListEntitiesUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema = ListEntitiesUnauthorizedError$outboundSchema;
  /** @deprecated use `ListEntitiesUnauthorizedError$Outbound` instead. */
  export type Outbound = ListEntitiesUnauthorizedError$Outbound;
}

/** @internal */
export const ListEntitiesBadRequestError$inboundSchema: z.ZodType<
  ListEntitiesBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new ListEntitiesBadRequestError(v);
  });

/** @internal */
export type ListEntitiesBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const ListEntitiesBadRequestError$outboundSchema: z.ZodType<
  ListEntitiesBadRequestError$Outbound,
  z.ZodTypeDef,
  ListEntitiesBadRequestError
> = z.instanceof(ListEntitiesBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListEntitiesBadRequestError$ {
  /** @deprecated use `ListEntitiesBadRequestError$inboundSchema` instead. */
  export const inboundSchema = ListEntitiesBadRequestError$inboundSchema;
  /** @deprecated use `ListEntitiesBadRequestError$outboundSchema` instead. */
  export const outboundSchema = ListEntitiesBadRequestError$outboundSchema;
  /** @deprecated use `ListEntitiesBadRequestError$Outbound` instead. */
  export type Outbound = ListEntitiesBadRequestError$Outbound;
}
