/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The server cannot find the requested resource.
 */
export type PauseUriMonitoringNotFoundErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class PauseUriMonitoringNotFoundError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PauseUriMonitoringNotFoundErrorData;

  constructor(err: PauseUriMonitoringNotFoundErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "PauseUriMonitoringNotFoundError";
  }
}

/** @internal */
export const PauseUriMonitoringNotFoundError$inboundSchema: z.ZodType<
  PauseUriMonitoringNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new PauseUriMonitoringNotFoundError(v);
  });

/** @internal */
export type PauseUriMonitoringNotFoundError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const PauseUriMonitoringNotFoundError$outboundSchema: z.ZodType<
  PauseUriMonitoringNotFoundError$Outbound,
  z.ZodTypeDef,
  PauseUriMonitoringNotFoundError
> = z.instanceof(PauseUriMonitoringNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PauseUriMonitoringNotFoundError$ {
  /** @deprecated use `PauseUriMonitoringNotFoundError$inboundSchema` instead. */
  export const inboundSchema = PauseUriMonitoringNotFoundError$inboundSchema;
  /** @deprecated use `PauseUriMonitoringNotFoundError$outboundSchema` instead. */
  export const outboundSchema = PauseUriMonitoringNotFoundError$outboundSchema;
  /** @deprecated use `PauseUriMonitoringNotFoundError$Outbound` instead. */
  export type Outbound = PauseUriMonitoringNotFoundError$Outbound;
}
