/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";
import { SwoError } from "./swoerror.js";

/**
 * The server cannot find the requested resource.
 */
export type PauseUriMonitoringNotFoundErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class PauseUriMonitoringNotFoundError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PauseUriMonitoringNotFoundErrorData;

  constructor(
    err: PauseUriMonitoringNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "PauseUriMonitoringNotFoundError";
  }
}

/** @internal */
export const PauseUriMonitoringNotFoundError$inboundSchema: z.ZodType<
  PauseUriMonitoringNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PauseUriMonitoringNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PauseUriMonitoringNotFoundError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const PauseUriMonitoringNotFoundError$outboundSchema: z.ZodType<
  PauseUriMonitoringNotFoundError$Outbound,
  z.ZodTypeDef,
  PauseUriMonitoringNotFoundError
> = z.instanceof(PauseUriMonitoringNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PauseUriMonitoringNotFoundError$ {
  /** @deprecated use `PauseUriMonitoringNotFoundError$inboundSchema` instead. */
  export const inboundSchema = PauseUriMonitoringNotFoundError$inboundSchema;
  /** @deprecated use `PauseUriMonitoringNotFoundError$outboundSchema` instead. */
  export const outboundSchema = PauseUriMonitoringNotFoundError$outboundSchema;
  /** @deprecated use `PauseUriMonitoringNotFoundError$Outbound` instead. */
  export type Outbound = PauseUriMonitoringNotFoundError$Outbound;
}
