/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The server could not understand the request due to invalid syntax.
 */
export type UnpauseWebsiteMonitoringBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class UnpauseWebsiteMonitoringBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UnpauseWebsiteMonitoringBadRequestErrorData;

  constructor(err: UnpauseWebsiteMonitoringBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UnpauseWebsiteMonitoringBadRequestError";
  }
}

/** @internal */
export const UnpauseWebsiteMonitoringBadRequestError$inboundSchema: z.ZodType<
  UnpauseWebsiteMonitoringBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new UnpauseWebsiteMonitoringBadRequestError(v);
  });

/** @internal */
export type UnpauseWebsiteMonitoringBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UnpauseWebsiteMonitoringBadRequestError$outboundSchema: z.ZodType<
  UnpauseWebsiteMonitoringBadRequestError$Outbound,
  z.ZodTypeDef,
  UnpauseWebsiteMonitoringBadRequestError
> = z.instanceof(UnpauseWebsiteMonitoringBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnpauseWebsiteMonitoringBadRequestError$ {
  /** @deprecated use `UnpauseWebsiteMonitoringBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    UnpauseWebsiteMonitoringBadRequestError$inboundSchema;
  /** @deprecated use `UnpauseWebsiteMonitoringBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    UnpauseWebsiteMonitoringBadRequestError$outboundSchema;
  /** @deprecated use `UnpauseWebsiteMonitoringBadRequestError$Outbound` instead. */
  export type Outbound = UnpauseWebsiteMonitoringBadRequestError$Outbound;
}
