/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Server error
 */
export type UpdateAwsIntegrationInternalServerErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * Server error
 */
export class UpdateAwsIntegrationInternalServerError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateAwsIntegrationInternalServerErrorData;

  constructor(err: UpdateAwsIntegrationInternalServerErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateAwsIntegrationInternalServerError";
  }
}

/**
 * Access is unauthorized.
 */
export type UpdateAwsIntegrationUnauthorizedErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * Access is unauthorized.
 */
export class UpdateAwsIntegrationUnauthorizedError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateAwsIntegrationUnauthorizedErrorData;

  constructor(err: UpdateAwsIntegrationUnauthorizedErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateAwsIntegrationUnauthorizedError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type UpdateAwsIntegrationBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class UpdateAwsIntegrationBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateAwsIntegrationBadRequestErrorData;

  constructor(err: UpdateAwsIntegrationBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateAwsIntegrationBadRequestError";
  }
}

/** @internal */
export const UpdateAwsIntegrationInternalServerError$inboundSchema: z.ZodType<
  UpdateAwsIntegrationInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new UpdateAwsIntegrationInternalServerError(v);
  });

/** @internal */
export type UpdateAwsIntegrationInternalServerError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateAwsIntegrationInternalServerError$outboundSchema: z.ZodType<
  UpdateAwsIntegrationInternalServerError$Outbound,
  z.ZodTypeDef,
  UpdateAwsIntegrationInternalServerError
> = z.instanceof(UpdateAwsIntegrationInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAwsIntegrationInternalServerError$ {
  /** @deprecated use `UpdateAwsIntegrationInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAwsIntegrationInternalServerError$inboundSchema;
  /** @deprecated use `UpdateAwsIntegrationInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAwsIntegrationInternalServerError$outboundSchema;
  /** @deprecated use `UpdateAwsIntegrationInternalServerError$Outbound` instead. */
  export type Outbound = UpdateAwsIntegrationInternalServerError$Outbound;
}

/** @internal */
export const UpdateAwsIntegrationUnauthorizedError$inboundSchema: z.ZodType<
  UpdateAwsIntegrationUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new UpdateAwsIntegrationUnauthorizedError(v);
  });

/** @internal */
export type UpdateAwsIntegrationUnauthorizedError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateAwsIntegrationUnauthorizedError$outboundSchema: z.ZodType<
  UpdateAwsIntegrationUnauthorizedError$Outbound,
  z.ZodTypeDef,
  UpdateAwsIntegrationUnauthorizedError
> = z.instanceof(UpdateAwsIntegrationUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAwsIntegrationUnauthorizedError$ {
  /** @deprecated use `UpdateAwsIntegrationUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAwsIntegrationUnauthorizedError$inboundSchema;
  /** @deprecated use `UpdateAwsIntegrationUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAwsIntegrationUnauthorizedError$outboundSchema;
  /** @deprecated use `UpdateAwsIntegrationUnauthorizedError$Outbound` instead. */
  export type Outbound = UpdateAwsIntegrationUnauthorizedError$Outbound;
}

/** @internal */
export const UpdateAwsIntegrationBadRequestError$inboundSchema: z.ZodType<
  UpdateAwsIntegrationBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new UpdateAwsIntegrationBadRequestError(v);
  });

/** @internal */
export type UpdateAwsIntegrationBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateAwsIntegrationBadRequestError$outboundSchema: z.ZodType<
  UpdateAwsIntegrationBadRequestError$Outbound,
  z.ZodTypeDef,
  UpdateAwsIntegrationBadRequestError
> = z.instanceof(UpdateAwsIntegrationBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAwsIntegrationBadRequestError$ {
  /** @deprecated use `UpdateAwsIntegrationBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAwsIntegrationBadRequestError$inboundSchema;
  /** @deprecated use `UpdateAwsIntegrationBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAwsIntegrationBadRequestError$outboundSchema;
  /** @deprecated use `UpdateAwsIntegrationBadRequestError$Outbound` instead. */
  export type Outbound = UpdateAwsIntegrationBadRequestError$Outbound;
}
