/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";
import { SwoError } from "./swoerror.js";

/**
 * The server cannot find the requested resource.
 */
export type UpdateDatabaseNotFoundErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class UpdateDatabaseNotFoundError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateDatabaseNotFoundErrorData;

  constructor(
    err: UpdateDatabaseNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateDatabaseNotFoundError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type UpdateDatabaseBadRequestErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class UpdateDatabaseBadRequestError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateDatabaseBadRequestErrorData;

  constructor(
    err: UpdateDatabaseBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateDatabaseBadRequestError";
  }
}

/** @internal */
export const UpdateDatabaseNotFoundError$inboundSchema: z.ZodType<
  UpdateDatabaseNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UpdateDatabaseNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UpdateDatabaseNotFoundError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateDatabaseNotFoundError$outboundSchema: z.ZodType<
  UpdateDatabaseNotFoundError$Outbound,
  z.ZodTypeDef,
  UpdateDatabaseNotFoundError
> = z.instanceof(UpdateDatabaseNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDatabaseNotFoundError$ {
  /** @deprecated use `UpdateDatabaseNotFoundError$inboundSchema` instead. */
  export const inboundSchema = UpdateDatabaseNotFoundError$inboundSchema;
  /** @deprecated use `UpdateDatabaseNotFoundError$outboundSchema` instead. */
  export const outboundSchema = UpdateDatabaseNotFoundError$outboundSchema;
  /** @deprecated use `UpdateDatabaseNotFoundError$Outbound` instead. */
  export type Outbound = UpdateDatabaseNotFoundError$Outbound;
}

/** @internal */
export const UpdateDatabaseBadRequestError$inboundSchema: z.ZodType<
  UpdateDatabaseBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UpdateDatabaseBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UpdateDatabaseBadRequestError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateDatabaseBadRequestError$outboundSchema: z.ZodType<
  UpdateDatabaseBadRequestError$Outbound,
  z.ZodTypeDef,
  UpdateDatabaseBadRequestError
> = z.instanceof(UpdateDatabaseBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDatabaseBadRequestError$ {
  /** @deprecated use `UpdateDatabaseBadRequestError$inboundSchema` instead. */
  export const inboundSchema = UpdateDatabaseBadRequestError$inboundSchema;
  /** @deprecated use `UpdateDatabaseBadRequestError$outboundSchema` instead. */
  export const outboundSchema = UpdateDatabaseBadRequestError$outboundSchema;
  /** @deprecated use `UpdateDatabaseBadRequestError$Outbound` instead. */
  export type Outbound = UpdateDatabaseBadRequestError$Outbound;
}
