/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The server could not understand the request due to invalid syntax.
 */
export type UpdateWebsiteBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class UpdateWebsiteBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateWebsiteBadRequestErrorData;

  constructor(err: UpdateWebsiteBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateWebsiteBadRequestError";
  }
}

/** @internal */
export const UpdateWebsiteBadRequestError$inboundSchema: z.ZodType<
  UpdateWebsiteBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new UpdateWebsiteBadRequestError(v);
  });

/** @internal */
export type UpdateWebsiteBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateWebsiteBadRequestError$outboundSchema: z.ZodType<
  UpdateWebsiteBadRequestError$Outbound,
  z.ZodTypeDef,
  UpdateWebsiteBadRequestError
> = z.instanceof(UpdateWebsiteBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebsiteBadRequestError$ {
  /** @deprecated use `UpdateWebsiteBadRequestError$inboundSchema` instead. */
  export const inboundSchema = UpdateWebsiteBadRequestError$inboundSchema;
  /** @deprecated use `UpdateWebsiteBadRequestError$outboundSchema` instead. */
  export const outboundSchema = UpdateWebsiteBadRequestError$outboundSchema;
  /** @deprecated use `UpdateWebsiteBadRequestError$Outbound` instead. */
  export type Outbound = UpdateWebsiteBadRequestError$Outbound;
}
