/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";
import { SwoError } from "./swoerror.js";

/**
 * The server cannot find the requested resource.
 */
export type UpdateEntityByIdNotFoundErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class UpdateEntityByIdNotFoundError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateEntityByIdNotFoundErrorData;

  constructor(
    err: UpdateEntityByIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateEntityByIdNotFoundError";
  }
}

/**
 * Access is unauthorized.
 */
export type UpdateEntityByIdUnauthorizedErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * Access is unauthorized.
 */
export class UpdateEntityByIdUnauthorizedError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateEntityByIdUnauthorizedErrorData;

  constructor(
    err: UpdateEntityByIdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateEntityByIdUnauthorizedError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type UpdateEntityByIdBadRequestErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class UpdateEntityByIdBadRequestError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateEntityByIdBadRequestErrorData;

  constructor(
    err: UpdateEntityByIdBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateEntityByIdBadRequestError";
  }
}

/** @internal */
export const UpdateEntityByIdNotFoundError$inboundSchema: z.ZodType<
  UpdateEntityByIdNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UpdateEntityByIdNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UpdateEntityByIdNotFoundError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateEntityByIdNotFoundError$outboundSchema: z.ZodType<
  UpdateEntityByIdNotFoundError$Outbound,
  z.ZodTypeDef,
  UpdateEntityByIdNotFoundError
> = z.instanceof(UpdateEntityByIdNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateEntityByIdNotFoundError$ {
  /** @deprecated use `UpdateEntityByIdNotFoundError$inboundSchema` instead. */
  export const inboundSchema = UpdateEntityByIdNotFoundError$inboundSchema;
  /** @deprecated use `UpdateEntityByIdNotFoundError$outboundSchema` instead. */
  export const outboundSchema = UpdateEntityByIdNotFoundError$outboundSchema;
  /** @deprecated use `UpdateEntityByIdNotFoundError$Outbound` instead. */
  export type Outbound = UpdateEntityByIdNotFoundError$Outbound;
}

/** @internal */
export const UpdateEntityByIdUnauthorizedError$inboundSchema: z.ZodType<
  UpdateEntityByIdUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UpdateEntityByIdUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UpdateEntityByIdUnauthorizedError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateEntityByIdUnauthorizedError$outboundSchema: z.ZodType<
  UpdateEntityByIdUnauthorizedError$Outbound,
  z.ZodTypeDef,
  UpdateEntityByIdUnauthorizedError
> = z.instanceof(UpdateEntityByIdUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateEntityByIdUnauthorizedError$ {
  /** @deprecated use `UpdateEntityByIdUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema = UpdateEntityByIdUnauthorizedError$inboundSchema;
  /** @deprecated use `UpdateEntityByIdUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    UpdateEntityByIdUnauthorizedError$outboundSchema;
  /** @deprecated use `UpdateEntityByIdUnauthorizedError$Outbound` instead. */
  export type Outbound = UpdateEntityByIdUnauthorizedError$Outbound;
}

/** @internal */
export const UpdateEntityByIdBadRequestError$inboundSchema: z.ZodType<
  UpdateEntityByIdBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: components.CommonDefaultErrorCode$inboundSchema.optional(),
  message: z.string(),
  target: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UpdateEntityByIdBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UpdateEntityByIdBadRequestError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateEntityByIdBadRequestError$outboundSchema: z.ZodType<
  UpdateEntityByIdBadRequestError$Outbound,
  z.ZodTypeDef,
  UpdateEntityByIdBadRequestError
> = z.instanceof(UpdateEntityByIdBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: components.CommonDefaultErrorCode$outboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateEntityByIdBadRequestError$ {
  /** @deprecated use `UpdateEntityByIdBadRequestError$inboundSchema` instead. */
  export const inboundSchema = UpdateEntityByIdBadRequestError$inboundSchema;
  /** @deprecated use `UpdateEntityByIdBadRequestError$outboundSchema` instead. */
  export const outboundSchema = UpdateEntityByIdBadRequestError$outboundSchema;
  /** @deprecated use `UpdateEntityByIdBadRequestError$Outbound` instead. */
  export type Outbound = UpdateEntityByIdBadRequestError$Outbound;
}
