/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The server cannot find the requested resource.
 */
export type UpdateCompositeMetricNotFoundErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server cannot find the requested resource.
 */
export class UpdateCompositeMetricNotFoundError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateCompositeMetricNotFoundErrorData;

  constructor(err: UpdateCompositeMetricNotFoundErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateCompositeMetricNotFoundError";
  }
}

/**
 * Access is forbidden.
 */
export type UpdateCompositeMetricForbiddenErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * Access is forbidden.
 */
export class UpdateCompositeMetricForbiddenError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateCompositeMetricForbiddenErrorData;

  constructor(err: UpdateCompositeMetricForbiddenErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateCompositeMetricForbiddenError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type UpdateCompositeMetricBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class UpdateCompositeMetricBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: UpdateCompositeMetricBadRequestErrorData;

  constructor(err: UpdateCompositeMetricBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "UpdateCompositeMetricBadRequestError";
  }
}

/** @internal */
export const UpdateCompositeMetricNotFoundError$inboundSchema: z.ZodType<
  UpdateCompositeMetricNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new UpdateCompositeMetricNotFoundError(v);
  });

/** @internal */
export type UpdateCompositeMetricNotFoundError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateCompositeMetricNotFoundError$outboundSchema: z.ZodType<
  UpdateCompositeMetricNotFoundError$Outbound,
  z.ZodTypeDef,
  UpdateCompositeMetricNotFoundError
> = z.instanceof(UpdateCompositeMetricNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCompositeMetricNotFoundError$ {
  /** @deprecated use `UpdateCompositeMetricNotFoundError$inboundSchema` instead. */
  export const inboundSchema = UpdateCompositeMetricNotFoundError$inboundSchema;
  /** @deprecated use `UpdateCompositeMetricNotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    UpdateCompositeMetricNotFoundError$outboundSchema;
  /** @deprecated use `UpdateCompositeMetricNotFoundError$Outbound` instead. */
  export type Outbound = UpdateCompositeMetricNotFoundError$Outbound;
}

/** @internal */
export const UpdateCompositeMetricForbiddenError$inboundSchema: z.ZodType<
  UpdateCompositeMetricForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new UpdateCompositeMetricForbiddenError(v);
  });

/** @internal */
export type UpdateCompositeMetricForbiddenError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateCompositeMetricForbiddenError$outboundSchema: z.ZodType<
  UpdateCompositeMetricForbiddenError$Outbound,
  z.ZodTypeDef,
  UpdateCompositeMetricForbiddenError
> = z.instanceof(UpdateCompositeMetricForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCompositeMetricForbiddenError$ {
  /** @deprecated use `UpdateCompositeMetricForbiddenError$inboundSchema` instead. */
  export const inboundSchema =
    UpdateCompositeMetricForbiddenError$inboundSchema;
  /** @deprecated use `UpdateCompositeMetricForbiddenError$outboundSchema` instead. */
  export const outboundSchema =
    UpdateCompositeMetricForbiddenError$outboundSchema;
  /** @deprecated use `UpdateCompositeMetricForbiddenError$Outbound` instead. */
  export type Outbound = UpdateCompositeMetricForbiddenError$Outbound;
}

/** @internal */
export const UpdateCompositeMetricBadRequestError$inboundSchema: z.ZodType<
  UpdateCompositeMetricBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int(),
  message: z.string(),
  target: z.string().optional(),
})
  .transform((v) => {
    return new UpdateCompositeMetricBadRequestError(v);
  });

/** @internal */
export type UpdateCompositeMetricBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const UpdateCompositeMetricBadRequestError$outboundSchema: z.ZodType<
  UpdateCompositeMetricBadRequestError$Outbound,
  z.ZodTypeDef,
  UpdateCompositeMetricBadRequestError
> = z.instanceof(UpdateCompositeMetricBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCompositeMetricBadRequestError$ {
  /** @deprecated use `UpdateCompositeMetricBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    UpdateCompositeMetricBadRequestError$inboundSchema;
  /** @deprecated use `UpdateCompositeMetricBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    UpdateCompositeMetricBadRequestError$outboundSchema;
  /** @deprecated use `UpdateCompositeMetricBadRequestError$Outbound` instead. */
  export type Outbound = UpdateCompositeMetricBadRequestError$Outbound;
}
