/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";
import { SwoError } from "./swoerror.js";

/**
 * Server error
 */
export type ValidateMgmtAccountOnboardingInternalServerErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * Server error
 */
export class ValidateMgmtAccountOnboardingInternalServerError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ValidateMgmtAccountOnboardingInternalServerErrorData;

  constructor(
    err: ValidateMgmtAccountOnboardingInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "ValidateMgmtAccountOnboardingInternalServerError";
  }
}

/**
 * Access is unauthorized.
 */
export type ValidateMgmtAccountOnboardingUnauthorizedErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * Access is unauthorized.
 */
export class ValidateMgmtAccountOnboardingUnauthorizedError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ValidateMgmtAccountOnboardingUnauthorizedErrorData;

  constructor(
    err: ValidateMgmtAccountOnboardingUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "ValidateMgmtAccountOnboardingUnauthorizedError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type ValidateMgmtAccountOnboardingBadRequestErrorData = {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Supporting description of the error
   */
  message: string;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class ValidateMgmtAccountOnboardingBadRequestError extends SwoError {
  /**
   * Uniquely identifies an error condition.
   */
  code?: components.CommonDefaultErrorCode | undefined;
  /**
   * Indicates the invalid field
   */
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ValidateMgmtAccountOnboardingBadRequestErrorData;

  constructor(
    err: ValidateMgmtAccountOnboardingBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "ValidateMgmtAccountOnboardingBadRequestError";
  }
}

/** @internal */
export const ValidateMgmtAccountOnboardingInternalServerError$inboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: components.CommonDefaultErrorCode$inboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new ValidateMgmtAccountOnboardingInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type ValidateMgmtAccountOnboardingInternalServerError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const ValidateMgmtAccountOnboardingInternalServerError$outboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingInternalServerError$Outbound,
    z.ZodTypeDef,
    ValidateMgmtAccountOnboardingInternalServerError
  > = z.instanceof(ValidateMgmtAccountOnboardingInternalServerError)
    .transform(v => v.data$)
    .pipe(z.object({
      code: components.CommonDefaultErrorCode$outboundSchema.optional(),
      message: z.string(),
      target: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValidateMgmtAccountOnboardingInternalServerError$ {
  /** @deprecated use `ValidateMgmtAccountOnboardingInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    ValidateMgmtAccountOnboardingInternalServerError$inboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    ValidateMgmtAccountOnboardingInternalServerError$outboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingInternalServerError$Outbound` instead. */
  export type Outbound =
    ValidateMgmtAccountOnboardingInternalServerError$Outbound;
}

/** @internal */
export const ValidateMgmtAccountOnboardingUnauthorizedError$inboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: components.CommonDefaultErrorCode$inboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new ValidateMgmtAccountOnboardingUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type ValidateMgmtAccountOnboardingUnauthorizedError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const ValidateMgmtAccountOnboardingUnauthorizedError$outboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingUnauthorizedError$Outbound,
    z.ZodTypeDef,
    ValidateMgmtAccountOnboardingUnauthorizedError
  > = z.instanceof(ValidateMgmtAccountOnboardingUnauthorizedError)
    .transform(v => v.data$)
    .pipe(z.object({
      code: components.CommonDefaultErrorCode$outboundSchema.optional(),
      message: z.string(),
      target: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValidateMgmtAccountOnboardingUnauthorizedError$ {
  /** @deprecated use `ValidateMgmtAccountOnboardingUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    ValidateMgmtAccountOnboardingUnauthorizedError$inboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    ValidateMgmtAccountOnboardingUnauthorizedError$outboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingUnauthorizedError$Outbound` instead. */
  export type Outbound =
    ValidateMgmtAccountOnboardingUnauthorizedError$Outbound;
}

/** @internal */
export const ValidateMgmtAccountOnboardingBadRequestError$inboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: components.CommonDefaultErrorCode$inboundSchema.optional(),
    message: z.string(),
    target: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new ValidateMgmtAccountOnboardingBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type ValidateMgmtAccountOnboardingBadRequestError$Outbound = {
  code?: string | undefined;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const ValidateMgmtAccountOnboardingBadRequestError$outboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingBadRequestError$Outbound,
    z.ZodTypeDef,
    ValidateMgmtAccountOnboardingBadRequestError
  > = z.instanceof(ValidateMgmtAccountOnboardingBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      code: components.CommonDefaultErrorCode$outboundSchema.optional(),
      message: z.string(),
      target: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValidateMgmtAccountOnboardingBadRequestError$ {
  /** @deprecated use `ValidateMgmtAccountOnboardingBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    ValidateMgmtAccountOnboardingBadRequestError$inboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    ValidateMgmtAccountOnboardingBadRequestError$outboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingBadRequestError$Outbound` instead. */
  export type Outbound = ValidateMgmtAccountOnboardingBadRequestError$Outbound;
}
