/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Server error
 */
export type ValidateMgmtAccountOnboardingInternalServerErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * Server error
 */
export class ValidateMgmtAccountOnboardingInternalServerError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ValidateMgmtAccountOnboardingInternalServerErrorData;

  constructor(err: ValidateMgmtAccountOnboardingInternalServerErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "ValidateMgmtAccountOnboardingInternalServerError";
  }
}

/**
 * Access is unauthorized.
 */
export type ValidateMgmtAccountOnboardingUnauthorizedErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * Access is unauthorized.
 */
export class ValidateMgmtAccountOnboardingUnauthorizedError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ValidateMgmtAccountOnboardingUnauthorizedErrorData;

  constructor(err: ValidateMgmtAccountOnboardingUnauthorizedErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "ValidateMgmtAccountOnboardingUnauthorizedError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type ValidateMgmtAccountOnboardingBadRequestErrorData = {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  /**
   * Supporting description of the error
   */
  message: string;
  target?: string | undefined;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class ValidateMgmtAccountOnboardingBadRequestError extends Error {
  /**
   * HTTP status code as defined in RFC 2817
   */
  code: number;
  target?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ValidateMgmtAccountOnboardingBadRequestErrorData;

  constructor(err: ValidateMgmtAccountOnboardingBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.target != null) this.target = err.target;

    this.name = "ValidateMgmtAccountOnboardingBadRequestError";
  }
}

/** @internal */
export const ValidateMgmtAccountOnboardingInternalServerError$inboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  })
    .transform((v) => {
      return new ValidateMgmtAccountOnboardingInternalServerError(v);
    });

/** @internal */
export type ValidateMgmtAccountOnboardingInternalServerError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const ValidateMgmtAccountOnboardingInternalServerError$outboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingInternalServerError$Outbound,
    z.ZodTypeDef,
    ValidateMgmtAccountOnboardingInternalServerError
  > = z.instanceof(ValidateMgmtAccountOnboardingInternalServerError)
    .transform(v => v.data$)
    .pipe(z.object({
      code: z.number().int(),
      message: z.string(),
      target: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValidateMgmtAccountOnboardingInternalServerError$ {
  /** @deprecated use `ValidateMgmtAccountOnboardingInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    ValidateMgmtAccountOnboardingInternalServerError$inboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    ValidateMgmtAccountOnboardingInternalServerError$outboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingInternalServerError$Outbound` instead. */
  export type Outbound =
    ValidateMgmtAccountOnboardingInternalServerError$Outbound;
}

/** @internal */
export const ValidateMgmtAccountOnboardingUnauthorizedError$inboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  })
    .transform((v) => {
      return new ValidateMgmtAccountOnboardingUnauthorizedError(v);
    });

/** @internal */
export type ValidateMgmtAccountOnboardingUnauthorizedError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const ValidateMgmtAccountOnboardingUnauthorizedError$outboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingUnauthorizedError$Outbound,
    z.ZodTypeDef,
    ValidateMgmtAccountOnboardingUnauthorizedError
  > = z.instanceof(ValidateMgmtAccountOnboardingUnauthorizedError)
    .transform(v => v.data$)
    .pipe(z.object({
      code: z.number().int(),
      message: z.string(),
      target: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValidateMgmtAccountOnboardingUnauthorizedError$ {
  /** @deprecated use `ValidateMgmtAccountOnboardingUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    ValidateMgmtAccountOnboardingUnauthorizedError$inboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    ValidateMgmtAccountOnboardingUnauthorizedError$outboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingUnauthorizedError$Outbound` instead. */
  export type Outbound =
    ValidateMgmtAccountOnboardingUnauthorizedError$Outbound;
}

/** @internal */
export const ValidateMgmtAccountOnboardingBadRequestError$inboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.number().int(),
    message: z.string(),
    target: z.string().optional(),
  })
    .transform((v) => {
      return new ValidateMgmtAccountOnboardingBadRequestError(v);
    });

/** @internal */
export type ValidateMgmtAccountOnboardingBadRequestError$Outbound = {
  code: number;
  message: string;
  target?: string | undefined;
};

/** @internal */
export const ValidateMgmtAccountOnboardingBadRequestError$outboundSchema:
  z.ZodType<
    ValidateMgmtAccountOnboardingBadRequestError$Outbound,
    z.ZodTypeDef,
    ValidateMgmtAccountOnboardingBadRequestError
  > = z.instanceof(ValidateMgmtAccountOnboardingBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      code: z.number().int(),
      message: z.string(),
      target: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValidateMgmtAccountOnboardingBadRequestError$ {
  /** @deprecated use `ValidateMgmtAccountOnboardingBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    ValidateMgmtAccountOnboardingBadRequestError$inboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    ValidateMgmtAccountOnboardingBadRequestError$outboundSchema;
  /** @deprecated use `ValidateMgmtAccountOnboardingBadRequestError$Outbound` instead. */
  export type Outbound = ValidateMgmtAccountOnboardingBadRequestError$Outbound;
}
