/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SwoCore } from "../core.js";
import { dlv } from "../lib/dlv.js";
import { encodeFormQuery } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { SwoError } from "../models/errors/swoerror.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";
import {
  createPageIterator,
  haltIterator,
  PageIterator,
  Paginator,
  URL_OVERRIDE,
} from "../types/operations.js";

/**
 * List metrics
 *
 * @remarks
 * List metrics available within a time period.
 */
export function metricsListMetrics(
  client: SwoCore,
  request: operations.ListMetricsRequest,
  options?: RequestOptions & { [URL_OVERRIDE]?: URL },
): APIPromise<
  PageIterator<
    Result<
      operations.ListMetricsResponse,
      | errors.CommonUnauthorizedErrorResponse
      | errors.CommonInternalErrorResponse
      | SwoError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    { url: string }
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: SwoCore,
  request: operations.ListMetricsRequest,
  options?: RequestOptions & { [URL_OVERRIDE]?: URL },
): Promise<
  [
    PageIterator<
      Result<
        operations.ListMetricsResponse,
        | errors.CommonUnauthorizedErrorResponse
        | errors.CommonInternalErrorResponse
        | SwoError
        | ResponseValidationError
        | ConnectionError
        | RequestAbortedError
        | RequestTimeoutError
        | InvalidRequestError
        | UnexpectedClientError
        | SDKValidationError
      >,
      { url: string }
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => operations.ListMetricsRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [haltIterator(parsed), { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const path = options?.[URL_OVERRIDE]
    ? options[URL_OVERRIDE].pathname
    : pathToFunc("/v1/metrics")();

  const query = options?.[URL_OVERRIDE]
    ? options[URL_OVERRIDE].search.substring(1)
    : encodeFormQuery({
      "endTime": payload.endTime,
      "name": payload.name,
      "pageSize": payload.pageSize,
      "skipToken": payload.skipToken,
      "startTime": payload.startTime,
    }, { explode: false });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiToken);
  const securityInput = secConfig == null ? {} : { apiToken: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "listMetrics",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiToken,
    retryConfig: options?.retries
      || client._options.retryConfig
      || {
        strategy: "backoff",
        backoff: {
          initialInterval: 500,
          maxInterval: 60000,
          exponent: 1.5,
          maxElapsedTime: 3600000,
        },
        retryConnectionErrors: true,
      }
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["5XX"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [haltIterator(requestRes), { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["401", "4XX", "500", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [haltIterator(doResult), { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result, raw] = await M.match<
    operations.ListMetricsResponse,
    | errors.CommonUnauthorizedErrorResponse
    | errors.CommonInternalErrorResponse
    | SwoError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.ListMetricsResponse$inboundSchema, {
      key: "Result",
    }),
    M.jsonErr(401, errors.CommonUnauthorizedErrorResponse$inboundSchema),
    M.jsonErr(500, errors.CommonInternalErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [haltIterator(result), {
      status: "complete",
      request: req,
      response,
    }];
  }

  const nextFunc = (
    responseData: unknown,
  ): {
    next: Paginator<
      Result<
        operations.ListMetricsResponse,
        | errors.CommonUnauthorizedErrorResponse
        | errors.CommonInternalErrorResponse
        | SwoError
        | ResponseValidationError
        | ConnectionError
        | RequestAbortedError
        | RequestTimeoutError
        | InvalidRequestError
        | UnexpectedClientError
        | SDKValidationError
      >
    >;
    "~next"?: { url: string };
  } => {
    let nextURL = dlv(responseData, "pageInfo.nextPage");
    if (typeof nextURL !== "string") {
      return { next: () => null };
    }

    if (nextURL.startsWith("/")) {
      nextURL = `${client._baseURL?.origin}${nextURL}`;
    }

    try {
      new URL(nextURL);
    } catch (_error) {
      return { next: () => null };
    }

    const nextVal = () =>
      metricsListMetrics(
        client,
        {
          ...request,
        },
        { ...options, [URL_OVERRIDE]: new URL(nextURL) },
      );

    return { next: nextVal, "~next": { url: nextURL } };
  };

  const page = { ...result, ...nextFunc(raw) };
  return [{ ...page, ...createPageIterator(page, (v) => !v.ok) }, {
    status: "complete",
    request: req,
    response,
  }];
}
